mobs:register_mob("nssm:crocodile", {
	type = "monster",
	hp_max = 36,
	hp_min = 25,
	collisionbox = {-.45, -.3, -.45, .45, .3, .45},
	visual = "mesh",
	mesh = "crocodile.x",
	textures = {{"croco.png"}},
  	sounds = {
		random = "crocod",
	},
	visual_size = {x= 4, y= 4},
	makes_footstep_sound = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 2,
	damage = 5,
	jump = true,
	drops = {
		{name = "nssm:energy_pearl", chance = 1, min = 1, max = 2},
		{name = "nssm:crocodile_heart", chance = 1, min = 1, max = 1},
		{name = "nssm:crocodile_ribs", chance = 1, min = 1, max = 2},
		{name = "nssm:crocodile_tail", chance = 2, min = 1, max = 1},
		{name = "nssm:crocodile_skin", chance = 3, min = 1, max = 1}
	},
	armor = 60,
	reach = 2,
	lava_damage = 10,
	fire_damage = 10,
	group_attack = true,
	attack_animals = true,
	blood_texture = "nssm_blood.png",
	attack_type = "dogfight",
	animation = {
		speed_normal = 25,
		speed_run = 29,
		stand_start = 1,
		stand_end = 80,
		walk_start = 230,
		walk_end = 270,
		run_start = 230,
		run_end = 270,
		punch_start = 205,
		punch_end = 220,
		--swim_start = 100,
		--swim_end = 140,
	}
})
