mobs:register_mob("nssm:octopus", {
	type = "monster",
	hp_max = 32,
	hp_min = 25,
	collisionbox = {-.9, -.5, -.9, .9, .92, .9},
	visual = "mesh",
	mesh = "octopus.x",
	textures = {{"octopus.png"}},
	visual_size = {x= 4, y= 4},
	view_range = 25,
	fly = true,
	fly_in = "default:water_source",
	fall_speed = -20,
	walk_velocity = 1.5,
	run_velocity = 3,
	damage = 5,
	reach = 2,
	rotate = 270,
	jump = false,
	jump_chance = 0,
	jump_height = 0,
  	sounds = {
		random = "octopus",
	},
	drops = {
		{name = "nssm:energy_pearl", chance = 1, min = 2, max = 3},
		{name = "nssm:tentacle", chance = 1, min = 1, max = 8},
		{name = "nssm:tentacle_curly", chance = 3, min = 1, max = 2}
	},
	armor = 70,
	lava_damage = 10,
	fire_damage = 10,
	group_attack = true,
	attack_animals = true,
	blood_texture = "nssm_blood_blue.png",
	attack_type = "dogfight",
	animation = {
		speed_normal = 25,
		speed_run = 35,
		stand_start = 1,
		stand_end = 50,
		walk_start = 60,
		walk_end = 100,
		run_start = 60,
		run_end = 100,
		punch_start = 120,
		punch_end = 160
	}
})

mobs:register_mob("nssm:xgaloctopus", {
	type = "monster",
	hp_max = 30,
	hp_min = 27,
	collisionbox = {-.25, -.25, -.25, .25, .25, .25},
	visual = "mesh",
	mesh = "octopus.x",
	textures = {{"xgaloctopus.png"}},
	visual_size = {x= 1, y= 1},
	view_range = 25,
	fly = true,
	fly_in = "default:water_source",
	fall_speed = -20,
	walk_velocity = 1.5,
	run_velocity = 3,
	damage = 5,
	reach = 1,
	rotate = 270,
	jump = false,
	jump_chance = 0,
	jump_height = 0,
	sounds = {
		random = "octopus",
	},
	drops = {
		{name = "nssm:energy_pearl", chance = 1, min = 2, max = 3},
		{name = "nssm:tentacle", chance = 1, min = 1, max = 8}
	},
	armor = 60,
	lava_damage = 10,
	fire_damage = 10,
	group_attack = true,
	attack_animals = true,
	blood_texture = "nssm_blood_blue.png",
	attack_type = "dogfight",
	animation = {
		speed_normal = 25,
		speed_run = 35,
		stand_start = 1,
		stand_end = 50,
		walk_start = 60,
		walk_end = 100,
		run_start = 60,
		run_end = 100,
		punch_start = 120,
		punch_end = 160
	}
})
