--[[
Map Tools: alias definitions

Copyright (c) 2012-2017 Hugo Locurcio and contributors.
Licensed under the zlib license. See LICENSE.md for more information.
--]]
if maptools.config["hide_from_creative_inventory"] == 1 then

core.register_alias("adminpick", "maptools:pick_admin")
core.register_alias("adminpickaxe", "maptools:pick_admin")
core.register_alias("admin_pick", "maptools:pick_admin")
core.register_alias("admin_pickaxe", "maptools:pick_admin")
core.register_alias("pick_admin", "maptools:pick_admin")
core.register_alias("pickaxe_admin", "maptools:pick_admin")
core.register_alias("pickadmin", "maptools:pick_admin")
core.register_alias("pickaxeadmin", "maptools:pick_admin")
core.register_alias("adminpickdrops", "maptools:pick_admin_with_drops")
core.register_alias("adminpickaxedrops", "maptools:pick_admin_with_drops")
core.register_alias("admin_pick_drops", "maptools:pick_admin_with_drops")
core.register_alias("admin_pickaxe_drops", "maptools:pick_admin_with_drops")
core.register_alias("pick_admin_drops", "maptools:pick_admin_with_drops")
core.register_alias("pickaxe_admin_drops", "maptools:pick_admin_with_drops")
core.register_alias("pickadmindrops", "maptools:pick_admin_with_drops")
core.register_alias("pickaxeadmindrops", "maptools:pick_admin_with_drops")
core.register_alias("infinitefuel", "maptools:infinitefuel")
core.register_alias("infinite_fuel", "maptools:infinitefuel")
core.register_alias("ifuel", "maptools:infinitefuel")
core.register_alias("superapple", "maptools:superapple")
core.register_alias("super_apple", "maptools:superapple")
core.register_alias("sapple", "maptools:superapple")
core.register_alias("damage_1", "maptools:damage_1")
core.register_alias("damage_2", "maptools:damage_2")
core.register_alias("damage_3", "maptools:damage_3")
core.register_alias("damage_4", "maptools:damage_4")
core.register_alias("damage_5", "maptools:damage_5")
core.register_alias("killblock", "maptools:kill")
core.register_alias("kill_block", "maptools:kill")
core.register_alias("lightbulb", "maptools:lightbulb")
core.register_alias("light_bulb", "maptools:lightbulb")
core.register_alias("fullclip", "maptools:fullclip")
core.register_alias("full_clip", "maptools:fullclip")
core.register_alias("fclip", "maptools:fullclip")
core.register_alias("full_clip", "maptools:fullclip")
core.register_alias("full_clip_face", "maptools:fullclip_face")
core.register_alias("fullclip_face", "maptools:fullclip_face")
core.register_alias("fullclipface", "maptools:fullclip_face")
core.register_alias("player_clip_top", "maptools:playerclip_top")
core.register_alias("playerclip_top", "maptools:playerclip_top")
core.register_alias("playercliptop", "maptools:playerclip_top")

--core.register_alias("stone_u", "maptools:stone")
core.register_alias("cobble_u", "maptools:cobble")
core.register_alias("stonebrick_u", "maptools:stone_brick")
core.register_alias("mossycobble_u", "maptools:mossycobble")
core.register_alias("mossy_cobble_u", "maptools:mossycobble")
--core.register_alias("gravel_u", "maptools:gravel")
--core.register_alias("wood_u", "maptools:wood")
--core.register_alias("tree_u", "maptools:tree")
--core.register_alias("leaves_u", "maptools:leaves")
--core.register_alias("brick_u", "maptools:brick")
--core.register_alias("dirt_u", "maptools:dirt")
core.register_alias("soilwet_u", "maptools:soil_wet")
--core.register_alias("grass_u", "maptools:grass")
--core.register_alias("sand_u", "maptools:sand")
--core.register_alias("glass_u", "maptools:glass")
--core.register_alias("sandstone_u", "maptools:sandstone")
--core.register_alias("desert_stone_u", "maptools:desert_stone")
--core.register_alias("desertstone_u", "maptools:desert_stone")
--core.register_alias("desert_sand_u", "maptools:desert_sand")
--core.register_alias("desertsand_u", "maptools:desert_sand")
end