
local B = {name = "default:bedrock_barrier", force_place = true}
local G = {name = "mapgen:green_tile", force_place = true}
local q = {name = "mapgen:floortile", force_place = true}
local T = {name = "mapgen:dungeon_tile", force_place = true}
local c = {name = "mapgen:beamoswall", force_place = true}
local t = {name = "mapgen:dungeon_brick", force_place = true}
local u = {name = "mapgen:dark_sandstone_decorated2", force_place = true}
local U = {name = "mapgen:dark_sandstone", force_place = true}
local D0 = {name = "mapgen:dartblock", force_place = true}
local D1 = {name = "mapgen:dartblock", param2 = 1, force_place = true}
local D2 = {name = "mapgen:dartblock", param2 = 2, force_place = true}
local D3 = {name = "mapgen:dartblock", param2 = 3, force_place = true}
local F = {name = "mapgen:flameblock", force_place = true}
local L = {name = "mapgen:dungeon_torch", force_place = true}
local C = {name = "mapgen:limestone_pale", force_place = true}
local O = {name = "mapgen:serpentine", force_place = true}
local l = {name = "default:glass", force_place = true}
local H = {name = "mapgen:dark_sandstone_tile", force_place = true}
local C0 = {name = "mapgen:chest", force_place = true}
local C1 = {name = "mapgen:chest", param2 = 1, force_place = true}
local C2 = {name = "mapgen:chest", param2 = 2, force_place = true}
local C3 = {name = "mapgen:chest", param2 = 3, force_place = true}
local M0 = {name = "mobs_loz:mimic_chest", force_place = true}
local M1 = {name = "mobs_loz:mimic_chest", param2 = 1, force_place = true}
local M2 = {name = "mobs_loz:mimic_chest", param2 = 2, force_place = true}
local M3 = {name = "mobs_loz:mimic_chest", param2 = 3, force_place = true}
local P1 = {name = "mapgen:pot", force_place = true}
local P2 = {name = "mapgen:pot2", force_place = true}
local V = {name = "default:lava_source", force_place = true}
local Q = {name = "mapgen:granite_black", force_place = true}
local CH = {name = "mapgen:chalk", force_place = true}
local M = {name = "mapgen:magnblock", force_place = true}
local h = {name = "mapgen:spikes", force_place = true}
local b = {name = "default:bedrock", force_place = true}
local d = {name = "stairs:slab_limestone_pale", force_place = true}
local Hi = {name = "doors:hidden", force_place = true}
local W = {name = "mapgen:wallring", force_place = true}
local s = {name = "mapgen:sinkingsand", force_place = true}
local D = {name = "default:diamite", force_place = true}
local S = {name = "mapgen:salt_block", force_place = true}
local A = {name = "default:fresh_water_source", force_place = true}
local m = {name = "mapgen:crate", force_place = true}

lom_puzzle_box = {size = {x = 23, y = 24, z = 23}, data = {
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,G,G,G,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,G,I,I,I,G,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,G,I,I,I,G,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,G,I,G,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,G,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,q,I,I,I,I,B,
B,I,T,T,T,T,T,T,T,T,T,T,I,I,c,G,G,I,G,G,c,I,B,
B,I,t,t,t,t,t,t,t,t,t,t,I,I,G,c,G,I,G,c,G,I,B,
B,I,t,t,t,t,t,t,t,t,t,t,I,I,c,c,c,G,c,c,c,I,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,
B,I,u,u,u,u,u,I,I,I,I,u,I,I,I,I,u,u,u,u,u,I,B,
B,I,U,U,U,U,U,I,I,I,I,U,I,I,I,I,U,U,U,U,I,I,B,
B,I,U,U,U,U,U,I,I,I,I,I,I,I,I,I,U,U,U,U,I,I,B,
B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,U,I,I,B,
B,I,I,I,I,I,I,Q,B,B,B,B,B,B,B,I,I,I,I,U,I,U,B,
B,Q,Q,Q,Q,Q,Q,I,I,I,I,I,I,I,I,I,I,Q,Q,Q,I,Q,B,
B,D3,F,I,I,I,I,I,I,I,I,I,B,I,I,I,B,I,I,I,I,L,B,
B,F,I,I,I,I,I,I,C,C,C,I,C,C,C,B,B,I,I,I,I,I,B,
B,B,B,B,B,B,B,B,C,C,C,I,C,C,C,_,_,B,B,B,B,B,B,
_,_,_,_,_,_,_,_,C,C,O,C,O,C,C,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,C,C,C,O,C,C,C,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,C,l,C,C,C,l,C,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,C,C,l,C,l,C,C,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,C,C,C,C,C,C,C,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,C,C,C,C,C,C,C,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,t,t,t,t,t,t,I,t,t,t,I,I,q,q,q,q,q,q,q,I,B,
B,T,L,C2,M2,M2,C2,L,T,L,P2,L,T,c,I,I,I,I,I,I,I,c,B,
B,t,I,I,I,I,I,I,t,I,I,I,t,G,I,I,I,I,I,I,I,G,B,
B,t,I,I,I,I,I,I,t,I,I,I,t,c,I,I,I,I,I,I,I,c,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,H,H,H,H,H,I,I,I,U,H,U,I,I,I,H,H,H,H,H,I,B,
B,u,M2,P1,M2,I,M2,u,I,V,u,L,u,V,I,u,I,I,D2,I,I,u,B,
B,U,I,I,I,I,I,U,I,V,U,I,U,V,I,U,I,I,I,I,D2,U,B,
B,U,I,I,I,I,I,U,I,V,I,U,I,V,I,U,I,I,I,I,D2,U,B,
B,I,U,U,U,U,U,I,I,I,I,I,I,I,I,I,U,U,U,U,U,I,B,
B,I,I,I,I,I,I,I,B,B,B,B,B,B,B,I,I,I,I,I,U,Q,B,
B,Q,Q,Q,Q,Q,I,Q,I,I,I,I,I,I,I,I,I,Q,Q,Q,Q,Q,B,
B,F,I,I,I,I,B,B,C,C,C,C,C,C,C,I,B,I,I,I,I,I,B,
B,I,I,I,I,I,B,C,I,I,I,I,I,I,I,C,B,I,I,I,I,I,B,
B,B,B,B,B,B,_,C,I,I,I,I,I,I,I,C,_,B,B,B,B,B,B,
_,_,_,_,_,_,_,C,I,I,I,I,I,I,I,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,I,I,I,I,I,I,I,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,I,I,I,I,I,I,I,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,I,I,I,I,I,I,I,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,I,I,I,I,I,I,I,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,C,C,C,C,C,C,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,t,t,t,t,t,t,I,t,t,t,I,I,q,q,q,q,q,q,q,I,B,
B,T,I,I,C2,C2,I,I,T,I,I,I,T,c,I,I,I,I,I,I,D1,c,B,
B,t,I,I,I,I,I,I,t,I,I,I,t,G,I,I,I,I,I,I,I,G,B,
B,t,I,I,I,I,I,I,t,I,I,I,t,c,I,I,I,I,I,I,I,c,B,
B,B,B,B,B,B,B,B,B,B,B,{name = "fabric:sheet_dark_grey", force_place = true},B,B,B,B,B,B,B,B,B,B,B,
B,I,H,H,H,H,H,I,I,I,H,I,H,I,I,I,H,H,H,H,H,I,B,
B,u,I,C2,I,M2,I,u,u,u,u,I,u,u,u,u,I,I,I,I,I,u,B,
B,U,I,I,I,I,I,U,U,U,U,I,U,U,U,U,I,I,I,I,I,U,B,
B,U,I,I,I,I,I,U,I,V,I,U,I,V,I,U,I,I,I,I,I,U,B,
B,I,U,U,U,U,U,I,I,I,I,I,I,I,I,I,U,U,U,U,U,I,B,
B,I,I,I,I,I,I,I,B,B,B,B,B,B,B,I,I,I,I,I,I,I,B,
B,Q,Q,Q,Q,Q,I,I,I,I,I,I,I,I,I,I,I,Q,Q,Q,Q,Q,B,
B,I,I,L,I,I,B,I,C,C,C,C,C,C,C,I,B,I,I,I,I,I,B,
B,I,I,I,I,I,B,C,I,I,I,I,I,I,I,C,B,I,I,I,I,I,B,
B,B,B,B,B,B,_,C,I,I,I,I,I,I,I,C,_,B,B,B,B,B,B,
_,_,_,_,_,_,_,O,I,I,I,I,I,I,I,O,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,I,I,I,I,I,I,I,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,l,I,I,I,I,I,I,I,l,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,I,I,I,I,I,I,I,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,I,I,I,I,I,I,I,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,C,C,C,C,C,C,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,t,t,t,t,t,t,t,t,t,t,I,I,q,q,q,q,q,q,q,I,B,
B,T,I,I,I,I,I,I,I,I,I,I,T,c,D3,I,I,I,I,I,I,c,B,
B,t,I,I,I,I,I,I,I,I,I,I,t,G,I,I,I,I,I,I,I,G,B,
B,t,I,I,I,I,I,I,t,I,I,I,t,c,I,I,I,I,I,I,I,c,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,H,H,H,H,H,H,H,H,H,H,H,H,H,H,H,H,H,H,H,I,B,
B,u,M2,I,M2,I,M2,CH,M,I,I,I,I,I,M,P2,I,I,I,I,C1,u,B,
B,U,I,I,I,I,I,M,V,M,I,I,I,M,V,M,I,I,I,I,I,U,B,
B,U,I,I,I,I,I,U,U,U,U,U,U,U,U,U,I,I,I,I,I,U,B,
B,I,U,U,U,U,U,I,I,I,I,I,I,I,I,I,U,U,U,U,U,I,B,
B,I,I,I,V,I,I,I,B,B,B,B,B,B,B,I,I,I,V,I,I,I,B,
B,Q,Q,Q,Q,Q,I,I,D0,D0,D0,I,I,I,I,I,I,Q,I,I,I,I,B,
B,I,I,I,I,I,B,I,C,C,C,C,C,C,C,I,B,I,b,b,b,b,B,
B,I,I,I,I,I,B,C,I,I,I,I,I,I,I,C,B,I,b,b,b,b,B,
B,B,B,B,B,B,_,C,I,I,I,I,I,I,I,C,_,B,B,B,B,B,B,
_,_,_,_,_,_,_,C,I,I,I,I,I,I,I,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,O,I,I,I,I,I,I,I,O,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,I,I,I,I,I,I,I,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,l,I,I,I,I,I,I,I,l,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,I,I,I,I,I,I,I,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,C,C,C,C,C,C,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,t,t,t,t,t,t,I,t,t,t,I,I,q,q,q,q,q,q,q,I,B,
B,T,I,I,I,I,I,I,T,L,I,L,T,c,I,I,I,I,I,I,D1,c,B,
B,t,I,I,I,I,I,I,t,I,I,I,t,G,I,I,I,I,I,I,I,G,B,
B,t,I,I,I,I,I,I,t,I,I,I,t,c,I,I,I,I,I,I,I,c,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,H,H,H,H,H,I,I,I,I,H,I,I,I,I,H,H,H,H,H,I,B,
B,u,I,M2,I,M2,I,u,u,u,u,I,u,u,u,u,I,I,I,I,I,u,B,
B,U,I,I,I,I,I,U,U,U,U,I,U,U,U,U,I,I,I,I,I,U,B,
B,U,I,I,I,I,I,U,I,V,I,U,I,V,I,U,I,I,I,I,I,U,B,
B,I,U,U,U,U,U,I,I,I,I,I,I,I,I,I,U,U,U,U,U,I,B,
B,I,I,I,I,I,I,I,B,B,B,B,B,B,B,I,I,I,I,I,I,I,B,
B,Q,Q,Q,Q,Q,I,I,I,I,I,I,I,I,I,I,I,Q,Q,Q,Q,Q,B,
B,F,F,F,F,F,B,I,C,C,C,C,C,C,C,I,B,I,I,h,h,h,B,
B,F,I,F,I,F,B,C,I,I,I,I,I,I,I,C,B,I,I,I,I,I,B,
B,B,B,B,B,B,_,C,I,I,I,I,I,I,I,C,_,B,B,B,B,B,B,
_,_,_,_,_,_,_,O,I,I,I,I,I,I,I,O,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,I,I,I,I,I,I,I,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,l,I,I,I,I,I,I,I,l,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,I,I,I,I,I,I,I,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,I,I,I,I,I,I,I,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,C,C,C,C,C,C,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,t,t,t,t,t,t,I,I,I,I,I,I,q,q,q,q,q,q,q,I,B,
B,T,I,I,I,I,I,I,T,T,T,T,I,c,D3,I,I,I,I,I,I,c,B,
B,t,I,I,I,I,I,I,t,t,t,t,I,G,I,I,I,I,I,I,I,G,B,
B,t,I,I,I,I,I,I,t,t,t,t,I,c,I,I,I,I,I,I,I,c,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,H,H,H,H,H,I,I,I,I,H,I,I,I,I,H,H,H,H,H,I,B,
B,u,I,I,I,I,I,u,I,V,u,I,u,V,I,u,D3,I,I,I,D1,u,B,
B,U,I,I,I,I,I,U,I,V,U,I,U,V,I,U,I,I,I,I,I,U,B,
B,U,I,I,I,I,I,U,I,V,I,U,I,V,I,U,I,I,I,I,I,U,B,
B,I,U,U,U,U,U,I,I,I,I,I,I,I,I,I,U,U,U,U,U,I,B,
B,I,I,I,I,I,I,I,B,B,B,B,B,B,B,I,I,I,I,I,I,I,B,
B,Q,Q,Q,Q,Q,I,I,I,I,I,I,I,I,I,I,I,Q,I,I,I,Q,B,
B,I,I,I,I,I,B,I,C,C,C,C,C,C,C,I,B,I,b,b,D1,h,B,
B,I,I,I,I,I,B,C,I,L,d,d,d,L,I,C,B,I,b,b,b,I,B,
B,B,B,B,B,B,_,C,I,I,I,I,I,I,I,C,_,B,B,B,B,B,B,
_,_,_,_,_,_,_,C,I,I,I,I,I,I,I,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,I,I,I,I,I,I,I,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,I,I,I,I,I,I,I,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,I,I,I,I,I,I,I,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,I,I,I,I,I,I,I,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,C,C,C,C,C,C,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,t,t,t,t,t,t,I,I,I,I,I,I,I,I,I,q,I,I,I,I,B,
B,T,L,I,I,I,I,L,T,Q,Q,Q,Q,Q,c,c,c,{name = "doors:door_ice_a", force_place = true},c,c,c,I,B,
B,t,I,I,I,I,I,I,t,Q,Q,Q,Q,Q,G,G,G,Hi,G,G,G,I,B,
B,t,I,I,I,I,I,I,t,Q,Q,Q,Q,Q,c,c,c,c,c,c,c,I,B,
B,B,B,B,B,B,B,B,B,Q,Q,Q,Q,Q,B,B,B,B,B,B,B,B,B,
B,I,I,I,H,I,I,I,U,U,U,H,U,U,U,I,I,I,H,I,I,I,B,
B,I,u,u,I,u,u,V,u,u,u,I,u,u,u,V,u,u,I,u,u,I,B,
B,I,U,U,I,U,U,V,U,U,U,I,U,U,U,V,U,U,I,U,U,I,B,
B,I,U,U,U,U,U,V,U,U,U,U,U,U,U,V,U,U,U,U,U,I,B,
B,I,I,I,I,I,I,I,u,u,u,W,u,u,u,I,I,I,I,I,I,I,B,
B,I,I,I,I,I,I,h,B,U,U,U,U,U,B,I,I,I,I,I,I,I,B,
B,Q,Q,Q,Q,Q,I,I,I,B,B,B,B,B,I,I,I,Q,Q,I,I,Q,B,
B,I,I,I,I,I,B,I,I,I,I,I,I,I,I,I,B,I,I,D1,D1,h,B,
B,I,I,I,I,I,B,C,C,C,C,C,C,C,C,C,B,I,I,{name = "ecology:firefung", force_place = true},b,I,B,
B,B,B,B,B,B,_,C,C,C,I,I,I,C,C,C,_,B,B,B,B,B,B,
_,_,_,_,_,_,_,C,C,C,I,I,I,C,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,C,O,C,C,C,O,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,C,C,O,C,O,C,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,C,C,C,O,C,C,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,C,C,C,C,C,C,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,C,C,C,C,C,C,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,I,t,I,I,I,I,I,Q,Q,Q,Q,Q,I,I,I,q,q,q,q,I,B,
B,I,T,{name = "doors:door_ice_a", param2 = 2, force_place = true},T,T,T,T,Q,h,h,h,h,h,Q,I,c,I,I,I,D2,D1,B,
B,I,t,Hi,t,t,t,t,Q,I,I,I,I,I,Q,I,c,I,I,I,M2,c,B,
B,I,t,t,t,t,t,t,Q,s,s,s,s,s,Q,I,c,I,I,I,I,c,B,
B,B,B,B,B,B,B,B,U,I,I,I,I,I,U,B,B,B,B,B,B,B,B,
B,I,I,I,H,I,I,U,I,I,I,H,I,I,I,U,I,I,H,I,I,I,B,
B,I,I,u,I,u,I,u,I,I,I,I,I,I,I,u,V,u,I,u,V,I,B,
B,I,I,U,I,U,I,U,I,I,I,I,I,I,I,U,V,U,I,U,V,I,B,
B,I,I,I,U,I,I,U,I,I,I,I,I,I,I,U,V,I,U,I,V,I,B,
B,I,I,I,I,I,I,u,I,I,I,I,I,I,I,u,I,I,I,I,I,I,B,
B,B,B,B,B,B,B,B,U,U,U,U,U,U,U,B,B,B,B,B,B,B,B,
B,s,s,s,s,I,I,I,B,U,U,U,U,U,B,I,I,s,s,s,s,I,B,
B,I,I,I,I,B,I,I,I,B,B,B,B,B,I,I,I,B,b,b,b,I,B,
B,I,I,I,I,B,C,D,C,C,C,C,C,C,C,D,C,B,b,{name = "stairs:slab_bedrock", force_place = true},b,I,B,
B,B,B,B,B,_,C,D,I,I,I,I,I,I,I,D,C,_,B,B,B,B,B,
_,_,_,_,_,_,C,D,I,I,I,I,I,I,I,D,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,D,I,I,I,I,I,I,I,D,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,D,I,I,I,I,I,I,I,D,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,D,I,I,I,I,I,I,I,D,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,D,I,I,I,I,I,I,I,D,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,C,C,C,C,C,C,C,C,C,C,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,C,C,C,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,t,t,t,t,I,I,Q,Q,Q,Q,Q,Q,Q,I,I,q,q,q,q,I,B,
B,T,L,s,s,L,T,Q,h,h,h,h,h,h,h,Q,c,I,I,I,D1,c,B,
B,t,I,s,s,I,t,Q,I,I,I,I,I,I,I,Q,c,I,I,I,I,c,B,
B,t,I,I,I,I,t,Q,s,s,s,s,s,s,s,Q,c,I,I,I,I,c,B,
B,B,B,B,B,B,B,Q,I,I,I,I,I,I,I,Q,B,B,B,B,B,B,B,
B,I,I,I,H,I,I,U,I,I,I,I,I,I,I,U,I,I,H,I,I,I,B,
B,I,V,u,I,u,V,u,I,I,I,I,I,I,I,u,I,u,I,u,I,I,B,
B,I,V,U,I,U,V,U,I,I,I,I,I,I,I,U,I,U,I,U,I,I,B,
B,I,V,V,U,V,V,U,I,I,I,I,I,I,I,U,I,V,U,V,I,I,B,
B,I,I,I,I,I,I,u,I,I,I,I,I,I,I,u,I,I,I,I,I,I,B,
B,B,B,B,B,B,B,U,U,U,I,I,I,U,U,U,B,B,B,B,B,B,B,
B,s,s,s,s,I,I,B,U,U,U,U,U,U,U,B,I,s,P1,I,I,I,B,
B,I,I,I,I,B,I,I,B,B,B,B,B,B,B,I,I,B,I,I,I,I,B,
B,I,I,I,I,B,C,C,C,O,O,C,O,O,C,C,C,B,I,I,I,I,B,
B,B,B,B,B,_,C,I,I,I,I,I,I,I,I,I,C,_,B,B,B,B,B,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,C,C,C,I,I,I,C,C,C,C,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,C,C,C,C,C,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,C,_,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,t,t,t,t,I,I,Q,Q,Q,Q,Q,Q,Q,I,I,I,q,q,q,I,B,
B,T,I,I,I,I,T,Q,h,h,h,h,h,h,h,Q,c,G,I,I,I,c,B,
B,t,I,I,I,I,t,Q,I,I,I,I,I,I,I,Q,c,I,I,I,I,c,B,
B,t,I,I,I,I,t,Q,s,s,s,s,s,s,s,Q,c,I,I,I,I,c,B,
B,B,B,B,B,B,B,Q,I,I,I,I,I,I,I,Q,B,B,B,B,B,B,B,
B,I,I,I,H,I,I,U,I,I,I,I,I,I,I,U,I,I,H,I,I,I,B,
B,I,u,u,I,u,u,u,I,I,I,I,I,I,I,u,u,u,I,u,u,I,B,
B,I,U,U,I,U,U,U,I,I,I,I,I,I,I,U,U,U,I,U,U,I,B,
B,I,I,I,U,I,I,U,I,I,I,I,I,I,I,U,I,I,U,I,I,I,B,
B,I,I,I,I,I,I,u,I,I,I,I,I,I,I,u,I,I,I,I,I,I,B,
B,B,B,B,B,B,B,U,U,I,I,I,I,I,U,U,B,B,B,B,B,B,B,
B,s,s,s,s,I,I,B,U,U,U,U,U,U,U,B,I,s,I,b,b,s,B,
B,I,I,I,I,B,I,I,B,B,B,B,B,B,B,I,I,B,I,b,b,b,B,
B,I,I,I,I,B,C,C,S,S,S,O,S,S,S,C,C,B,I,b,b,b,B,
B,B,B,B,B,_,C,I,I,I,I,I,I,I,I,I,C,_,B,B,B,B,B,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,O,I,I,I,I,I,I,I,I,I,O,_,_,_,_,_,_,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,C,C,I,I,I,I,I,C,C,C,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,C,C,I,I,I,C,C,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,C,C,C,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,t,t,t,t,I,I,Q,Q,Q,Q,Q,Q,Q,I,I,I,I,q,q,I,B,
B,T,{name = "mapgen:floor_lamp", force_place = true},I,I,I,T,Q,h,h,h,C0,h,h,h,Q,c,D2,G,I,I,c,B,
B,t,I,I,I,I,t,Q,I,I,I,h,I,I,I,Q,c,G,I,I,I,c,B,
B,t,I,I,I,I,t,Q,s,s,s,s,s,s,s,Q,c,I,I,I,I,c,B,
B,B,B,B,B,B,B,Q,I,I,I,I,I,I,I,Q,B,B,B,B,B,B,B,
B,I,H,H,H,H,H,H,H,I,I,I,I,I,H,H,H,H,H,H,H,I,B,
B,u,L,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,L,u,B,
B,U,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,U,B,
B,I,U,U,U,U,U,U,I,I,I,I,I,I,I,U,U,U,U,U,U,I,B,
B,I,I,I,I,I,I,W,I,I,I,I,I,I,I,W,I,I,I,I,I,I,B,
B,B,B,B,B,B,B,U,U,I,I,{name = "mapgen:glowstone", force_place = true},I,I,U,U,B,B,B,B,B,B,B,
B,s,s,s,s,I,I,B,U,U,U,U,U,U,U,B,I,s,P1,I,I,I,B,
B,I,I,I,I,B,I,I,B,B,B,B,B,B,B,I,I,B,I,I,I,I,B,
B,I,I,I,I,B,C,C,O,S,O,C,O,S,O,C,C,B,I,I,I,I,B,
B,B,B,B,B,_,C,I,I,I,I,{name = "mapgen:stand", force_place = true},I,I,I,I,C,_,B,B,B,B,B,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,O,I,I,I,I,I,I,I,I,I,O,_,_,_,_,_,_,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,C,C,I,I,I,I,I,C,C,C,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,C,C,I,I,I,C,C,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,C,C,l,C,C,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,t,t,t,t,I,I,Q,Q,Q,Q,Q,Q,Q,I,I,I,I,q,q,I,B,
B,T,L,I,I,L,T,Q,h,h,h,h,h,h,h,Q,c,D2,c,I,I,c,B,
B,t,I,I,I,I,t,Q,I,I,I,I,I,I,I,Q,c,I,G,I,I,c,B,
B,t,I,I,I,I,t,Q,s,s,s,s,s,s,s,Q,c,G,I,I,I,c,B,
B,B,B,B,B,B,B,Q,I,I,I,I,I,I,I,Q,B,B,B,B,B,B,B,
B,I,I,I,H,I,I,U,I,I,I,I,I,I,I,U,I,I,H,I,I,I,B,
B,I,u,u,I,u,u,u,I,I,I,I,I,I,I,u,u,u,I,u,u,I,B,
B,I,U,U,I,U,U,U,I,I,I,I,I,I,I,U,U,U,I,U,U,I,B,
B,I,I,I,U,I,I,U,I,I,I,I,I,I,I,U,I,I,U,I,I,I,B,
B,I,I,I,I,I,I,u,I,I,I,I,I,I,I,u,I,I,I,I,I,I,B,
B,B,B,B,B,B,B,U,U,I,I,I,I,I,U,U,B,B,B,B,B,B,B,
B,s,s,s,s,I,I,B,U,U,U,U,U,U,U,B,I,s,s,s,s,I,B,
B,I,I,I,I,B,I,I,B,B,B,B,B,B,B,I,I,B,b,b,b,I,B,
B,I,I,I,I,B,C,C,C,O,S,S,S,O,C,C,C,B,b,b,b,I,B,
B,B,B,B,B,_,C,I,I,I,I,I,I,I,I,I,C,_,B,B,B,B,B,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,O,I,I,I,I,I,I,I,I,I,O,_,_,_,_,_,_,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,C,C,I,I,I,I,I,C,C,C,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,C,C,I,I,I,C,C,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,C,C,C,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,I,I,t,I,I,I,Q,Q,Q,Q,Q,Q,Q,I,I,q,I,q,q,I,B,
B,T,T,T,I,T,c,Q,h,h,h,h,h,h,h,Q,c,I,c,I,I,c,B,
B,t,t,t,I,t,c,Q,I,I,I,I,I,I,I,Q,c,I,c,I,I,c,B,
B,t,t,t,t,t,c,Q,s,s,s,s,s,s,s,Q,c,I,G,I,I,c,B,
B,B,B,B,B,B,B,Q,I,I,I,I,I,I,I,Q,B,B,B,B,B,B,B,
B,I,I,I,H,I,I,U,I,I,I,I,I,I,I,U,I,I,H,I,I,I,B,
B,I,V,u,I,u,V,u,I,I,I,I,I,I,I,u,V,u,I,u,V,I,B,
B,I,V,U,M,U,V,U,I,I,I,I,I,I,I,U,V,U,M,U,V,I,B,
B,I,V,V,U,V,V,U,I,I,I,I,I,I,I,U,V,V,U,V,V,I,B,
B,I,I,I,I,I,I,u,I,I,I,I,I,I,I,u,I,I,I,I,I,I,B,
B,B,B,B,B,B,B,U,U,U,I,I,I,U,U,U,B,B,B,B,B,B,B,
B,s,s,s,s,I,I,B,U,U,U,U,U,U,U,B,I,s,P1,I,I,I,B,
B,I,I,I,I,B,I,I,B,B,B,B,B,B,B,I,I,B,I,I,I,I,B,
B,I,I,I,I,B,C,C,C,C,O,S,O,C,C,C,C,B,I,I,I,I,B,
B,B,B,B,B,_,C,I,I,I,I,I,I,I,I,I,C,_,B,B,B,B,B,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,I,I,I,I,I,I,I,I,I,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,C,C,C,I,I,I,C,C,C,C,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,C,C,C,C,C,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,C,_,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,t,t,t,t,I,I,I,Q,Q,Q,Q,Q,I,I,I,q,I,q,q,I,B,
B,T,L,I,I,L,c,c,Q,h,h,h,h,h,Q,M,c,I,G,I,I,c,B,
B,t,I,I,I,I,c,c,Q,I,I,I,I,I,Q,c,c,I,G,I,I,c,B,
B,t,I,I,I,I,c,c,Q,s,s,s,s,s,Q,c,c,I,G,I,I,c,B,
B,B,B,B,B,B,B,B,U,I,I,I,I,I,U,B,B,B,B,B,B,B,B,
B,I,I,I,H,I,I,U,I,I,I,H,I,I,I,U,I,I,H,I,I,I,B,
B,I,I,u,M,u,I,u,I,I,I,I,I,I,I,u,I,u,M,u,I,I,B,
B,I,I,U,V,U,I,U,I,I,I,I,I,I,I,U,I,U,V,U,I,I,B,
B,I,I,I,U,I,I,U,I,I,I,I,I,I,I,U,I,I,U,I,I,I,B,
B,I,I,I,I,I,I,u,I,I,I,I,I,I,I,u,I,I,I,I,I,I,B,
B,B,B,B,B,B,B,B,U,U,U,U,U,U,U,B,B,B,B,B,B,B,B,
B,s,s,s,s,I,I,I,B,U,U,U,U,U,B,I,I,s,I,I,I,s,B,
B,I,I,I,I,B,I,I,I,B,B,B,B,B,I,I,I,B,I,b,b,b,B,
B,I,I,I,I,B,C,D,C,C,C,C,C,C,C,D,C,B,I,b,b,b,B,
B,B,B,B,B,_,C,D,I,I,I,I,I,I,I,D,C,_,B,B,B,B,B,
_,_,_,_,_,_,C,D,I,I,I,I,I,I,I,D,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,D,I,I,I,I,I,I,I,D,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,D,I,I,I,I,I,I,I,D,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,D,I,I,I,I,I,I,I,D,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,D,I,I,I,I,I,I,I,D,C,_,_,_,_,_,_,
_,_,_,_,_,_,C,C,C,C,C,C,C,C,C,C,C,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,C,C,C,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,t,t,t,t,I,q,I,I,I,I,I,I,I,M,q,q,q,q,q,I,B,
B,T,I,m,I,I,c,C2,c,Q,Q,Q,Q,Q,M,C3,M,I,h,I,I,c,B,
B,t,I,I,I,I,c,C2,c,Q,Q,Q,Q,Q,c,M,I,I,I,I,I,c,B,
B,t,I,I,I,I,c,C2,c,Q,Q,Q,Q,Q,c,P2,I,I,G,I,I,c,B,
B,B,B,B,B,B,B,B,B,Q,Q,Q,Q,Q,B,B,B,B,B,B,B,B,B,
B,I,I,I,H,I,I,I,U,U,U,H,U,U,U,I,I,I,H,I,I,I,B,
B,I,u,u,P2,u,u,V,u,u,u,I,u,u,u,V,u,u,P1,u,u,I,B,
B,I,U,U,M,U,U,V,U,U,U,I,U,U,U,V,U,U,M,U,U,I,B,
B,I,U,U,U,U,U,V,U,U,U,U,U,U,U,V,U,U,U,U,U,I,B,
B,I,I,I,I,I,I,I,u,u,u,W,u,u,u,I,I,I,I,I,I,I,B,
B,I,I,I,I,I,I,I,B,U,U,U,U,U,B,I,I,I,I,I,I,I,B,
B,Q,Q,Q,Q,Q,h,I,I,B,B,B,B,B,I,I,I,Q,Q,Q,Q,Q,B,
B,I,I,I,I,I,B,I,I,I,I,I,I,I,I,I,B,I,I,I,I,I,B,
B,I,I,I,I,I,B,C,C,C,C,C,C,C,C,C,B,I,I,I,A,I,B,
B,B,B,B,B,B,_,C,C,C,C,C,C,C,C,C,_,B,B,B,B,B,B,
_,_,_,_,_,_,_,C,C,C,C,C,C,C,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,C,O,C,C,C,O,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,C,C,O,C,O,C,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,C,C,C,O,C,C,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,C,C,C,C,C,C,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,C,C,C,C,C,C,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,t,t,t,t,I,q,I,I,I,I,I,I,I,q,q,q,q,q,q,I,B,
B,T,m,M0,m,I,c,C2,c,c,c,c,c,c,c,M,I,I,G,I,I,c,B,
B,t,I,m,I,I,c,C2,c,c,c,c,c,c,c,P2,I,I,G,I,I,c,B,
B,t,I,I,I,I,c,C2,c,c,c,c,c,c,c,I,I,I,G,I,I,c,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,H,H,H,H,H,I,I,I,I,H,I,I,I,I,H,H,H,H,H,I,B,
B,u,I,h,h,h,h,u,I,V,u,I,u,V,I,u,I,m,I,m,I,u,B,
B,U,I,I,I,I,I,U,I,V,U,I,U,V,I,U,I,I,I,I,I,U,B,
B,U,I,I,I,I,I,U,I,V,I,U,I,V,I,U,I,I,I,I,I,U,B,
B,I,U,U,U,U,U,I,I,I,I,I,I,I,I,I,U,U,U,U,U,I,B,
B,I,I,I,I,I,I,I,B,B,B,B,B,B,B,I,I,I,I,I,I,I,B,
B,Q,Q,Q,Q,Q,Q,h,I,I,I,I,I,I,I,I,Q,Q,Q,Q,Q,Q,B,
B,I,I,I,I,m,I,B,B,B,B,B,B,B,B,B,I,I,S,S,S,I,B,
B,I,I,I,I,I,I,B,B,B,B,B,B,B,B,B,I,A,S,S,S,I,B,
B,B,B,B,B,B,B,_,_,_,_,_,_,_,_,_,B,B,B,B,B,B,B,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,t,t,t,t,I,q,q,q,q,q,q,q,I,q,q,q,q,q,q,I,B,
B,T,I,m,I,I,c,I,CH,CH,c,s,s,s,c,P2,I,c,h,I,I,c,B,
B,t,I,I,I,I,c,I,CH,I,c,I,I,I,c,I,I,c,I,I,I,c,B,
B,t,I,I,I,I,c,c,M3,I,c,I,I,I,c,I,I,c,I,I,I,c,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,H,H,H,H,H,I,I,I,I,H,I,I,I,I,H,H,H,H,H,I,B,
B,u,I,h,h,h,h,u,u,u,u,I,u,u,u,u,m,I,m,I,m,u,B,
B,U,I,I,I,I,I,U,U,U,U,I,U,U,U,U,I,I,I,I,I,U,B,
B,U,I,I,I,I,I,U,I,V,I,U,I,V,I,U,I,I,I,I,I,U,B,
B,I,U,U,U,U,U,I,I,I,I,I,I,I,I,I,U,U,U,U,U,I,B,
B,I,I,I,I,I,I,I,B,B,B,B,B,B,B,I,I,I,I,I,I,I,B,
B,Q,Q,Q,Q,Q,Q,Q,P1,P1,P1,P1,P1,{name = "default:obsidian", force_place = true},{name = "default:obsidian", force_place = true},Q,Q,Q,Q,Q,Q,Q,B,
B,I,I,I,m,I,m,I,I,I,I,I,I,I,{name = "stairs:slab_obsidian_glass", force_place = true},I,I,S,D1,D1,I,I,B,
B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,A,S,{name = "default:coco_3", force_place = true},S,I,A,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,t,t,t,t,I,q,q,q,q,q,q,q,q,q,q,q,q,q,q,I,B,
B,T,I,m,I,I,c,C0,c,CH,s,s,c,CH,s,c,c,h,I,I,h,c,B,
B,t,I,I,I,I,c,C0,c,I,I,I,c,I,I,c,c,I,I,I,I,c,B,
B,t,I,I,I,I,c,C0,c,I,I,I,c,I,I,c,c,I,I,I,I,c,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,H,H,H,H,H,H,H,H,H,H,H,H,H,H,H,H,H,H,H,I,B,
B,u,C3,h,h,h,h,h,h,I,I,I,I,I,I,I,m,I,I,m,I,u,B,
B,U,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,U,B,
B,U,I,I,I,I,I,U,U,U,U,U,U,U,U,U,I,I,I,I,I,U,B,
B,I,U,U,U,U,U,I,I,I,I,I,I,I,I,I,U,U,U,U,U,I,B,
B,I,I,I,V,I,I,I,B,B,B,B,B,B,B,I,I,I,V,I,I,I,B,
B,Q,Q,Q,Q,Q,Q,Q,I,I,I,I,I,S,S,Q,Q,Q,Q,Q,Q,Q,B,
B,I,I,m,I,m,I,m,M,M,M,M,M,{name = "default:obsidian", force_place = true},{name = "default:obsidian", force_place = true},S,S,I,I,S,I,S,B,
B,I,I,I,I,I,I,I,I,I,I,I,I,{name = "default:obsidian", force_place = true},{name = "default:obsidian", force_place = true},S,S,I,I,S,I,S,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,t,C0,t,t,q,I,I,I,I,I,I,I,q,I,q,q,q,q,q,I,B,
B,T,m,m,m,I,h,c,c,c,c,c,c,G,{name = "doors:door_wood_a", force_place = true},G,I,I,I,h,h,c,B,
B,t,I,m,I,I,I,c,c,c,c,c,c,G,Hi,G,I,I,I,I,I,c,B,
B,t,I,I,I,I,I,c,c,c,c,c,c,G,G,G,I,I,I,I,I,c,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,H,H,H,H,H,I,I,I,I,H,I,I,I,I,H,H,H,H,H,I,B,
B,u,I,h,h,h,h,u,u,u,u,I,u,u,u,u,m,I,m,h,m,u,B,
B,U,I,I,I,I,I,U,U,U,U,I,U,U,U,U,I,I,I,I,I,U,B,
B,U,I,I,I,I,I,U,I,V,I,U,I,V,I,U,I,I,I,I,I,U,B,
B,I,U,U,U,U,U,I,I,I,I,I,I,I,I,I,U,U,U,U,U,I,B,
B,I,I,I,I,I,I,I,B,B,B,B,B,B,B,I,I,I,I,I,I,I,B,
B,Q,Q,Q,Q,Q,Q,Q,I,I,I,I,I,I,I,Q,Q,Q,Q,Q,Q,Q,B,
B,I,m,L,m,I,m,I,I,I,I,I,I,I,I,D0,I,I,I,{name = "mapgen:glowore", force_place = true},I,I,B,
B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,S,I,A,I,S,A,I,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,t,t,t,t,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,I,B,
B,T,L,m,I,I,I,I,I,I,I,I,I,I,I,I,I,I,h,h,h,c,B,
B,t,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,c,B,
B,t,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,c,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,H,H,H,H,H,I,I,I,I,H,I,I,I,I,H,H,H,H,H,I,B,
B,u,I,h,h,h,h,u,I,V,u,L,u,V,I,u,I,m,C0,m,I,u,B,
B,U,I,I,I,I,I,U,I,V,U,I,U,V,I,U,I,I,m,m,I,U,B,
B,U,I,I,I,I,I,U,I,V,I,U,I,V,I,U,I,I,I,I,I,U,B,
B,I,U,U,U,U,U,I,I,I,I,I,I,I,I,I,U,U,U,U,U,I,B,
B,I,I,I,I,I,I,I,B,B,B,B,B,B,B,I,I,I,I,I,I,I,B,
B,Q,Q,Q,Q,Q,Q,Q,I,I,I,I,I,S,I,Q,Q,Q,Q,Q,Q,Q,B,
B,m,C3,m,I,m,I,m,I,I,I,I,I,S,I,D0,I,S,I,S,S,I,B,
B,I,m,I,I,I,I,I,I,I,I,I,I,S,A,S,I,S,I,S,S,I,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,
B,T,T,T,T,T,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,I,B,
B,t,t,t,t,t,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,I,B,
B,t,t,t,t,t,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,I,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,
B,I,u,u,u,u,u,I,I,I,I,u,I,I,I,I,u,u,u,u,u,I,B,
B,I,U,U,U,U,U,I,I,I,I,U,I,I,I,I,U,U,U,U,U,I,B,
B,I,U,U,U,U,U,I,I,I,I,I,I,I,I,I,U,U,U,U,U,I,B,
B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,
B,I,I,I,I,I,I,I,B,B,B,B,B,B,B,I,I,I,I,I,I,I,B,
B,Q,Q,Q,Q,Q,Q,Q,I,{name = "mapgen:crystal_2", param2 = 3, force_place = true},I,{name = "mapgen:crystal_3", param2 = 3, force_place = true},I,S,{name = "mapgen:adamantium_ore", force_place = true},Q,Q,Q,Q,Q,Q,Q,B,
B,D0,m,I,m,I,m,I,I,I,I,I,I,S,I,I,I,S,I,I,I,I,B,
B,m,I,I,I,I,I,I,I,I,I,I,I,S,I,I,A,S,A,I,I,A,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_}}

local f = {name = "mapgen:darkgreen_tile", force_place = true}
local r = {name = "mapgen:railblock", force_place = true}
s = {name = "mapgen:stained_glass", force_place = true}
local g = {name = "mapgen:geyser", force_place = true}
b = {name = "mapgen:ganon_sphere", force_place = true}
local P = {name = "mapgen:dark_sandstone_pillar_base", force_place = true}
local p = {name = "mapgen:dark_sandstone_pillar", force_place = true}
t = {name = "mapgen:dark_sandstone_pillar_top", force_place = true}
local w = {name = "mapgen:dark_sandstone_decorated", force_place = true}

ganon_dungeon = {size = {x = 23, y = 19, z = 23}, data = {
_,_,_,_,_,_,_,_,f,f,f,f,f,f,f,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,r,r,r,r,r,r,r,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,r,r,r,r,r,r,r,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,r,r,r,r,r,r,r,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,r,r,r,s,r,r,r,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,r,r,s,r,s,r,r,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,r,r,r,s,r,r,r,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,r,r,r,r,r,r,r,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,s,s,s,s,s,s,s,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,s,s,s,s,s,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,s,s,s,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,_,_,_,_,_,f,f,f,f,r,f,r,f,f,f,f,_,_,_,_,_,_,
_,_,_,_,_,_,r,r,s,I,I,I,I,I,s,r,r,_,_,_,_,_,_,
_,_,_,_,_,_,r,r,s,I,I,I,I,I,s,r,r,_,_,_,_,_,_,
_,_,_,_,_,_,r,r,s,I,I,I,I,I,s,r,r,_,_,_,_,_,_,
_,_,_,_,_,_,r,r,s,I,I,I,I,I,s,r,r,_,_,_,_,_,_,
_,_,_,_,_,_,r,r,s,I,I,I,I,I,s,r,r,_,_,_,_,_,_,
_,_,_,_,_,_,r,r,s,I,I,I,I,I,s,r,r,_,_,_,_,_,_,
_,_,_,_,_,_,r,r,s,I,I,I,I,I,s,r,r,_,_,_,_,_,_,
_,_,_,_,_,_,s,s,s,I,I,I,I,I,s,s,s,_,_,_,_,_,_,
_,_,_,_,_,_,s,s,s,I,I,I,I,I,s,s,s,_,_,_,_,_,_,
_,_,_,_,_,_,_,s,s,s,s,I,s,s,s,s,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,s,s,s,s,s,s,s,s,s,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,s,s,s,s,s,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,_,_,_,f,f,f,r,r,f,f,r,f,f,r,r,f,f,f,_,_,_,_,
_,_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,_,
_,_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,_,
_,_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,_,
_,_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,_,
_,_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,_,
_,_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,_,
_,_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,_,
_,_,_,_,s,s,I,I,I,I,I,I,I,I,I,I,I,s,s,_,_,_,_,
_,_,_,_,_,s,s,I,I,I,I,I,I,I,I,I,s,s,_,_,_,_,_,
_,_,_,_,_,s,s,I,I,I,I,I,I,I,I,I,s,s,_,_,_,_,_,
_,_,_,_,_,_,s,s,I,I,I,I,I,I,I,s,s,_,_,_,_,_,_,
_,_,_,_,_,_,s,s,s,s,I,I,I,s,s,s,s,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,s,s,s,s,s,s,s,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,s,s,s,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,_,_,f,f,r,f,f,f,f,r,f,r,f,f,f,f,r,f,f,_,_,_,
_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,
_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,
_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,
_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,
_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,
_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,
_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,
_,_,_,s,f,I,I,I,I,I,I,I,I,I,I,I,I,I,f,s,_,_,_,
_,_,_,s,f,I,I,I,I,I,I,I,I,I,I,I,I,I,f,s,_,_,_,
_,_,_,_,f,I,I,I,I,I,I,I,I,I,I,I,I,I,f,_,_,_,_,
_,_,_,_,s,s,I,I,I,I,I,I,I,I,I,I,I,s,s,_,_,_,_,
_,_,_,_,_,s,s,I,I,I,I,I,I,I,I,I,s,s,_,_,_,_,_,
_,_,_,_,_,_,s,s,I,I,I,I,I,I,I,s,s,_,_,_,_,_,_,
_,_,_,_,_,_,_,s,s,s,s,s,s,s,s,s,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,s,s,s,s,s,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,_,f,f,f,f,f,f,f,f,f,r,f,f,f,f,f,f,f,f,f,_,_,
_,_,r,r,g,I,I,I,I,I,I,I,I,I,I,I,I,I,g,r,r,_,_,
_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,
_,_,r,r,b,I,I,I,I,I,I,I,I,I,I,I,I,I,b,r,r,_,_,
_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,
_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,
_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,
_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,
_,_,s,f,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,f,s,_,_,
_,_,_,f,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,f,_,_,_,
_,_,_,f,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,f,_,_,_,
_,_,_,s,f,I,I,I,I,I,I,I,I,I,I,I,I,I,f,s,_,_,_,
_,_,_,_,s,f,I,I,I,I,I,I,I,I,I,I,I,f,s,_,_,_,_,
_,_,_,_,_,f,s,I,I,I,I,I,I,I,I,I,s,f,_,_,_,_,_,
_,_,_,_,_,_,s,s,I,I,I,I,I,I,I,s,s,_,_,_,_,_,_,
_,_,_,_,_,_,_,s,s,s,s,s,s,s,s,s,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,s,s,s,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,_,f,r,f,r,r,f,f,f,f,f,f,f,f,f,r,r,f,r,f,_,_,
_,_,r,I,I,I,I,I,I,h,h,h,h,h,I,I,I,I,I,I,r,_,_,
_,_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,_,
_,_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,_,
_,_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,_,
_,_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,_,
_,_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,_,
_,_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,_,
_,_,_,s,f,I,I,I,I,I,I,I,I,I,I,I,I,I,f,s,_,_,_,
_,_,_,_,f,I,I,I,I,I,I,I,I,I,I,I,I,I,f,_,_,_,_,
_,_,_,_,_,f,f,f,f,f,f,f,f,f,f,f,f,f,_,_,_,_,_,
_,_,_,_,_,f,s,s,I,I,I,I,I,I,I,s,s,f,_,_,_,_,_,
_,_,_,_,_,_,_,_,s,s,s,s,s,s,s,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,f,f,f,f,r,f,r,f,f,f,f,f,f,f,r,f,r,f,f,f,f,_,
_,r,I,I,I,I,P,h,h,h,h,h,h,h,h,h,P,I,I,I,I,r,_,
_,r,I,I,I,I,p,I,I,I,I,I,I,I,I,I,p,I,I,I,I,r,_,
_,r,I,I,I,I,p,I,I,I,I,I,I,I,I,I,p,I,I,I,I,r,_,
_,r,I,I,I,I,p,I,I,I,I,I,I,I,I,I,p,I,I,I,I,r,_,
_,r,I,I,I,I,p,I,I,I,I,I,I,I,I,I,p,I,I,I,I,r,_,
_,r,I,I,I,I,t,I,I,I,I,I,I,I,I,I,t,I,I,I,I,r,_,
_,r,I,I,I,I,w,w,w,w,I,I,I,w,w,w,w,I,I,I,I,r,_,
_,s,I,I,I,I,W,I,I,I,I,I,I,I,I,I,W,I,I,I,I,s,_,
_,s,s,I,I,I,b,I,I,I,I,I,I,I,I,I,b,I,I,I,s,s,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,s,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,s,_,_,
_,_,_,s,s,I,I,I,I,I,I,I,I,I,I,I,I,I,s,s,_,_,_,
_,_,_,_,s,f,I,I,I,I,I,I,I,I,I,I,I,f,s,_,_,_,_,
_,_,_,_,_,s,I,I,I,I,I,I,I,I,I,I,I,s,_,_,_,_,_,
_,_,_,_,_,_,f,s,s,s,I,I,I,s,s,s,f,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,s,s,s,s,s,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,f,r,f,f,f,r,r,f,f,f,r,f,f,f,r,r,f,f,f,r,f,_,
_,r,I,I,I,I,h,h,h,I,I,I,I,I,h,h,h,I,I,I,I,r,_,
_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,
_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,
_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,
_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,
_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,
_,r,I,I,I,I,w,I,I,I,I,I,I,I,I,I,w,I,I,I,I,r,_,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,s,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,s,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,_,
_,_,_,s,s,f,I,I,I,I,I,I,I,I,I,I,I,f,s,s,_,_,_,
_,_,_,_,s,s,I,I,I,I,I,I,I,I,I,I,I,s,s,_,_,_,_,
_,_,_,_,_,_,s,I,I,I,I,I,I,I,I,I,s,_,_,_,_,_,_,
_,_,_,_,_,_,_,f,s,s,s,s,s,s,s,f,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

f,f,r,f,f,f,f,f,f,f,r,f,r,f,f,f,f,f,f,f,r,f,f,
r,s,I,I,I,I,h,h,I,I,I,I,I,I,I,h,h,I,I,I,I,s,r,
r,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,r,
r,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,r,
r,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,r,
r,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,r,
r,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,r,
r,s,I,I,I,I,w,I,I,I,I,I,I,I,I,I,w,I,I,I,I,s,r,
s,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,s,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,_,s,I,f,I,I,I,I,I,I,I,I,I,I,I,f,I,s,_,_,_,
_,_,_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,_,_,
_,_,_,_,_,s,s,I,I,I,I,I,I,I,I,I,s,s,_,_,_,_,_,
_,_,_,_,_,_,_,s,f,s,s,I,s,s,f,s,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,s,s,s,_,_,_,_,_,_,_,_,_,_,

f,f,f,f,f,f,f,f,f,f,f,r,f,f,f,f,f,f,f,f,f,f,f,
r,I,I,I,I,h,h,I,I,I,I,I,I,I,I,I,h,h,I,I,I,I,r,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
r,I,I,I,I,I,w,I,I,I,I,I,I,I,I,I,w,I,I,I,I,I,r,
s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,
s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,s,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,s,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,_,s,I,f,I,I,I,I,I,I,I,I,I,I,I,f,I,s,_,_,_,
_,_,_,s,s,I,I,I,I,I,I,I,I,I,I,I,I,I,s,s,_,_,_,
_,_,_,_,_,s,s,I,I,I,I,I,I,I,I,I,s,s,_,_,_,_,_,
_,_,_,_,_,_,s,s,s,I,I,I,I,I,s,s,s,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,f,f,s,f,f,_,_,_,_,_,_,_,_,_,

f,r,f,r,f,f,f,f,r,f,f,f,f,f,r,f,f,f,f,r,f,r,f,
r,I,I,I,I,h,h,I,I,I,I,I,I,I,I,I,h,h,I,I,I,I,r,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,
s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,
s,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,s,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,s,s,I,f,I,I,I,I,I,I,I,I,I,I,I,f,I,s,s,_,_,
_,_,_,s,s,I,I,I,I,I,I,I,I,I,I,I,I,I,s,s,_,_,_,
_,_,_,_,s,s,I,I,I,I,I,I,I,I,I,I,I,s,s,_,_,_,_,
_,_,_,_,_,_,s,s,s,I,I,I,I,I,s,s,s,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,s,f,I,s,I,f,s,_,_,_,_,_,_,_,_,

f,f,r,f,r,f,f,r,f,r,f,s,f,r,f,r,f,f,r,f,r,f,f,
r,I,I,I,I,h,h,I,I,I,I,I,I,I,I,I,h,h,I,I,I,I,r,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,
s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,
s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,s,s,I,f,I,I,I,I,I,I,I,I,I,I,I,f,I,s,s,_,_,
_,_,_,s,s,I,I,I,I,I,I,I,I,I,I,I,I,I,s,s,_,_,_,
_,_,_,_,s,s,I,I,I,I,I,I,I,I,I,I,I,s,s,_,_,_,_,
_,_,_,_,_,_,s,s,I,I,I,I,I,I,I,s,s,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,s,s,s,f,s,s,s,_,_,_,_,_,_,_,_,

f,r,f,r,f,f,f,f,r,f,f,f,f,f,r,f,f,f,f,r,f,r,f,
r,I,I,I,I,h,h,I,I,I,I,I,I,I,I,I,h,h,I,I,I,I,r,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,
s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,
s,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,s,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,s,s,I,f,I,I,I,I,I,I,I,I,I,I,I,f,I,s,s,_,_,
_,_,_,s,s,I,I,I,I,I,I,I,I,I,I,I,I,I,s,s,_,_,_,
_,_,_,_,s,s,I,I,I,I,I,I,I,I,I,I,I,s,s,_,_,_,_,
_,_,_,_,_,_,s,s,s,I,I,I,I,I,s,s,s,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,s,f,I,s,I,f,s,_,_,_,_,_,_,_,_,

f,f,f,f,f,f,f,f,f,f,f,r,f,f,f,f,f,f,f,f,f,f,f,
r,I,I,I,I,h,h,I,I,I,I,I,I,I,I,I,h,h,I,I,I,I,r,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,
r,I,I,I,I,I,w,I,I,I,I,I,I,I,I,I,w,I,I,I,I,I,r,
s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,
s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,s,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,s,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,_,s,I,f,I,I,I,I,I,I,I,I,I,I,I,f,I,s,_,_,_,
_,_,_,s,s,I,I,I,I,I,I,I,I,I,I,I,I,I,s,s,_,_,_,
_,_,_,_,_,s,s,I,I,I,I,I,I,I,I,I,s,s,_,_,_,_,_,
_,_,_,_,_,_,s,s,s,I,I,I,I,I,s,s,s,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,f,f,s,f,f,_,_,_,_,_,_,_,_,_,

f,f,r,f,f,f,f,f,f,f,r,f,r,f,f,f,f,f,f,f,r,f,f,
r,s,I,I,I,I,h,h,I,I,I,I,I,I,I,h,h,I,I,I,I,s,r,
r,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,r,
r,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,r,
r,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,r,
r,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,r,
r,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,r,
r,s,I,I,I,I,w,I,I,I,I,I,I,I,I,I,w,I,I,I,I,s,r,
s,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,s,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,_,s,I,f,I,I,I,I,I,I,I,I,I,I,I,f,I,s,_,_,_,
_,_,_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,_,_,
_,_,_,_,_,s,s,I,I,I,I,I,I,I,I,I,s,s,_,_,_,_,_,
_,_,_,_,_,_,_,s,f,s,s,I,s,s,f,s,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,s,s,s,_,_,_,_,_,_,_,_,_,_,

_,f,r,f,f,f,r,r,f,f,f,r,f,f,f,r,r,f,f,f,r,f,_,
_,r,I,I,I,I,h,h,h,I,I,I,I,I,h,h,h,I,I,I,I,r,_,
_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,
_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,
_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,
_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,
_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,
_,r,I,I,I,I,w,I,I,I,I,I,I,I,I,I,w,I,I,I,I,r,_,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,
_,s,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,s,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,_,
_,_,_,s,s,f,I,I,I,I,I,I,I,I,I,I,I,f,s,s,_,_,_,
_,_,_,_,s,s,I,I,I,I,I,I,I,I,I,I,I,s,s,_,_,_,_,
_,_,_,_,_,_,s,I,I,I,I,I,I,I,I,I,s,_,_,_,_,_,_,
_,_,_,_,_,_,_,f,s,s,s,s,s,s,s,f,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,f,f,f,f,r,f,r,f,f,f,f,f,f,f,r,f,r,f,f,f,f,_,
_,r,I,I,I,I,P,h,h,h,h,h,h,h,h,h,P,I,I,I,I,r,_,
_,r,I,I,I,I,p,I,I,I,I,I,I,I,I,I,p,I,I,I,I,r,_,
_,r,I,I,I,I,p,I,I,I,I,I,I,I,I,I,p,I,I,I,I,r,_,
_,r,I,I,I,I,p,I,I,I,I,I,I,I,I,I,p,I,I,I,I,r,_,
_,r,I,I,I,I,p,I,I,I,I,I,I,I,I,I,p,I,I,I,I,r,_,
_,r,I,I,I,I,t,I,I,I,I,I,I,I,I,I,t,I,I,I,I,r,_,
_,r,I,I,I,I,w,w,w,w,I,I,I,w,w,w,w,I,I,I,I,r,_,
_,s,I,I,I,I,W,I,I,I,I,I,I,I,I,I,W,I,I,I,I,s,_,
_,s,s,I,I,I,b,I,I,I,I,I,I,I,I,I,b,I,I,I,s,s,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,s,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,s,_,_,
_,_,_,s,s,I,I,I,I,I,I,I,I,I,I,I,I,I,s,s,_,_,_,
_,_,_,_,s,f,I,I,I,I,I,I,I,I,I,I,I,f,s,_,_,_,_,
_,_,_,_,_,s,I,I,I,I,I,I,I,I,I,I,I,s,_,_,_,_,_,
_,_,_,_,_,_,f,s,s,s,I,I,I,s,s,s,f,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,s,s,s,s,s,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,_,f,r,f,r,r,f,f,f,f,f,f,f,f,f,r,r,f,r,f,_,_,
_,_,r,I,I,I,I,I,I,h,h,h,h,h,I,I,I,I,I,I,r,_,_,
_,_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,_,
_,_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,_,
_,_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,_,
_,_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,_,
_,_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,_,
_,_,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,_,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,
_,_,_,s,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,s,_,_,_,
_,_,_,s,f,I,I,I,I,I,I,I,I,I,I,I,I,I,f,s,_,_,_,
_,_,_,_,f,I,I,I,I,I,I,I,I,I,I,I,I,I,f,_,_,_,_,
_,_,_,_,_,f,f,f,f,f,f,f,f,f,f,f,f,f,_,_,_,_,_,
_,_,_,_,_,f,s,s,I,I,I,I,I,I,I,s,s,f,_,_,_,_,_,
_,_,_,_,_,_,_,_,s,s,s,s,s,s,s,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,_,f,f,f,f,f,f,f,f,f,r,f,f,f,f,f,f,f,f,f,_,_,
_,_,r,r,g,I,I,I,I,I,I,I,I,I,I,I,I,I,g,r,r,_,_,
_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,
_,_,r,r,b,I,I,I,I,I,I,I,I,I,I,I,I,I,b,r,r,_,_,
_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,
_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,
_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,
_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,
_,_,s,f,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,f,s,_,_,
_,_,_,f,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,f,_,_,_,
_,_,_,f,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,f,_,_,_,
_,_,_,s,f,I,I,I,I,I,I,I,I,I,I,I,I,I,f,s,_,_,_,
_,_,_,_,s,f,I,I,I,I,I,I,I,I,I,I,I,f,s,_,_,_,_,
_,_,_,_,_,f,s,I,I,I,I,I,I,I,I,I,s,f,_,_,_,_,_,
_,_,_,_,_,_,s,s,I,I,I,I,I,I,I,s,s,_,_,_,_,_,_,
_,_,_,_,_,_,_,s,s,s,s,s,s,s,s,s,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,s,s,s,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,_,_,f,f,r,f,f,f,f,r,f,r,f,f,f,f,r,f,f,_,_,_,
_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,
_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,
_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,
_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,
_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,
_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,
_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,
_,_,_,s,f,I,I,I,I,I,I,I,I,I,I,I,I,I,f,s,_,_,_,
_,_,_,s,f,I,I,I,I,I,I,I,I,I,I,I,I,I,f,s,_,_,_,
_,_,_,_,f,I,I,I,I,I,I,I,I,I,I,I,I,I,f,_,_,_,_,
_,_,_,_,s,s,I,I,I,I,I,I,I,I,I,I,I,s,s,_,_,_,_,
_,_,_,_,_,s,s,I,I,I,I,I,I,I,I,I,s,s,_,_,_,_,_,
_,_,_,_,_,_,s,s,I,I,I,I,I,I,I,s,s,_,_,_,_,_,_,
_,_,_,_,_,_,_,s,s,s,s,s,s,s,s,s,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,s,s,s,s,s,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,_,_,_,f,f,f,r,r,f,f,r,f,f,r,r,f,f,f,_,_,_,_,
_,_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,_,
_,_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,_,
_,_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,_,
_,_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,_,
_,_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,_,
_,_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,_,
_,_,_,_,r,r,I,I,I,I,I,I,I,I,I,I,I,r,r,_,_,_,_,
_,_,_,_,s,s,I,I,I,I,I,I,I,I,I,I,I,s,s,_,_,_,_,
_,_,_,_,_,s,s,I,I,I,I,I,I,I,I,I,s,s,_,_,_,_,_,
_,_,_,_,_,s,s,I,I,I,I,I,I,I,I,I,s,s,_,_,_,_,_,
_,_,_,_,_,_,s,s,I,I,I,I,I,I,I,s,s,_,_,_,_,_,_,
_,_,_,_,_,_,s,s,s,s,I,I,I,s,s,s,s,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,s,s,s,s,s,s,s,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,s,s,s,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,_,_,_,_,_,f,f,f,f,r,f,r,f,f,f,f,_,_,_,_,_,_,
_,_,_,_,_,_,r,r,s,I,I,I,I,I,s,r,r,_,_,_,_,_,_,
_,_,_,_,_,_,r,r,s,I,I,I,I,I,s,r,r,_,_,_,_,_,_,
_,_,_,_,_,_,r,r,s,I,I,I,I,I,s,r,r,_,_,_,_,_,_,
_,_,_,_,_,_,r,r,s,I,I,I,I,I,s,r,r,_,_,_,_,_,_,
_,_,_,_,_,_,r,r,s,I,I,I,I,I,s,r,r,_,_,_,_,_,_,
_,_,_,_,_,_,r,r,s,I,I,I,I,I,s,r,r,_,_,_,_,_,_,
_,_,_,_,_,_,r,r,s,I,I,I,I,I,s,r,r,_,_,_,_,_,_,
_,_,_,_,_,_,s,s,s,I,I,I,I,I,s,s,s,_,_,_,_,_,_,
_,_,_,_,_,_,s,s,s,I,I,I,I,I,s,s,s,_,_,_,_,_,_,
_,_,_,_,_,_,_,s,s,s,s,I,s,s,s,s,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,s,s,s,s,s,s,s,s,s,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,s,s,s,s,s,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,_,_,_,_,_,_,_,f,f,f,f,f,f,f,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,r,r,r,r,r,r,r,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,r,r,r,r,r,r,r,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,r,r,r,r,r,r,r,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,r,r,r,s,r,r,r,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,r,r,s,r,s,r,r,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,r,r,r,s,r,r,r,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,r,r,r,r,r,r,r,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,s,s,s,s,s,s,s,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,s,s,s,s,s,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,s,s,s,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_}}

c = {name = "mapgen:dungeon_brick2", force_place = true}
B = {name = "mapgen:dungeon_barrier2", force_place = true}
local Y = {name = "mapgen:crystal_1", force_place = true}
f = {name = "mapgen:fire", force_place = true}
local y = {name = "mapgen:crystal_2", force_place = true}
T = {name = "mapgen:dungeon_tile2", force_place = true}
M = {name = "flowers:mushroom_brown", force_place = true}
d = {name = "stairs:slab_dungeon_brick2", force_place = true}
l = {name = "mapgen:glowstone", force_place = true}
S = {name = "mapgen:skull", param2 = 2, force_place = true}
local Fy = {name = "fabric:block_yellow", force_place = true}
local Fr = {name = "fabric:block_red", force_place = true}
local Fw = {name = "fabric:block_white", force_place = true}

zols_lair = {size = {x = 31, y = 7, z = 31}, data = {
c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,
c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,I,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,
c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,I,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,
c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,I,I,I,I,Y,I,B,I,I,B,I,Y,c,c,{name = "doors:door_wood_a", force_place = true},c,c,f,f,f,f,f,f,f,f,f,f,f,f,c,
c,I,I,I,I,I,I,B,I,I,B,I,I,c,c,Hi,c,c,I,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,I,I,I,I,I,I,I,c,c,c,c,c,I,I,I,I,I,I,I,I,I,I,I,I,c,
_,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,I,L,I,I,I,I,B,I,I,B,I,I,c,y,I,y,c,f,I,I,I,h,h,h,h,h,h,h,f,c,
c,I,I,I,I,I,I,B,I,I,B,I,I,c,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,I,B,I,I,B,I,I,c,I,I,I,c,I,I,I,I,I,I,I,I,I,F,I,I,c,
_,c,I,I,I,I,I,I,I,I,I,I,I,c,I,I,I,c,c,I,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,I,I,I,I,I,I,D3,I,I,I,I,I,c,I,I,I,c,f,I,I,I,h,h,h,h,h,h,h,f,c,
c,I,I,I,I,I,I,B,I,I,I,I,I,c,I,I,I,c,I,I,I,I,I,I,I,I,F,F,I,I,c,
c,I,I,I,I,I,I,B,I,I,I,I,I,c,I,I,I,c,I,I,I,I,I,I,I,I,F,C1,F,I,c,
_,c,I,I,I,I,I,I,I,I,I,I,I,c,I,I,I,c,c,I,I,I,I,I,I,I,I,F,I,c,_,
_,_,c,I,I,I,I,I,I,I,I,I,I,c,I,I,I,c,I,c,T,T,T,T,T,T,T,T,c,_,_,
_,_,_,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,I,I,I,I,I,I,B,I,I,B,I,I,c,I,I,I,c,f,I,I,I,h,h,h,h,h,h,h,f,c,
c,I,I,I,I,I,I,D1,I,I,B,I,I,c,I,I,I,c,I,I,I,I,I,I,I,I,F,F,I,I,c,
c,I,I,I,I,I,I,B,I,I,B,I,I,c,I,I,I,c,I,I,I,I,I,I,I,I,F,F,I,I,c,
_,c,I,I,I,I,I,I,I,I,B,I,I,c,I,I,I,c,c,I,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,I,I,I,I,I,I,B,B,I,I,c,I,I,I,c,I,c,T,T,T,T,T,T,T,T,c,_,_,
_,_,_,c,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,I,I,I,I,B,I,D3,I,I,B,I,I,c,I,I,I,h,f,I,I,I,h,h,h,h,h,h,h,f,c,
c,I,I,I,I,I,I,B,I,I,B,I,I,c,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,I,B,B,B,B,I,I,c,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,I,c,
_,c,I,I,I,I,I,I,I,I,I,I,I,c,I,I,I,c,c,I,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,I,I,B,I,I,I,I,I,I,I,c,I,I,I,c,I,c,T,T,T,T,T,T,T,T,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,Y,I,I,I,B,I,B,I,I,B,I,I,c,I,I,I,h,f,I,I,I,h,h,h,h,h,h,h,f,c,
c,I,I,I,I,I,I,D1,I,I,B,I,I,c,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,I,B,I,I,B,I,I,c,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,I,c,
_,c,I,I,I,I,I,I,I,I,I,I,I,c,I,I,I,c,c,I,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,I,I,B,I,I,B,I,I,I,I,c,I,I,I,c,I,c,T,T,T,T,T,T,T,T,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,I,I,I,I,B,I,D3,I,I,B,I,I,c,I,I,I,c,f,I,I,I,h,h,h,h,h,h,h,f,c,
c,I,I,I,I,I,I,B,I,I,B,I,I,c,I,I,I,c,I,I,I,I,I,I,I,I,F,F,I,I,c,
c,I,I,I,I,I,I,B,I,I,B,I,I,c,I,I,I,c,I,I,I,I,I,I,I,I,F,F,I,I,c,
_,c,I,I,I,I,I,I,I,I,I,I,I,c,I,I,I,c,c,I,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,I,I,B,I,I,B,I,I,I,I,c,I,I,I,c,I,c,T,T,T,T,T,T,T,T,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,I,I,I,I,B,P2,B,I,I,B,I,I,{name = "doors:door_wood_a", param2 = 3, force_place = true},I,I,I,c,f,I,I,I,h,h,h,h,h,h,h,f,c,
c,I,I,I,I,I,I,D1,I,I,B,I,I,Hi,I,I,I,c,I,I,I,I,I,I,I,I,F,F,I,I,c,
c,I,I,I,I,I,I,B,I,I,B,I,I,c,I,I,I,c,I,I,I,I,I,I,I,I,F,C1,F,I,c,
_,c,I,I,I,I,I,I,I,I,I,I,I,c,I,I,I,c,c,I,I,I,I,I,I,I,I,F,I,c,_,
_,_,c,I,I,B,I,I,B,I,I,I,I,c,I,I,I,c,I,c,T,T,T,T,T,T,T,T,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,I,I,I,I,B,P2,B,I,B,B,I,I,c,I,I,I,c,f,I,I,I,h,h,h,h,h,h,h,f,c,
c,I,I,I,I,I,I,D3,I,I,B,I,I,c,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,I,B,I,I,B,I,I,c,I,I,I,c,I,I,I,I,I,I,I,I,I,F,I,I,c,
_,c,I,I,I,I,I,I,I,I,I,I,I,c,I,I,I,c,c,I,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,I,I,B,I,I,B,I,I,I,I,c,I,I,I,c,I,c,c,c,c,c,c,c,c,c,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,P2,L,I,I,B,P2,B,Y,B,B,I,L,c,L,I,L,c,f,f,f,f,f,f,f,f,f,f,f,f,c,
c,I,I,I,I,I,I,D1,I,B,B,I,I,c,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,I,B,I,I,B,I,I,c,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,I,c,
_,c,I,I,I,I,I,D0,I,I,I,I,I,c,I,I,I,c,c,c,c,c,c,c,c,c,c,c,c,c,_,
_,_,c,I,I,B,I,I,B,I,I,I,I,c,I,I,I,c,I,I,I,I,I,I,I,I,I,I,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,c,c,I,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,
c,c,c,I,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,
c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,
_,c,c,c,c,c,c,c,c,c,c,c,c,c,c,I,c,c,c,I,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,I,I,I,I,I,I,I,I,I,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,I,I,I,I,I,c,M,I,h,h,P2,c,P2,I,L,I,I,c,h,h,I,I,I,I,I,I,I,h,h,c,
c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,d,I,I,I,d,c,c,c,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
_,c,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,c,c,c,c,c,c,c,c,c,c,c,_,
_,_,c,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,I,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,l,G,G,l,G,l,G,G,l,q,c,
c,Y,I,I,I,I,I,I,h,h,h,h,c,P2,I,I,I,m,c,h,I,I,I,I,{name = "mapgen:zol_stone", force_place = true},I,I,I,I,h,c,
c,I,I,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,d,I,I,I,I,I,c,d,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
_,c,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,I,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,c,c,c,c,c,c,c,c,c,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,G,G,G,G,l,G,G,G,G,q,c,
c,I,I,I,I,I,c,I,h,h,h,h,c,I,I,I,I,I,c,I,I,h,I,I,I,I,I,h,I,I,c,
c,I,I,I,I,I,c,I,I,I,I,I,c,c,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,d,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
_,c,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,I,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,c,c,T,T,T,T,T,T,T,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,G,G,l,G,G,G,l,G,G,q,c,
c,I,I,I,I,I,c,I,h,h,h,h,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,c,I,I,I,I,I,c,d,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,d,I,I,d,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
_,c,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,I,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,c,c,T,T,T,T,T,T,T,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,G,G,l,G,G,G,l,G,G,q,c,
c,I,I,I,I,I,c,I,h,h,h,I,c,c,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,d,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
_,c,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,I,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,c,c,T,T,T,T,T,T,T,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,G,G,G,G,l,G,G,G,G,q,c,
c,I,I,I,I,I,c,I,h,h,h,L,c,d,I,I,I,I,c,I,I,h,I,I,I,I,I,h,I,I,c,
c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,d,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
_,c,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,I,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,c,c,T,T,T,T,T,T,T,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,l,G,G,l,G,l,G,G,l,q,c,
c,I,I,I,I,I,c,I,h,h,h,I,c,I,I,I,I,I,c,h,I,I,I,I,I,I,I,I,I,h,c,
c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,d,I,I,d,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
_,c,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,I,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,c,c,c,c,c,c,c,c,c,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,I,L,I,I,I,c,I,h,h,h,h,c,I,I,I,I,I,c,h,h,I,I,I,I,I,I,I,h,h,c,
c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,d,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
_,c,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,c,c,c,c,c,c,c,c,c,c,c,_,
_,_,c,I,I,I,I,I,I,I,I,c,I,I,I,I,I,I,I,I,C1,C1,I,I,c,I,I,I,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,I,I,I,I,I,c,I,I,h,h,h,c,I,I,I,I,I,c,c,c,c,c,c,{name = "doors:door_wood_a", param2 = 2, force_place = true},c,c,c,c,c,c,
c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,c,c,c,c,c,c,Hi,c,c,c,c,c,c,
c,I,I,I,I,I,d,I,I,I,I,I,c,I,I,I,I,I,c,c,c,c,c,c,c,c,c,c,c,c,c,
_,c,I,I,I,I,I,I,I,I,I,I,c,c,I,I,I,c,c,c,c,c,c,S,c,S,c,c,c,c,_,
_,_,c,I,I,I,I,I,I,I,I,I,c,c,c,b,c,c,c,c,c,c,c,c,S,c,c,c,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,I,I,I,I,I,c,I,I,h,h,h,c,I,I,I,I,I,c,I,I,I,I,I,m,I,I,I,I,P2,c,
c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,m,I,m,I,I,I,I,c,
c,I,I,I,I,I,d,I,I,I,d,I,c,I,I,I,I,I,c,I,I,I,m,I,I,I,m,I,I,I,c,
_,c,I,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,c,c,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,c,I,c,T,T,I,I,I,T,T,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,I,I,I,I,I,c,I,I,h,h,h,c,I,I,I,I,I,c,I,L,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,m,I,I,I,I,I,c,
c,I,I,I,I,I,d,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
_,c,I,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,c,c,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,c,I,c,T,T,I,I,I,T,T,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,I,I,I,I,I,c,h,h,h,h,h,c,I,I,I,I,I,c,S,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,d,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
_,c,I,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,c,c,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,I,I,I,{name = "mapgen:shield", force_place = true},I,I,I,I,I,c,I,I,I,I,I,c,I,c,T,T,I,I,I,T,T,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,I,I,I,I,I,c,I,h,h,h,h,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,m,c,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,B,I,I,d,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
_,c,I,I,I,I,B,I,I,I,I,I,c,I,I,I,I,I,c,c,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,I,I,I,B,I,I,I,I,I,c,I,I,I,I,I,c,I,c,T,T,I,I,I,T,T,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,I,I,I,I,d,c,h,h,h,h,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,{name = "mapgen:skull", param2 = 1, force_place = true},I,I,I,c,
c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
_,c,I,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,c,c,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,c,I,c,T,T,T,I,T,T,T,c,_,_,
_,_,_,c,B,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,I,I,I,Y,c,c,I,I,I,I,I,c,I,I,L,I,I,I,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
_,c,I,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,c,c,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,c,I,c,T,T,T,T,T,T,T,c,_,_,
_,_,_,c,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,I,I,I,I,P2,c,I,I,L,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,d,c,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,I,I,I,I,I,I,c,I,I,I,I,I,c,I,I,I,I,I,I,I,I,I,I,I,c,
_,c,I,I,I,I,I,I,I,I,I,I,c,I,Fy,I,Fy,I,c,c,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,I,I,I,I,I,I,I,I,I,c,Fy,I,I,I,Fy,c,I,c,T,T,T,T,T,T,T,c,_,_,
_,_,_,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,I,L,I,I,P2,c,I,I,I,I,M,c,Fy,Fy,Fy,Fy,Fy,c,I,I,I,I,I,I,I,I,I,L,I,c,
c,I,I,I,I,c,c,I,I,I,I,I,c,Fr,Fw,Fy,Fw,Fr,c,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,I,I,I,I,I,I,c,Fr,Fr,Fy,Fr,Fr,c,I,I,I,I,I,I,I,I,I,I,I,c,
_,c,I,I,I,I,I,I,I,I,I,I,c,Fy,Fy,Fy,Fy,Fy,c,c,I,I,I,I,I,I,I,I,I,c,_,
_,_,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

c,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,q,c,
c,I,I,I,I,I,c,M,I,C0,I,I,c,Fy,D0,D0,D0,Fy,c,P2,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,c,I,I,I,I,I,c,Fr,D0,Fy,D0,Fr,c,I,I,I,I,I,I,I,I,I,I,I,c,
c,I,I,I,I,I,I,I,I,I,I,I,c,Fr,Fr,C0,Fr,Fr,c,I,I,I,I,I,I,I,I,I,I,I,c,
_,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,
c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,
c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,
c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,c,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_}}
