
local L = {name = "default:sandstone", force_place = true}
local k = {name = "default:sandstone_brick", force_place = true}
local c = {name = "default:sandstone_block", force_place = true}
local D0 = {name = "mapgen:dartblock", force_place = true}
local D1 = {name = "mapgen:dartblock", param2 = 1, force_place = true}
local D2 = {name = "mapgen:dartblock", param2 = 2, force_place = true}
local D3 = {name = "mapgen:dartblock", param2 = 3, force_place = true}
local W0 = {name = "mapgen:sandstone_wall", force_place = true}
local W1 = {name = "mapgen:sandstone_wall", param2 = 1, force_place = true}
local W2 = {name = "mapgen:sandstone_wall", param2 = 2, force_place = true}
local W3 = {name = "mapgen:sandstone_wall", param2 = 3, force_place = true}
local P1 = {name = "mapgen:sandstone_pillar_base", force_place = true}
local P2 = {name = "mapgen:sandstone_pillar", force_place = true}
local P3 = {name = "mapgen:sandstone_pillar_base", param2 = 20, force_place = true}
local s0 = {name = "stairs:slab_sandstone_block", force_place = true}
local s4 = {name = "stairs:slab_sandstone_block", param2 = 4, force_place = true}
local s8 = {name = "stairs:slab_sandstone_block", param2 = 8, force_place = true}
local sz = {name = "stairs:slab_sandstone_block", param2 = 12, force_place = true}
local sn = {name = "stairs:slab_sandstone_block", param2 = 16, force_place = true}
local a = I
if core.get_modpath("decor") then
	a = {name = "decor:Ancient_vase_sand", force_place = true}
end
pyramid_egypt = {size = {x = 21, y = 12, z = 21}, data = {
k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
c,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,c,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
_,c,k,k,k,k,k,k,k,k,c,k,k,k,k,k,k,k,k,c,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
_,k,k,k,k,k,k,k,k,k,I,k,k,k,k,k,k,k,k,k,_,
_,_,c,k,k,k,k,k,k,k,c,k,k,k,k,k,k,k,c,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
_,k,k,k,k,k,k,k,k,W2,I,W1,k,k,k,k,k,k,k,k,_,
_,_,k,k,k,k,k,k,k,W1,I,W0,k,k,k,k,k,k,k,_,_,
_,_,_,c,k,k,k,k,k,k,k,k,k,k,k,k,k,c,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
_,k,k,k,L,L,L,L,L,L,I,L,L,L,L,L,L,k,k,k,_,
_,_,k,k,L,D2,D2,D2,L,L,I,L,L,D2,D2,D2,L,k,k,_,_,
_,_,_,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,_,_,_,
_,_,_,_,c,k,k,k,k,k,k,k,k,k,k,k,c,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
_,k,k,k,L,s0,a,a,W3,s4,I,s4,W3,a,a,s0,L,k,k,k,_,
_,_,k,k,L,s4,s4,s4,W2,s4,I,s4,W1,s4,s4,s4,L,k,k,_,_,
_,_,_,k,k,I,I,I,W1,s4,s4,s4,W2,I,I,I,k,k,_,_,_,
_,_,_,_,k,k,k,k,k,k,k,k,k,k,k,k,k,_,_,_,_,
_,_,_,_,_,c,k,k,k,k,k,k,k,k,k,c,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
_,k,k,k,L,I,I,I,I,I,I,I,I,I,I,I,L,k,k,k,_,
_,_,k,k,L,I,I,I,I,I,I,I,I,I,I,I,L,k,k,_,_,
_,_,_,k,k,I,I,I,I,I,I,I,I,I,I,I,k,k,_,_,_,
_,_,_,_,k,k,I,I,I,I,I,I,I,I,I,k,k,_,_,_,_,
_,_,_,_,_,k,k,k,k,k,k,k,k,k,k,k,_,_,_,_,_,
_,_,_,_,_,_,c,k,k,k,k,k,k,k,c,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
_,k,k,k,L,I,I,I,I,I,I,I,I,I,I,I,L,k,k,k,_,
_,_,k,k,L,I,I,I,I,I,I,I,I,I,I,I,L,k,k,_,_,
_,_,_,k,k,I,I,I,I,I,I,I,I,I,I,I,k,k,_,_,_,
_,_,_,_,k,k,I,I,I,I,I,I,I,I,I,k,k,_,_,_,_,
_,_,_,_,_,k,k,I,I,I,I,I,I,I,k,k,_,_,_,_,_,
_,_,_,_,_,_,k,k,k,k,k,k,k,k,k,_,_,_,_,_,_,
_,_,_,_,_,_,_,c,k,k,k,k,k,c,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
_,k,k,k,L,sz,I,I,P1,I,I,I,P1,I,I,sn,L,k,k,k,_,
_,_,k,k,L,sz,I,I,P2,I,I,I,P2,I,I,sn,L,k,k,_,_,
_,_,_,k,k,sz,I,I,P2,I,I,I,P2,I,I,sn,k,k,_,_,_,
_,_,_,_,k,k,I,I,P2,I,I,I,P2,I,I,k,k,_,_,_,_,
_,_,_,_,_,k,k,I,P2,I,I,I,P2,I,k,k,_,_,_,_,_,
_,_,_,_,_,_,k,k,P3,I,I,I,P3,k,k,_,_,_,_,_,_,
_,_,_,_,_,_,_,k,k,k,k,k,k,k,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,c,k,k,k,c,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
k,k,k,k,k,k,k,k,k,c,c,c,k,k,k,k,k,k,k,k,k,
_,k,k,k,L,I,I,I,I,I,I,I,I,I,I,I,L,k,k,k,_,
_,_,k,k,W3,I,I,I,I,I,I,I,I,I,I,I,W1,k,k,_,_,
_,_,_,k,k,I,I,I,I,I,I,I,I,I,I,I,k,k,_,_,_,
_,_,_,_,k,k,I,I,I,I,I,I,I,I,I,k,k,_,_,_,_,
_,_,_,_,_,k,k,I,I,I,I,I,I,I,k,k,_,_,_,_,_,
_,_,_,_,_,_,k,k,I,I,I,I,I,k,k,_,_,_,_,_,_,
_,_,_,_,_,_,_,k,k,I,I,I,k,k,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,k,k,k,k,k,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,c,k,c,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
k,k,k,k,k,k,k,k,k,c,c,c,k,k,k,k,k,k,k,k,k,
_,k,k,k,L,sz,I,I,I,s0,I,s0,I,I,I,sn,L,k,k,k,_,
_,_,k,k,D3,sz,I,I,I,I,I,I,I,I,I,sn,D1,k,k,_,_,
_,_,_,k,k,sz,I,I,I,I,I,I,I,I,I,sn,k,k,_,_,_,
_,_,_,_,k,k,I,I,I,I,I,I,I,I,I,k,k,_,_,_,_,
_,_,_,_,_,k,k,I,I,I,I,I,I,I,k,k,_,_,_,_,_,
_,_,_,_,_,_,k,k,I,I,I,I,I,k,k,_,_,_,_,_,_,
_,_,_,_,_,_,_,k,k,I,I,I,k,k,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,k,k,I,k,k,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,k,k,k,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,c,_,_,_,_,_,_,_,_,_,_,

k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
k,k,k,k,k,k,k,k,k,c,c,c,k,k,k,k,k,k,k,k,k,
_,k,k,k,L,I,I,I,I,s0,{name = "schem_spawn:chest_placer", force_place = true},s0,I,I,I,{param2 = 1, name = "mapgen:old_skeleton", force_place = true},L,k,k,k,_,
_,_,k,k,W3,I,I,I,I,I,I,I,I,I,I,I,W1,k,k,_,_,
_,_,_,k,k,I,I,I,I,I,I,I,I,I,I,I,k,k,_,_,_,
_,_,_,_,k,k,I,I,I,I,I,I,I,I,I,k,k,_,_,_,_,
_,_,_,_,_,k,k,I,I,I,I,I,I,I,k,k,_,_,_,_,_,
_,_,_,_,_,_,k,k,I,I,I,I,I,k,k,_,_,_,_,_,_,
_,_,_,_,_,_,_,k,k,I,I,I,k,k,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,k,k,k,k,k,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,c,k,c,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
_,k,k,k,L,sz,I,I,P1,I,I,I,P1,I,I,sn,L,k,k,k,_,
_,_,k,k,L,sz,I,I,P2,I,I,I,P2,I,I,sn,L,k,k,_,_,
_,_,_,k,k,sz,I,I,P2,I,I,I,P2,I,I,sn,k,k,_,_,_,
_,_,_,_,k,k,I,I,P2,I,I,I,P2,I,I,k,k,_,_,_,_,
_,_,_,_,_,k,k,I,P2,I,I,I,P2,I,k,k,_,_,_,_,_,
_,_,_,_,_,_,k,k,P3,I,I,I,P3,k,k,_,_,_,_,_,_,
_,_,_,_,_,_,_,k,k,k,k,k,k,k,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,c,k,k,k,c,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
_,k,k,k,L,I,I,I,I,I,I,I,I,I,I,I,L,k,k,k,_,
_,_,k,k,L,I,I,I,I,I,I,I,I,I,I,I,L,k,k,_,_,
_,_,_,k,k,I,I,I,I,I,I,I,I,I,I,I,k,k,_,_,_,
_,_,_,_,k,k,I,I,I,I,I,I,I,I,I,k,k,_,_,_,_,
_,_,_,_,_,k,k,I,I,I,I,I,I,I,k,k,_,_,_,_,_,
_,_,_,_,_,_,k,k,k,k,k,k,k,k,k,_,_,_,_,_,_,
_,_,_,_,_,_,_,c,k,k,k,k,k,c,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
_,k,k,k,L,I,{name = "mapgen:old_skeleton", force_place = true},s8,I,a,P1,a,I,s8,I,I,L,k,k,k,_,
_,_,k,k,L,I,I,s8,I,I,{name = "bones:bones", force_place = true},I,I,s8,I,I,L,k,k,_,_,
_,_,_,k,k,I,I,s8,I,I,I,I,I,s8,I,I,k,k,_,_,_,
_,_,_,_,k,k,I,s8,I,I,I,I,I,s8,I,k,k,_,_,_,_,
_,_,_,_,_,k,k,k,k,k,k,k,k,k,k,k,_,_,_,_,_,
_,_,_,_,_,_,c,k,k,k,k,k,k,k,c,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
_,k,k,k,L,W3,W0,L,W0,W3,W1,W1,W3,L,W2,W1,L,k,k,k,_,
_,_,k,k,L,W2,W1,L,W1,W1,D0,W0,W2,L,W1,W0,L,k,k,_,_,
_,_,_,k,k,L,L,L,W0,W1,W0,W3,W0,L,L,L,k,k,_,_,_,
_,_,_,_,k,k,k,k,k,k,k,k,k,k,k,k,k,_,_,_,_,
_,_,_,_,_,c,k,k,k,k,k,k,k,k,k,c,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
_,k,k,k,L,L,L,L,L,L,L,L,L,L,L,L,L,k,k,k,_,
_,_,k,k,L,L,L,L,L,L,L,L,L,L,L,L,L,k,k,_,_,
_,_,_,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,_,_,_,
_,_,_,_,c,k,k,k,k,k,k,k,k,k,k,k,c,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
_,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,_,
_,_,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,_,_,
_,_,_,c,k,k,k,k,k,k,k,k,k,k,k,k,k,c,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
_,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,_,
_,_,c,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,c,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
_,c,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,c,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,
c,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,k,c,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_}}

local W = {name = "default:stone_brick", force_place = true}
local X = {name = "default:mossystone_brick", force_place = true}
local C = {name = "stairs:stair_cobble", force_place = true}
local D = {name = "stairs:stair_mossycobble", force_place = true}
local E = {name = "stairs:stair_cobble", param2 = 3, force_place = true}
local F = {name = "stairs:stair_mossycobble", param2 = 3, force_place = true}
local G = {name = "stairs:stair_cobble", param2 = 1, force_place = true}
local H = {name = "stairs:stair_mossycobble", param2 = 1, force_place = true}
local J = {name = "stairs:stair_cobble", param2 = 2, force_place = true}
local K = {name = "stairs:stair_mossycobble", param2 = 2, force_place = true}
local R = {name = "stairs:slab_stone_brick", force_place = true}
local m = I
if core.get_modpath("ecology") then
	m = {name = "ecology:moss", param2 = 1, force_place = true}
end
local g = {name = "default:jungle_grass_1", force_place = true}
local h = {name = "default:jungle_grass_2", force_place = true}
local j = {name = "default:jungle_grass_3", force_place = true}
local A = I
if core.get_modpath("decor") then
	A = {name = "decor:Ancient_vase", force_place = true}
end
pyramid_aztec = {size = {x = 25, y = 13, z = 25}, data = {
I,I,I,I,I,I,I,I,I,I,W,C,C,C,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,

I,I,I,I,I,I,I,I,I,I,W,W,W,W,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,C,D,C,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,

I,I,W,X,X,W,W,X,W,W,W,W,W,W,W,X,W,W,X,X,W,W,X,I,I,
I,I,I,j,I,I,I,h,I,I,W,W,W,X,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,C,C,C,X,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,

I,I,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,I,I,
I,I,I,W,W,X,W,X,W,W,W,W,W,W,W,W,X,W,W,W,X,W,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,X,W,W,W,I,h,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,D,C,C,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,

I,I,W,W,W,W,W,X,W,W,W,X,X,W,W,X,W,W,X,X,W,W,X,I,I,
I,I,I,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,h,I,I,
I,I,I,I,W,W,X,W,W,W,W,W,W,W,W,W,W,W,X,X,W,I,I,I,I,
I,I,I,I,I,I,g,I,I,I,W,W,W,W,X,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,C,C,C,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,

I,I,X,W,W,W,W,W,X,W,W,W,W,W,X,W,W,W,X,W,X,W,W,I,I,
I,I,I,X,W,W,W,W,D2,W,W,W,D2,W,W,W,W,W,W,W,W,W,I,I,I,
I,I,I,m,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,I,I,I,I,
I,I,I,I,m,W,W,W,W,X,W,W,W,W,W,W,W,X,W,X,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,W,W,W,W,I,I,I,I,g,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,C,D,C,X,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,g,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,

I,I,W,W,X,W,W,W,W,W,W,W,X,W,W,W,X,W,X,W,W,W,W,I,I,
I,I,m,W,W,W,W,W,I,W,W,{name = "mapgen:skull", param2 = 2, force_place = true},I,I,W,W,X,W,W,W,W,X,I,I,I,
I,I,I,m,W,W,W,W,W,X,W,I,I,I,W,W,W,W,W,W,W,I,I,I,I,
I,I,I,I,m,X,W,X,X,W,X,I,I,I,W,W,W,W,W,X,I,I,I,I,I,
I,I,I,I,I,g,W,W,X,W,W,W,W,W,W,W,X,X,W,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,m,m,X,W,W,W,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,C,C,C,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,

I,I,W,W,X,W,W,X,W,W,W,X,W,W,W,W,W,X,W,W,W,W,X,I,I,
I,I,I,W,W,W,W,I,I,I,I,I,I,I,X,I,I,I,W,W,W,W,I,I,I,
I,I,I,m,X,W,W,I,I,I,I,I,I,I,W,I,I,I,W,W,W,I,I,I,I,
I,I,I,I,m,W,W,I,I,I,W,I,I,I,W,I,I,I,X,W,I,I,I,I,I,
I,I,I,I,I,m,X,W,W,W,W,I,I,I,W,X,W,W,W,m,I,I,I,I,I,
I,I,I,I,I,I,I,W,W,W,W,W,X,W,W,W,W,X,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,m,m,m,W,W,W,W,W,I,I,g,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,X,C,C,D,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,j,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,

I,I,X,W,W,X,W,W,X,X,W,W,X,W,W,X,W,W,W,X,W,W,W,I,I,
I,I,I,W,W,W,X,I,I,I,W,I,I,I,W,{name = "schem_spawn:chest_placer", param2 = 3, force_place = true},I,I,I,D1,W,W,I,I,I,
I,I,I,I,W,W,W,I,I,I,X,I,I,I,W,{name = "mapgen:skull", param2 = 3, force_place = true},I,I,W,W,X,I,I,I,I,
I,I,I,I,m,W,W,I,I,I,W,I,I,I,X,I,I,I,W,W,I,I,I,I,I,
I,I,I,I,I,I,W,X,W,W,W,I,I,I,W,W,W,X,W,m,I,I,I,I,I,
I,I,I,I,I,I,I,W,W,W,W,I,I,I,W,W,W,W,m,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,X,W,W,W,W,W,W,W,W,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,h,m,W,W,W,W,X,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,C,C,C,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,

I,I,W,W,W,W,W,W,W,W,X,W,W,W,W,X,W,W,W,W,W,W,W,I,I,
I,I,I,X,W,W,W,I,{name = "mapgen:old_skeleton", force_place = true},I,W,A,I,A,W,I,I,I,W,W,W,X,I,I,I,
I,I,I,h,W,W,W,I,I,I,W,I,I,I,W,I,I,I,X,W,W,g,I,I,I,
I,I,I,I,I,W,W,I,I,I,W,I,I,I,W,I,I,I,W,W,m,I,I,I,I,
I,I,I,I,I,I,W,W,W,W,X,I,I,I,W,W,W,W,X,m,I,I,I,I,I,
I,I,I,I,I,I,I,W,W,W,W,I,I,I,W,W,W,W,m,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,W,W,W,W,W,W,W,W,W,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,W,W,W,W,W,W,W,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,W,W,X,X,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,m,m,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,

W,W,W,W,W,X,W,W,X,X,W,W,X,W,X,W,W,W,W,W,W,W,W,W,W,
I,X,W,X,W,W,W,W,X,W,{name = "mapgen:pot", force_place = true},W,I,W,{name = "mapgen:pot", force_place = true},W,X,I,W,W,W,W,W,X,I,
I,I,W,X,W,W,W,X,W,W,W,W,I,W,W,X,W,I,W,W,W,W,W,h,I,
I,I,I,W,W,W,W,W,W,X,W,X,X,W,W,W,W,W,W,W,W,W,I,I,I,
I,I,I,I,X,W,W,W,X,W,W,W,X,W,W,W,X,W,W,W,X,I,I,I,I,
I,I,I,I,I,W,X,W,W,W,W,W,W,W,W,W,W,W,X,W,I,I,I,I,I,
I,I,I,I,I,I,W,W,W,W,W,W,W,W,W,W,W,W,W,I,I,I,I,I,I,
I,I,I,I,I,I,I,W,W,W,W,W,W,W,W,W,W,W,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,W,W,W,W,W,W,W,W,X,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,X,m,W,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,X,I,W,X,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,X,{name = "stairs:stair_stone_brick", force_place = true},{name = "stairs:stair_stone_brick", force_place = true},{name = "stairs:stair_stone_brick", force_place = true},W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,R,R,R,R,R,I,I,I,I,I,I,I,I,I,I,

H,W,W,W,W,X,W,W,X,X,X,W,W,W,W,W,X,W,X,W,X,W,W,W,F,
I,G,W,W,W,W,I,I,I,A,W,I,I,I,W,A,I,I,I,W,W,W,X,E,I,
I,I,G,W,W,X,I,I,I,I,W,I,I,I,W,I,I,I,I,W,W,W,E,I,I,
I,I,I,G,W,W,I,I,I,I,W,I,I,I,W,I,I,I,I,W,W,E,I,I,I,
I,I,I,I,G,W,X,I,I,I,W,I,I,I,W,I,I,I,X,W,F,I,I,I,I,
I,I,I,I,I,G,W,W,I,I,X,I,I,I,X,I,I,W,W,E,I,I,I,I,I,
I,I,I,I,I,I,G,W,W,W,W,I,I,I,X,X,W,W,E,I,I,I,I,I,I,
I,I,I,I,I,I,I,H,W,W,W,I,I,I,X,W,W,E,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,G,W,W,{name = "default:rocks", force_place = true},{name = "default:rocks", force_place = true},{name = "default:rocks", force_place = true},W,W,E,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,I,I,I,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,X,I,I,I,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,{name = "stairs:stair_stone_brick", param2 = 1, force_place = true},I,I,I,{name = "stairs:stair_stone_brick", param2 = 3, force_place = true},I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,R,R,R,R,R,I,I,I,I,I,I,I,I,I,I,

G,W,W,X,W,X,W,X,W,X,W,X,X,W,X,X,W,W,W,X,W,W,W,W,E,
I,G,W,W,W,D3,I,I,I,I,I,I,I,I,I,I,I,I,I,D1,W,W,W,E,I,
I,I,H,W,W,X,I,I,I,I,I,I,I,I,I,I,I,I,I,W,W,W,E,I,I,
I,I,I,H,W,W,I,I,I,I,W,I,I,I,X,I,I,I,I,W,W,E,I,I,I,
I,I,I,I,G,W,W,I,I,I,W,I,I,I,W,I,I,I,W,W,F,I,I,I,I,
I,I,I,I,I,G,W,W,I,I,W,I,I,I,W,I,I,W,W,E,I,I,I,I,I,
I,I,I,I,I,I,G,W,W,W,X,I,I,I,X,W,W,W,F,I,I,I,I,I,I,
I,I,I,I,I,I,I,G,W,W,W,I,I,I,W,W,W,E,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,G,W,X,{name = "default:rocks", force_place = true},{name = "default:rocks", force_place = true},{name = "default:rocks", force_place = true},X,W,E,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,{name = "stairs:stair_stone_brick", param2 = 1, force_place = true},I,I,I,{name = "stairs:stair_stone_brick", param2 = 3, force_place = true},I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,R,R,R,R,R,I,I,I,I,I,I,I,I,I,I,

G,W,W,W,W,W,X,W,X,W,W,W,W,W,W,X,X,W,W,X,W,W,W,X,E,
I,G,W,W,W,W,I,I,I,A,X,I,I,I,W,A,I,{name = "mapgen:skull", force_place = true},I,W,W,W,W,E,I,
I,I,H,X,W,W,I,I,I,I,W,I,I,I,W,I,I,I,I,X,W,W,F,I,I,
I,I,I,G,W,W,I,I,I,I,X,I,I,I,W,I,I,I,I,W,W,E,I,I,I,
I,I,I,I,G,W,W,I,I,I,W,I,I,I,W,I,I,I,W,W,E,I,I,I,I,
I,I,I,I,I,G,W,W,I,I,W,I,I,I,W,I,I,X,W,E,I,I,I,I,I,
I,I,I,I,I,I,H,W,W,W,W,I,I,I,W,W,W,W,E,I,I,I,I,I,I,
I,I,I,I,I,I,I,G,W,W,W,I,I,I,W,W,W,F,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,G,W,W,{name = "default:rocks", force_place = true},{name = "default:rocks", force_place = true},{name = "default:rocks", force_place = true},W,W,E,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,I,I,I,X,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,I,I,I,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,{name = "stairs:stair_stone_brick", param2 = 1, force_place = true},I,I,I,{name = "stairs:stair_stone_brick", param2 = 3, force_place = true},I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,R,R,R,R,R,I,I,I,I,I,I,I,I,I,I,

W,W,W,W,W,X,W,W,X,W,W,W,W,X,W,W,W,X,W,W,W,W,W,W,W,
I,W,W,W,W,W,W,I,W,W,{name = "mapgen:pot", force_place = true},W,I,W,{name = "mapgen:pot", force_place = true},W,W,W,X,W,W,W,X,W,I,
I,I,W,W,W,W,W,I,X,W,W,W,I,W,W,X,W,X,W,W,W,W,W,I,I,
I,I,I,W,W,W,W,W,W,W,W,W,W,X,W,W,X,W,W,W,W,W,I,I,I,
I,I,I,I,W,W,W,W,W,X,W,W,W,X,W,W,W,W,W,X,X,I,I,I,I,
I,I,I,I,I,X,W,W,X,W,W,X,W,W,W,W,W,W,W,W,g,I,I,I,I,
I,I,I,I,I,g,W,W,W,W,W,W,W,W,W,W,W,X,W,I,I,I,I,I,I,
I,I,I,I,I,I,I,W,X,W,W,W,W,W,W,W,W,W,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,X,W,W,W,W,W,W,X,W,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,j,I,W,W,I,W,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,X,I,X,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,X,{name = "stairs:stair_stone_brick", param2 = 2, force_place = true},{name = "stairs:stair_stone_brick", param2 = 2, force_place = true},{name = "stairs:stair_stone_brick", param2 = 2, force_place = true},W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,R,R,R,R,R,I,I,I,I,I,I,I,I,I,I,

I,I,W,W,W,W,W,W,W,X,W,X,W,X,W,X,W,X,W,W,X,W,W,I,I,
I,I,I,W,W,W,W,I,I,I,W,A,I,A,W,I,{name = "schem_spawn:chest_placer", param2 = 2, force_place = true},I,W,W,W,W,I,I,I,
I,I,I,I,X,W,W,I,I,I,X,I,I,I,W,I,I,I,W,W,X,I,I,I,I,
I,I,I,I,I,W,X,I,I,I,W,I,I,I,W,I,I,I,W,W,I,I,I,I,I,
I,I,I,I,I,I,W,W,W,W,W,I,I,I,W,W,W,W,W,I,I,I,I,I,I,
I,I,I,I,I,I,I,W,W,W,W,I,I,I,X,W,W,W,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,W,W,W,W,W,W,W,W,X,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,W,W,W,W,W,W,W,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,W,W,X,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,m,m,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,

I,I,X,W,X,X,W,X,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,I,I,
I,I,g,W,W,D3,I,I,I,{name = "schem_spawn:chest_placer", param2 = 1, force_place = true},W,I,I,I,X,I,I,I,W,W,W,X,I,I,I,
I,I,I,I,W,W,W,I,I,I,W,I,I,I,W,I,I,I,X,W,W,I,I,I,I,
I,I,I,I,I,W,W,I,I,I,W,I,I,I,X,I,I,I,W,W,I,I,I,I,I,
I,I,I,I,I,I,X,W,X,W,X,I,I,I,W,W,W,W,W,I,I,I,I,I,I,
I,I,I,I,I,I,I,W,W,W,X,I,I,I,W,W,W,W,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,W,X,W,W,W,W,W,W,W,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,W,W,W,X,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,J,J,J,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,

I,I,W,W,X,W,X,W,W,W,X,W,X,W,W,W,X,W,W,W,W,W,X,I,I,
I,I,I,X,W,W,X,I,{name = "mapgen:skull", force_place = true},I,W,I,I,I,I,I,I,I,X,W,W,W,j,I,I,
I,I,I,I,W,W,W,I,I,I,W,I,I,I,I,I,I,I,W,W,X,I,I,I,I,
I,I,I,I,I,W,W,I,I,I,X,I,I,I,W,I,I,I,W,W,I,I,I,I,I,
I,I,I,I,I,I,W,W,W,W,W,I,I,I,W,W,W,W,W,I,I,I,I,I,I,
I,I,I,I,I,I,I,X,W,W,W,W,W,W,W,W,X,W,m,I,I,I,I,I,I,
I,I,I,I,I,I,I,j,I,I,W,W,W,W,X,I,m,m,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,X,J,J,K,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,

I,I,W,W,W,W,W,X,W,W,X,W,W,X,W,W,W,W,W,X,W,W,W,I,I,
I,I,I,W,W,W,W,W,W,X,W,I,I,I,W,X,I,W,W,W,W,W,I,I,I,
I,I,I,I,W,W,W,X,W,X,W,I,I,I,W,X,W,W,W,W,X,I,I,I,I,
I,I,I,I,I,X,W,W,X,W,W,I,I,I,W,W,X,W,W,W,g,I,I,I,I,
I,I,I,I,I,I,W,X,W,W,W,W,W,W,W,W,W,X,X,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,W,W,W,W,I,m,m,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,J,J,J,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,

I,I,W,W,W,X,W,W,X,W,X,W,W,W,W,W,W,X,W,W,X,W,W,I,I,
I,I,m,W,W,W,W,W,W,W,W,W,D0,W,W,W,D0,W,W,W,W,W,I,I,I,
I,I,I,I,X,W,W,W,W,W,W,X,W,W,W,W,W,W,W,W,W,I,I,I,I,
I,I,I,I,I,W,X,W,W,X,W,W,W,X,W,W,X,W,W,W,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,h,W,W,W,W,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,J,J,J,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,

I,I,W,W,W,W,X,W,W,X,W,X,W,X,W,W,W,X,W,W,X,W,X,I,I,
I,I,m,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,W,X,I,I,I,
I,I,I,m,X,W,W,X,W,W,W,W,W,W,W,W,W,X,W,W,W,m,I,I,I,
I,I,I,I,I,I,I,I,I,I,X,W,W,W,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,K,K,J,X,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,h,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,

I,I,X,W,W,W,W,W,W,W,W,W,X,W,W,W,W,W,W,W,W,W,W,I,I,
I,I,m,W,W,X,W,W,X,W,W,W,W,W,W,W,W,X,X,W,W,W,m,I,I,
I,I,I,m,I,I,I,I,I,I,W,W,W,W,W,I,I,I,I,I,m,m,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,J,J,J,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,

I,I,W,X,X,W,W,X,X,W,W,W,W,W,W,W,X,W,W,X,W,W,X,I,I,
I,I,m,m,h,I,I,I,I,I,W,W,W,W,W,I,j,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,X,J,K,J,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,

I,I,I,I,I,I,I,I,I,I,X,W,W,W,W,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,W,J,J,J,X,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,

I,I,I,I,I,I,I,I,I,I,X,J,J,K,X,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,j,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,
I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I}}
