--mob_players
--Maikerumine edited by Biomeguy
--made for Extreme Survival game
--License for code is WTFPL

mobs:register_mob("es:playerbad1", {
	type = "monster",
	hp_min = 25,
	hp_max = 40,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_27.png"}},
	specific_attack = {"player","es:Ghost"},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	docile_by_day = true,
	view_range = 10,
	walk_velocity = 2.5,
	run_velocity = 3,
	damage = 2,
	reach = 2,
	drops = {
		{name = "default:apple", chance = 7, min = 0, max = 1},
		{name = "default:sword_steel", chance = 5, min = 0, max = 1},
		{name = "default:stick", chance = 2, min = 0, max = 3},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 0,
	lava_damage = 1,
	light_damage = 0,
	fear_height = 3,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
})

mobs:register_mob("es:playerbad2", {
	type = "monster",
	hp_min = 35,
	hp_max = 75,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_2.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 3,
	damage = 3,
	drops = {
		{name = "default:jungle_trunk", chance = 1, min = 0, max = 2},
		{name = "default:sword_steel", chance = 2, min = 0, max = 1},
		{name = "default:stick", chance = 2, min = 0, max = 3},
	},
	armor = 100,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "default_punch",
	},
})

mobs:register_mob("es:playerbad3", {
	type = "monster",
	hp_min = 49,
	hp_max = 83,
	collisionbox = {-.3, 0, -.3, .3, 1.5, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_3.png"}},
	visual_size = {x=1.2, y=.9},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 0.1,
	run_velocity = 2,
	damage = 3,
	drops = {
		{name = "default:stone_with_mese", chance = 7, min = 0, max = 5},
		{name = "default:sword_steel", chance = 1, min = 0, max = 1},
		{name = "default:apple", chance = 1, min = 1, max = 3},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell2",
		death = "mobs_howl",
		attack = "default_punch3",
	},
})

mobs:register_mob("es:playerbad4", {
	type = "monster",
	hp_min = 37,
	hp_max = 82,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_4.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 3,
	damage = 3,
	drops = {
		{name = "default:sword_steel", chance = 2, min =0, max = 1},
		{name = "default:pick_steel", chance = 4, min = 0, max = 1},
		{name = "default:steel_ingot", chance = 2, min = 1, max = 3},
	},
	armor = 100,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "default_punch2",
	},
})

mobs:register_mob("es:playerbad5", {
	type = "monster",
	hp_min = 130,
	hp_max = 140,
	collisionbox = {-.3, 0, -.3, .3, 1.4, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_5.png"}},
	visual_size = {x=.9, y=.8},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 3,
	run_velocity = 4,
	damage = 3,
	drops = {
		{name = "default:sword_mese", chance = 3, min = 0, max = 1},
		{name = "default:gold_ingot", chance = 3, min = 0, max = 1},
		{name = "default:apple", chance = 2, min = 1, max = 3},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "default_punch3",
	},
})

mobs:register_mob("es:playerbad6", {
	type = "monster",
	hp_min = 37,
	hp_max = 70,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_6.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1.2,
	run_velocity = 3,
	damage = 3,
	drops = {
		{name = "default:sword_mese", chance = 2, min = 0, max = 1},
		{name = "default:steel_ingot", chance = 3, min = 0, max = 5},
		{name = "default:apple", chance = 1, min = 1, max = 2},
	},
	armor = 85,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell2",
		death = "mobs_yeti_death",
		attack = "mobs_oerkki_attack",
	},
})

mobs:register_mob("es:playerbad7", {
	type = "monster",
	hp_min = 157,
	hp_max = 195,
	collisionbox = {-.2, 0, -.2, .2, 1.4, .2},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_7.png"}},
	visual_size = {x=.6, y=.8},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 1.5,
	damage = 3,
	drops = {
		{name = "default:snow", chance = 1, min = 3, max = 33},
		{name = "default:sword_steel", chance = 2, min = 0, max = 1},
		{name = "default:ice", chance = 2, min = 13, max = 30},
	},
	armor = 100,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "default_punch",
	},
})

mobs:register_mob("es:playerbad8", {
	type = "monster",
	hp_min = 177,
	hp_max = 190,
	collisionbox = {-.3, 0, -.3, .3, 1.4, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_8.png"}},
	visual_size = {x=.9, y=.8},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 3,
	damage = 3,
	drops = {
		{name = "default:sword_diamond", chance = 2, min = 0, max = 1},
		{name = "default:stone_with_diamond", chance = 6, min = 0, max = 3},
		{name = "default:apple", chance = 1, min = 1, max = 3},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "default_punch3",
	},
})

mobs:register_mob("es:playerbad9", {
	type = "monster",
	hp_min = 157,
	hp_max = 200,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_9.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 10,
	walk_velocity = 0.5,
	run_velocity =15,
	damage = 4,
	drops = {
		{name = "farming:cotton", chance = 1, min = 3, max = 5},
		{name = "default:sword_diamond", chance = 3, min = 0, max = 1},
		{name = "default:sword_mese", chance = 2, min = 0, max = 1},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_fireball",
		attack = "mobs_slash_attack",
	},
})

mobs:register_mob("es:playerbad10", {
	type = "monster",
	hp_min = 49,
	hp_max = 85,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_10.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 2,
	damage = 3,
	drops = {
		{name = "default:sapling", chance = 1, min = 3, max = 5},
		{name = "default:sword_steel", chance = 6, min = 0, max = 1},
		{name = "default:dirt", chance = 2, min = 13, max = 30},
	},
	armor = 100,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "default_punch",
	},
})

mobs:register_mob("es:playerbad11", {
	type = "monster",
	hp_min = 57,
	hp_max = 85,
	collisionbox = {-.3, 0, -.3, .3, .9, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_11.png"}},
	visual_size = {x=1, y=.5},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 0.3,
	run_velocity = 1.5,
	damage = 3,
	drops = {
		{name = "default:grass_1", chance = 1, min = 3, max = 5},
		{name = "default:sword_steel", chance = 2, min = 1, max = 1},
		{name = "default:sand", chance = 2, min = 13, max = 30},
	},
	armor = 100,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "default_punch3",
	},
})

mobs:register_mob("es:playerbad12", {
	type = "monster",
	hp_min = 47,
	hp_max = 85,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_12.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 1.4,
	damage = 3,
	drops = {
		{name = "default:pick_steel", chance = 1, min = 0, max = 1},
		{name = "default:sword_steel", chance = 1, min = 1, max = 1},
		{name = "default:stick", chance = 2, min = 1, max = 5},
	},
	armor = 90,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "default_punch2",
	},
})

mobs:register_mob("es:playerbad13", {
	type = "monster",
	hp_min = 48,
	hp_max = 77,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_13.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 2,
	damage = 3,
	drops = {
		{name = "default:pick_stone", chance = 1, min = 1, max = 3},
		{name = "default:sword_stone", chance = 5, min = 0, max = 1},
		{name = "default:stone_with_gold", chance = 2, min = 4, max = 8},
	},
	armor = 90,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_eerie",
		death = "mobs_yeti_death",
		attack = "default_punch3",
	},
})

mobs:register_mob("es:playerbad14", {
	type = "monster",
	hp_min = 77,
	hp_max = 90,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_14.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	attack_monsters = true,
	group_attack = true,
	view_range = 15,
	walk_velocity = 3,
	run_velocity = 3,
	damage = 4,
	drops = {
		{name = "default:chest", chance = 1, min = 0, max = 1},
		{name = "default:sword_steel", chance = 1, min = 0, max = 1},
		{name = "default:book", chance = 4, min = 1, max = 30},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_die_yell",
		death = "mobs_death2",
		attack = "default_punch2",
	},
})

mobs:register_mob("es:playerbad15", {
	type = "monster",
	hp_min = 127,
	hp_max = 152,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_15.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 17,
	walk_velocity = 1.3,
	run_velocity = 3.5,
	damage = 3,
	drops = {
		{name = "default:steel_block", chance = 3, min = 0, max = 2},
		{name = "default:sword_steel", chance = 1, min = 0, max = 1},
		{name = "default:bronze_ingot", chance = 2, min = 1, max = 3},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "default_punch",
	},
})

mobs:register_mob("es:playerbad16", {
	type = "monster",
	hp_min = 137,
	hp_max = 159,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_16.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	fly = true,
	view_range = 15,
	walk_velocity = 0.5,
	run_velocity = 3,
	damage = 2.5,
	drops = {
		{name = "default:gold_block", chance = 6, min = 1, max = 4},
		{name = "default:sword_steel", chance = 1, min = 0, max = 1},
		{name = "default:stick", chance = 2, min = 0, max = 3},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell2",
		death = "mobs_barbarian_death",
		attack = "default_punch3",
	},
})

mobs:register_mob("es:playerbad17", {
	type = "monster",
	hp_min = 100,
	hp_max = 120,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_17.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 12,
	walk_velocity = 2,
	run_velocity = 3,
	damage = 5,
	drops = {
		{name = "default:pick_diamond", chance = 2, min = 0, max = 1},
		{name = "default:sword_diamond", chance = 1, min = 0, max = 2},
		{name = "default:apple", chance = 2, min = 1, max = 5},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "default_punch2",
	},
})

mobs:register_mob("es:playerbad18", {
	type = "monster",
	hp_min = 73,
	hp_max = 80,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_18.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 2,
	damage = 3,
	drops = {
		{name = "default:axe_steel", chance = 1, min = 0, max = 2},
		{name = "farming:seed_cotton", chance = 1, min = 0, max = 1},
		{name = "default:stick", chance = 2, min = 1, max = 3},
	},
	armor = 90,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "default_punch",
	},
})

mobs:register_mob("es:playerbad19", {
	type = "monster",
	hp_min = 99,
	hp_max = 140,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_19.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 10,
	walk_velocity = 2,
	run_velocity = 4,
	damage = 6,
	drops = {
		{name = "default:sword_diamond", chance = 1, min = 0, max = 1},
		{name = "default:apple", chance = 1, min = 1, max = 7},
		{name = "default:stick", chance = 1, min = 1, max = 3},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell2",
		death = "mobs_barbarian_death",
		attack = "default_punch3",
	},
})

mobs:register_mob("es:playerbad20", {
	type = "monster",
	hp_min = 77,
	hp_max = 90,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_20.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 0.5,
	run_velocity = 1.5,
	damage = 3,
	drops = {
		{name = "default:obsidian", chance = 2, min = 0, max = 5},
		{name = "default:sword_steel", chance = 1, min = 0, max = 1},
		{name = "default:apple", chance = 2, min = 1, max = 3},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "default_punch2",
	},
})

mobs:register_mob("es:playerbad21", {
	type = "monster",
	hp_min = 69,
	hp_max = 89,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_21.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 2,
	damage = 3,
	drops = {
		{name = "default:sword_stone", chance = 1, min = 0, max = 2},
		{name = "default:water_flowing", chance = 3, min = 1, max = 3},
		{name = "default:apple", chance = 2, min = 1, max = 9},
	},
	armor = 100,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_eerie",
		death = "mobs_yeti_death",
		attack = "default_punch",
	},
})

mobs:register_mob("es:playerbad22", {
	type = "monster",
	hp_min = 137,
	hp_max = 150,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_22.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 5,
	walk_velocity = 1,
	run_velocity = 3.6,
	damage = 4,
	drops = {
		{name = "default:diamond_block", chance = 4, min = 1, max = 3},
		{name = "default:sword_mese", chance = 2, min = 0, max = 1},
		{name = "default:apple", chance = 2, min = 2, max = 7},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell2",
		death = "mobs_howl",
		attack = "default_punch3",
	},
})

mobs:register_mob("es:playerbad23", {
	type = "monster",
	hp_min = 77,
	hp_max = 130,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_23.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 5,
	walk_velocity = 1,
	run_velocity = 5,
	damage = 4,
	drops = {
		{name = "default:cactus", chance = 5, min = 0, max = 3},
		{name = "default:sword_mese", chance = 2, min = 1, max = 1},
		{name = "default:dirt", chance = 2, min = 6, max = 23},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell2",
		death = "mobs_howl",
		attack = "default_punch3",
	},
})

mobs:register_mob("es:playerbad24", {
	type = "monster",
	hp_min = 35,
	hp_max = 75,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_24.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1.9,
	run_velocity = 3.8,
	damage = 4,
	drops = {
		{name = "default:jungle_trunk", chance = 1, min = 0, max = 2},
		{name = "default:sword_diamond", chance = 2, min = 0, max = 1},
		{name = "default:stick", chance = 2, min = 0, max = 3},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "default_punch",
	},
})

mobs:register_mob("es:Mr_Black", {
	type = "monster",
	hp_min = 35,
	hp_max = 65,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_25.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	attack_monsters = true,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 3,
	damage = 2,
	drops = {
		{name = "default:apple", chance = 1, min = 1, max = 2},
		{name = "default:sword_stone", chance = 2, min = 0, max = 1},
	},
	armor = 75,
	attack_type = "dogfight",
	water_damage = 70,
	lava_damage = 50,
	light_damage = 0,
	fear_height = 5,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "default_punch3",
	},
})

mobs:register_mob("es:Mr_Gray", {
	type = "monster",
	hp_min = 35,
	hp_max = 65,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PG_22.png^PG_22_23_Monster.png^[colorize:gray:90"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	attack_monsters = true,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 3,
	damage = 2,
	drops = {
		{name = "default:apple", chance = 1, min = 1, max = 2},
		{name = "default:sword_bronze", chance = 2, min = 0, max = 1},
	},
	armor = 75,
	attack_type = "dogshoot",
	dogshoot_switch = 1,
	dogshoot_count_max = 10,
	arrow = "es:bullet",
	shoot_interval = 0.12,
	water_damage = 70,
	lava_damage = 50,
	light_damage = 10,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "shooter_rifle",
		shoot_attack = "shooter_rifle",
	},
})

mobs:register_mob("es:Jasmine", {
	type = "monster",
	hp_min = 277,
	hp_max = 290,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_26.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 18,
	walk_velocity = 5,
	run_velocity = 3.4,
	damage = 7,
	drops = {
		{name = "default:diamond", chance = 5, min = 0, max = 2},
		{name = "es:sword_emerald", chance = 7, min = 0, max = 1},
		{name = "flowers:rose", chance = 6, min = 0, max = 1},
	},
	armor = 75,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 70,
	fear_height = 4,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell2",
		death = "mobs_howl",
		attack = "default_punch3",
	},
})

mobs:register_mob("es:Infinium_Monster", {
	type = "monster",
	hp_min = 377,
	hp_max = 390,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_24.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	fly = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 4,
	stepheight = 3,
	fall_speed = 3,
	damage = 5,
	drops = {
		{name = "default:obsidian", chance = 5, min = 3, max = 10},
		{name = "default:sword_diamond", chance = 2, min = 1, max = 1},
		{name = "default:lava_source", chance = 2, min = 1, max = 2},
		{name = "es:infiniumblock", chance = 4, min = 1, max = 2},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 0,
	lava_damage = 0,
	light_damage = 0,
	fear_height = 50,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell2",
		death = "mobs_howl",
		attack = "default_punch3",
	},
})

mobs:register_mob("es:Bajan_m", {
	type = "monster",
	hp_min = 35,
	hp_max = 75,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PG_18.png^PG_18_Monster.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 3,
	damage = 3,
	drops = {
		{name = "default:jungle_trunk", chance = 1, min = 0, max = 2},
		{name = "rangedweapons:tmp", chance = 2, min = 0, max = 1},
		{name = "rangedweapons:9mm", chance = 2, min = 0, max = 3},
	},
	armor = 100,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mummy_death",
		attack = "shooter_pistol",
	},
})

mobs:register_mob("es:Calinou", {
	type = "monster",
	hp_min = 49,
	hp_max = 83,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_28.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 2,
	damage = 3,
	drops = {
		{name = "default:pine_needles", chance = 7, min = 0, max = 5},
		{name = "default:coal_block", chance = 10, min = 1, max = 1},
		{name = "default:apple", chance = 1, min = 1, max = 3},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell2",
		death = "mobs_howl",
		attack = "shooter_pistol",
	},
})

mobs:register_mob("es:John_m", {
	type = "monster",
	hp_min = 37,
	hp_max = 82,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PG_19.png^PG_19_Monster.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 19,
	walk_velocity = 1,
	run_velocity = 3,
	damage = 3,
	drops = {
		{name = "rangedweapons:shell", chance = 2, min =1, max = 10},
		{name = "rangedweapons:rpk", chance = 8, min = 0, max = 1},
		{name = "default:steel_ingot", chance = 2, min = 1, max = 3},
	},
	armor = 100,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "shooter_rifle",
	},
})

mobs:register_mob("es:cx384", {
	type = "monster",
	hp_min = 130,
	hp_max = 140,
	collisionbox = {-.3, 0, -.3, .3, 1.6, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_29.png"}},
	visual_size = {x=.9, y=.9},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 20,
	walk_velocity = 3,
	run_velocity = 4,
	damage = 3,
	drops = {
		{name = "rangedweapons:tmp", chance = 3, min = 0, max = 1},
		{name = "farming:wheat_bread", chance = 3, min = 1, max = 5},
		{name = "default:pine_needles", chance = 2, min = 1, max = 3},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "shooter_pistol",
	},
})

mobs:register_mob("es:FloatingWraith", {
	type = "monster",
	hp_min = 37,
	hp_max = 70,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_31.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1.2,
	run_velocity = 3,
	damage = 3,
	drops = {
		{name = "rangedweapons:benelli_uld", chance = 8, min = 0, max = 1},
		{name = "default:bronze_ingot", chance = 3, min = 0, max = 5},
		{name = "es:magentium_lump", chance = 7, min = 5, max = 9},
	},
	armor = 85,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_stonemonster",
		death = "mobs_yeti_death",
		attack = "shooter_shotgun",
	},
})

mobs:register_mob("es:Ghost", {
	type = "monster",
	hp_min = 157,
	hp_max = 195,
	collisionbox = {-.3, 0, -.3, .3, 1.6, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_32.png"}},
	visual_size = {x=.9, y=.9},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 1.5,
	damage = 3,
	drops = {
		{name = "default:pine_needles", chance = 1, min = 3, max = 13},
		{name = "rangedweapons:hand_grenade", chance = 8, min = 0, max = 10},
		{name = "default:ice", chance = 2, min = 13, max = 30},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 100,
	lava_damage = 0,
	light_damage = 20,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_stonemonster",
		death = "mummy_death",
		attack = "shooter_shotgun",
	},
})

mobs:register_mob("es:Zombie_Rex", {
	type = "monster",
	hp_min = 177,
	hp_max = 190,
	collisionbox = {-.3, 0, -.3, .3, 1.6, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_40.png"}},
	visual_size = {x=.9, y=.9},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 3,
	damage = 3,
	drops = {
		{name = "rangedweapons:benelli_uld", chance = 2, min = 0, max = 1},
		{name = "default:stone_with_diamond", chance = 6, min = 0, max = 3},
		{name = "rangedweapons:diamond_shuriken", chance = 1, min = 1, max = 3},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_stonemonster",
		death = "mummy_death",
		attack = "shooter_shotgun",
	},
})

mobs:register_mob("es:Lovehart", {
	type = "monster",
	hp_min = 157,
	hp_max = 200,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_33.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 10,
	walk_velocity = 4,
	run_velocity =15,
	damage = 4,
	drops = {
		{name = "farming:cotton", chance = 1, min = 3, max = 5},
		{name = "rangedweapons:tmp", chance = 3, min = 0, max = 1},
		{name = "es:griefer_soul", chance = 2, min = 0, max = 1},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_stonemonster",
		death = "mobs_fireball",
		attack = "shooter_pistol",
	},
})

mobs:register_mob("es:Minetestian", {
	type = "monster",
	hp_min = 49,
	hp_max = 85,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PG_23.png^PG_22_23_Monster.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 2,
	damage = 3,
	drops = {
		{name = "default:sapling", chance = 1, min = 3, max = 5},
		{name = "rangedweapons:deagle", chance = 8, min = 0, max = 1},
		{name = "rangedweapons:357", chance = 8, min = 3, max = 10},
	},
	armor = 100,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "shooter_pistol",
	},
})

mobs:register_mob("es:Andromeda", {
	type = "monster",
	hp_min = 57,
	hp_max = 85,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_30.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 25,
	walk_velocity = 0.3,
	run_velocity = 1.5,
	damage = 3,
	drops = {
		{name = "rangedweapons:9mm", chance = 1, min = 3, max = 5},
		{name = "es:sword_aikerum", chance = 5, min = 0, max = 1},
		{name = "rangedweapons:taurus", chance = 4, min = 0, max = 1},
	},
	armor = 100,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "creatures_ghost.2",
		death = "mummy_death",
		attack = "shooter_throw",
	},
})

mobs:register_mob("es:Phil", {
	type = "monster",
	hp_min = 47,
	hp_max = 85,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PG_22.png^PG_22_23_Monster.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 1.4,
	damage = 3,
	drops = {
		{name = "rangedweapons:jackhammer", chance = 1, min = 0, max = 1},
		{name = "default:pine_needles", chance = 8, min = 1, max = 4},
		{name = "rangedweapons:9mm", chance = 2, min = 1, max = 5},
	},
	armor = 90,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "shooter_click",
	},
})

mobs:register_mob("es:IvanbotXD", {
	type = "monster",
	hp_min = 48,
	hp_max = 77,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_34.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 2,
	damage = 3,
	drops = {
		{name = "default:pick_stone", chance = 1, min = 1, max = 3},
		{name = "default:pine_needles", chance = 5, min = 1, max = 4},
		{name = "rangedweapons:9mm", chance = 2, min = 4, max = 8},
	},
	armor = 90,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_eerie",
		death = "mobs_yeti_death",
		attack = "shooter_rifle",
	},
})

mobs:register_mob("es:Orc", {
	type = "monster",
	hp_min = 77,
	hp_max = 90,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_35.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 3,
	run_velocity = 3,
	damage = 4,
	drops = {
		{name = "default:chest", chance = 1, min = 0, max = 1},
		{name = "rangedweapons:tmp", chance = 1, min = 0, max = 1},
		{name = "default:pine_needles", chance = 4, min = 3, max = 5},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_stonemonster",
		death = "mobs_death2",
		attack = "shooter_pistol",
	},
})

mobs:register_mob("es:Luke", {
	type = "monster",
	hp_min = 127,
	hp_max = 152,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_36.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 7,
	walk_velocity = 1.3,
	run_velocity = 3.5,
	damage = 3,
	drops = {
		{name = "default:steel_block", chance = 8, min = 0, max = 2},
		{name = "rangedweapons:beretta", chance = 1, min = 0, max = 1},
		{name = "default:bronze_ingot", chance = 2, min = 1, max = 3},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mummy_death",
		attack = "shooter_pistol",
	},
})

mobs:register_mob("es:Seth_Rollins", {
	type = "monster",
	hp_min = 137,
	hp_max = 159,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_37.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1.5,
	run_velocity = 3,
	damage = 2.5,
	drops = {
		{name = "rangedweapons:taurus", chance = 6, min = 1, max = 4},
		{name = "rangedweapons:tmp", chance = 1, min = 0, max = 1},
		{name = "rangedweapons:9mm", chance = 2, min = 0, max = 3},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell2",
		death = "mobs_barbarian_death",
		attack = "shooter_flare_burn",
	},
})

mobs:register_mob("es:Sgt_Prf", {
	type = "monster",
	hp_min = 100,
	hp_max = 120,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_38.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 12,
	walk_velocity = 2,
	run_velocity = 3,
	damage = 5,
	drops = {
		{name = "rangedweapons:rpk", chance = 2, min = 0, max = 1},
		{name = "rangedweapons:benelli_uld", chance = 1, min = 0, max = 2},
		{name = "default:apple", chance = 2, min = 1, max = 5},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "shooter_rifle",
	},
})

mobs:register_mob("es:Willy_Rex", {
	type = "monster",
	hp_min = 73,
	hp_max = 80,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_39.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 2,
	damage = 3,
	drops = {
		{name = "default:axe_steel", chance = 1, min = 0, max = 2},
		{name = "rangedweapons:9mm", chance = 2, min = 1, max = 3},		
		{name = "rangedweapons:10mm", chance = 2, min = 3, max = 25},
	},
	armor = 90,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_barbarian_yell1",
		death = "mobs_barbarian_death",
		attack = "mobs_slash_attack",
	},
})

mobs:register_mob("es:Zombie_Drogado_A", {
	type = "monster",
	hp_min = 99,
	hp_max = 140,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_40.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 10,
	walk_velocity = 2,
	run_velocity = 4,
	damage = 6,
	drops = {
		{name = "default:pine_needles", chance = 1, min = 3, max = 6},
		{name = "default:apple", chance = 1, min = 1, max = 7},
		{name = "rangedweapons:10mm", chance = 1, min = 1, max = 3},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_stonemonster",
		death = "mummy_death",
		attack = "shooter_shotgun",
	},
})

mobs:register_mob("es:Zombie_Drogado_B", {
	type = "monster",
	hp_min = 77,
	hp_max = 90,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_40.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 25,
	walk_velocity = 0.5,
	run_velocity = 1.5,
	damage = 3,
	drops = {
		{name = "default:obsidian", chance = 6, min = 0, max = 2},
		{name = "default:pine_needles", chance = 1, min = 2, max = 4},
		{name = "default:apple", chance = 2, min = 1, max = 3},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_stonemonster",
		death = "mummy_death",
		attack = "shooter_pistol",
	},
})

mobs:register_mob("es:Zombie_Drogado_C", {
	type = "monster",
	hp_min = 69,
	hp_max = 89,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_40.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1,
	run_velocity = 2,
	damage = 3,
	drops = {
		{name = "default:stone", chance = 1, min = 0, max = 2},
		{name = "default:pine_needles", chance = 3, min = 4, max = 5},
		{name = "rangedweapons:10mm", chance = 2, min = 1, max = 9},
	},
	armor = 100,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_stonemonster",
		death = "mummy_death",
		attack = "shooter_shotgun",
	},
})

mobs:register_mob("es:Zombie_Drogado_D", {
	type = "monster",
	hp_min = 137,
	hp_max = 150,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_40.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 5,
	walk_velocity = 1,
	run_velocity = 5,
	damage = 4,
	drops = {
		{name = "default:diamond", chance = 4, min = 1, max = 3},
		{name = "rangedweapons:tmp", chance = 2, min = 0, max = 1},
		{name = "rangedweapons:10mm", chance = 2, min = 2, max = 7},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_stonemonster",
		death = "mummy_death",
		attack = "shooter_pistol",
	},
})

mobs:register_mob("es:Zombie_Drogado_E", {
	type = "monster",
	hp_min = 97,
	hp_max = 130,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_40.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 5,
	walk_velocity = 1,
	run_velocity = 5,
	damage = 4,
	drops = {
		{name = "default:cactus", chance = 8, min = 0, max = 1},
		{name = "rangedweapons:tmp", chance = 2, min = 1, max = 1},
		{name = "rangedweapons:power_particle", chance = 10, min = 1, max = 3},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_stonemonster",
		death = "mummy_death",
		attack = "shooter_pistol",
	},
})

mobs:register_mob("es:Zombie_Drogado_F", {
	type = "monster",
	hp_min = 35,
	hp_max = 75,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_40.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 1.9,
	run_velocity = 3.8,
	damage = 4,
	drops = {
		{name = "rangedweapons:javelin", chance = 3, min = 0, max = 1},
		{name = "rangedweapons:tmp", chance = 2, min = 0, max = 1},
		{name = "rangedweapons:9mm", chance = 2, min = 0, max = 3},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 100,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		war_cry = "mobs_stonemonster",
		death = "mummy_death",
		attack = "shooter_pistol",
	},
})

mobs:register_mob("es:badbot_fighter", {
	type = "monster",
	hp_min = 60,
	hp_max = 70,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_43.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	jump = true,
	view_range = 15,
	walk_velocity = 3,
	run_velocity = 3.6,
	damage = 3,
	drops = {
		{name = "es:sword_lightsteel_red", chance = 10, min = 0, max = 1},
	},
	armor = 90,
	attack_type = "dogfight",
	water_damage = 1,
	lava_damage = 10,
	light_damage = 100,
	fear_height = 3,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		war_cry = "mobs_stone_attack",
		death = "mummy_death",
		attack = "default_punch",
	},
})

mobs:register_mob("es:badbot_gunner", {
	type = "monster",
	hp_min = 60,
	hp_max = 70,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_44.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	jump = true,
	view_range = 15,
	walk_velocity = 2.7,
	run_velocity = 3.4,
	damage = 3,
	drops = {
		{name = "es:red_laser_gun", chance = 50, min = 0, max = 1},
		{name = "es:laser", chance = 1, min = 2, max = 12},
	},
	armor = 90,
	attack_type = "dogshoot",
	dogshoot_switch = 1,
	dogshoot_count_max = 10,
	arrow = "es:lasershot",
	shoot_interval = 0.5,	
	water_damage = 100,
	lava_damage = 10,
	light_damage = 100,
	fear_height = 3,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		war_cry = "mobs_stone_attack",
		death = "mummy_death",
		attack = "default_punch",
		shoot_attack = "laser_sound",
	},
})

mobs:register_mob("es:claw_alien", {
	type = "monster",
	hp_min = 60,
	hp_max = 70,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "human_model.x",
	textures = {{"PB_41.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	jump = true,
	view_range = 15,
	walk_velocity = 2,
	run_velocity = 3,
	damage = 3,
	drops = {
		{name = "es:claw", chance = 10, min = 0, max = 1},
	},
	armor = 200,
	attack_type = "dogfight",
	water_damage = 6,
	lava_damage = 2,
	light_damage = 100,
	fear_height = 3,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		war_cry = "mobs_stone_attack",
		death = "mummy_death",
		attack = "default_punch",
	},
})

mobs:register_mob("es:alien", {
	type = "monster",
	hp_min = 60,
	hp_max = 70,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "human_model.x",
	textures = {{"PB_1.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	jump = true,
	view_range = 30,
	walk_velocity = 2,
	armor = 100,
	run_velocity = 3,
	damage = 2,
	drops = {
		{name = "es:alien_skin", chance = 1, min = 1, max = 3},
	},
	attack_type = "dogfight",
	water_damage = 2,
	lava_damage = 2,
	light_damage = 100,
	fear_height = 3,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		war_cry = "mobs_stone_attack",
		death = "mummy_death",
		attack = "default_punch",
	},
})

mobs:register_mob("es:destroyed_bot", {
	type = "monster",
   	hp_min = 115,
   	hp_max = 125,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_42.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	jump = true,
	view_range = 12,
	walk_velocity = 1,
	run_velocity = 2,
	damage = 4,
	drops = {
		{name = "default:steel_ingot", chance = 3, min = 1, max = 3},
		{name = "default:copper_ingot", chance = 3, min = 1, max = 3},
	},
	armor = 90,
	attack_type = "dogfight",
	water_damage = 100,
	lava_damage = 10,
	light_damage = 30,
	fear_height = 3,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 79,
		walk_start = 168,
		walk_end = 187,
		run_start = 168,
		run_end = 187,
		punch_start = 189,
		punch_end = 198,
	},
	sounds = {
		war_cry = "mobs_stone_attack",
		death = "mummy_death",
		attack = "default_punch",
	},
})

mobs:register_mob("es:dirtmons", {
	type = "monster",
	hp_min = 30,
	hp_max = 50,
	collisionbox = {-.4, -1, -.4, .4, .9, .4},
	visual = "mesh",
	mesh = "mobs_stone_monster.b3d",
	textures = {{"mobs_dirtmons.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 24,
	walk_velocity = 2.5,
	run_velocity = 3.8,
	damage = 3.7,
	reach = 2,
	drops = {
		{name = "default:dirt", chance = 1, min = 1, max = 1},
		{name = "default:gravel", chance = 1, min = 1, max = 1},
		{name = "default:iron_lump", chance = 1, min = 2, max = 2},
	},
	armor = 75,
	attack_type = "dogfight",
	water_damage = 10,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 6,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
	sounds = {
		war_cry = "mobs_stone",
		death = "mobs_death2",
		attack = "mobs_stone_attack",
	}
})

-- Spider by AspireMint (fishyWET (CC-BY-SA 3.0 license for texture)
mobs:register_mob("es:spider", {
	type = "monster",
	hp_min = 20,
	hp_max = 40,
	collisionbox = {-.3, -.25, -.3, .3, 0, .3},
	visual = "mesh",
	mesh = "mobs_spider.b3d",
	textures = {{"mobs_spider_crystal.png"}},
	visual_size = {x=.5,y=.5},
	makes_footstep_sound = false,
	pathfinding = 1,
	group_attack = true,
	jump = true,
	view_range = 15,
	walk_velocity = 1.7,
	run_velocity = 3.3,
	floats = 0,
	damage = 3,
	reach = 1,
    drops = {
		{name = "mobs:cobweb", chance = 1, min = 1, max = 2},
		{name = "mobs:meat_raw", chance = 1, min = 0, max = 1},
	},
	armor = 100,
	attack_type = "dogfight",
	water_damage = 5,
	lava_damage = 50,
	light_damage = 0,
	fear_height = 7,
	animation = {
		speed_normal = 15,	speed_run = 20,
		stand_start = 0,	stand_end = 0,
		walk_start = 1,		walk_end = 21,
		run_start = 1,		run_end = 21,
		punch_start = 25,	punch_end = 45,
	},
	sounds = {
		random = "mobs_spider",
		attack = "mobs_spider",
	},
	on_spawn = function(self)
		self.object:set_properties({
			collisionbox = {-.3, -.25, -.3, .3, 0, .3}
		})
		return true
	end
})

--Herobrine's Bloody Ghost by Lovehart and Maikerumine  http://minetest.fensta.mobslaced.net/#author=lovehart
mobs:register_mob("es:herobrines_bloody_ghost", {
	type = "monster",
	hp_min = 320,
	hp_max = 340,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"PB_33.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 19,
	walk_velocity = 1.8,
	run_velocity = 3.6,
	damage = 10,
	drops = {
		{name = "default:mese", chance = 7, min = 1, max = 4},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 210,
	lava_damage = 50,
	light_damage = 150,
	fear_height = 30,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 19,
		walk_start = 20,
		walk_end = 35,
		run_start = 30,
		run_end = 40,
		punch_start = 36,
		punch_end = 48,
	}
})

-- Bone Monster by Maikerumine
mobs:register_mob("es:bonemons", {
	type = "monster",
	damage = 2,
	hp_min = 17,
	hp_max = 35,
	armor = 90,
	collisionbox = {-.5, -1.5, -.5, .5, .5, .5},
	visual = "mesh",
	mesh = "flying_block_monster.x",
	textures = {{"mobs_bonemons.png"}},
	visual_size = {x=.9,y=.9},
	blood_texture = "bones_bottom.png",
	makes_footstep_sound = false,
	group_attack = true,
	jump = true,
	jump_height = 8,
	view_range = 15,
	walk_velocity = 1.5,
	run_velocity = 4,
	floats = 1,
	drops = {
		{name = "bones:bones", chance = 1, min = 3, max = 5},
		{name = "default:steel_block", chance = 3, min = 0, max = 2},
		{name = "mobs_animal:chicken_feather", chance = 1, min = 3, max = 9},
	},
	attack_type = "dogshoot",
	dogshoot_switch = 1,
	arrow = "mobs:bonebullet",
	shoot_interval = 1.5,
	shoot_offset = 2,
	water_damage = 4,
	lava_damage = 4,
	light_damage = 4,
	fear_height = 30,
	fall_damage = 0,
	fall_speed = -0.5,
	stepheight = 3,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
	sounds = {random = "default_gravel_footstep"}
})

mobs:register_arrow("mobs:bonebullet", {
	visual = "sprite",
	visual_size = {x = .3, y = .3},
	textures = {"bones_front.png"},
	velocity = 7,

	hit_player = function(self, player)
		player:punch(self.object, 1.0, {
			full_punch_interval = 1.0,
			damage_groups = {fleshy = 4},
		}, nil)
	end,

	hit_mob = function(self, player)
		player:punch(self.object, 1.0, {
			full_punch_interval = 1.0,
			damage_groups = {fleshy = 7},
		}, nil)
	end,
	hit_node = function(self, pos, node)
	end
})

mobs:register_mob("es:icemons", {
	type = "monster",
	hp_min = 80,
	hp_max = 110,
	collisionbox = {-.4, -1, -.4, .4, .9, .4},
	visual = "mesh",
	mesh = "mobs_stone_monster.b3d",
	textures = {{"mobs_icemons.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 14,
	walk_velocity = 2.0,
	run_velocity = 2.9,
	damage = 4,
	drops = {
		{name = "default:ice", chance = 1, min = 3, max = 6},
	},
	armor = 75,
	attack_type = "dogfight",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 30,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 37,
		punch_end = 49,
	},
	sounds = {
		random = "mobs_stonemonster",
	}
})

mobs:register_mob("es:snowmons", {
	type = "monster",
	hp_min = 69,
	hp_max = 112,
	collisionbox = {-.4, -1, -.4, .4, .9, .4},
	visual = "mesh",
	mesh = "mobs_stone_monster.b3d",
	textures = {{"mobs_snowmons.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 14,
	walk_velocity = 1.0,
	run_velocity = 2.0,
	damage = 5,
	drops = {
		{name = "default:snow", chance = 1, min = 3, max = 6},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 20,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 3,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 37,
		punch_end = 49,
	},
	sounds = {
		random = "mobs_stonemonster",
	}
})

mobs:register_mob("es:watermons", {
	type = "monster",
	hp_min = 35,
	hp_max = 75,
	collisionbox = {-.3, 0, -.3, .3, 1.7, .3},
	visual = "mesh",
	mesh = "character.b3d",
	textures = {{"mobs_watermons.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 15,
	walk_velocity = 0.9,
	run_velocity = 1.8,
	damage = 1,
	drops = {
		{name = "default:water_flowing", chance = 1, min = 2, max = 4},
		{name = "bucket:bucket_empty", chance = 8, min = 1, max = 2},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 0,
	lava_damage = 50,
	light_damage = 1,
	fear_height = 3,
	animation = {
		speed_normal = 30,		speed_run = 30,
		stand_start = 0,		stand_end = 79,
		walk_start = 168,		walk_end = 187,
		run_start = 168,		run_end = 187,
		punch_start = 200,		punch_end = 219,
	},
	sounds = {
		random = "mobs_stonemonster",
	}
})

mobs:register_mob("es:blue", {
	type = "monster",
	hp_min = 30,
	hp_max = 50,
	collisionbox = {-.4, -1, -.4, .4, .9, .4},
	visual = "mesh",
	mesh = "mobs_stone_monster.b3d",
	textures = {{"mobs_blue.png"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	view_range = 24,
	walk_velocity = 1.5,
	run_velocity = 2.8,
	damage = 3.7,
	drops = {
		{name = "default:dirt", chance = 1, min = 1, max = 2},
		{name = "flowers:rose", chance = 10, min = 0, max = 1},
	},
	armor = 75,
	attack_type = "dogfight",
	water_damage = 20,
	lava_damage = 40,
	light_damage = 1,
	fear_height = 6,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
	sounds = {
		war_cry = "mobs_stone",
		death = "mobs_death2",
		attack = "mobs_stone_attack",
	}
})

-- Stone Monster by PilzAdam
mobs:register_mob("es:stonemons", {
	type = "monster",
	hp_min = 82,
	hp_max = 105,
	collisionbox = {-.4, -1, -.4, .4, .9, .4},
	visual = "mesh",
	mesh = "mobs_stone_monster.b3d",
	textures = {{"mobs_stone_monster.png^[colorize:#FF0000:130"}},
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	jump = true,
	view_range = 13,
	walk_velocity = 0.5,
	run_velocity = 1.6,
	jump_height = 17,
	fall_damage = 0,
	fall_speed = -13.5,
	floats = 1,
	damage = 6,
	drops = {
		{name = "default:rocks", chance = 2, min = 0, max = 2},
		{name = "default:iron_lump", chance = 5, min = 0, max = 5},
		{name = "default:coal_lump", chance = 3, min = 0, max = 5},
	},
	armor = 80,
	attack_type = "dogfight",
	water_damage = 5,
	lava_damage = 0,
	light_damage = 1,
	fear_height = 33,
	replace_what = {"default:torch"},
	replace_with = "air",
	replace_rate = 5,
	replace_offset = -1,
	animation = {
		speed_normal = 15,		speed_run = 15,
		stand_start = 0,		stand_end = 14,
		walk_start = 15,		walk_end = 38,
		run_start = 40,			run_end = 43,
		punch_start = 43,		punch_end = 43,
	},
	sounds = {
		random = "mobs_stone_attack",
	},
})

mobs:register_mob("es:jack", {
	type = "monster",
	hp_min = 19,
	hp_max = 25,
	collisionbox = {-.75, -.75, -.75, .75, .75, .75},
	visual = "cube",
	textures = {{"default_stone.png^crack_anylength.png", "default_stone.png", "default_stone.png",
		"default_stone.png", "default_stone.png^troll_face.png^[colorize:black:60", "default_stone.png"}},
	visual_size = {x=1.5, y=1.5},
	blood_texture ="default_stone.png",
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	jump = true,
	jump_height = 6,
	view_range = 16,
	walk_velocity = .8,
	run_velocity = 2.6,
	damage = 2,
	reach = 2,
	drops = {
		{name = "default:jungle_leaves", chance = 2, min = 1, max = 1},		
		{name = "default:apple_leaves", chance = 2, min = 1, max = 1},
		{name = "default:stick", chance = 22, min = 1, max = 2},
	},
	armor = 100,
	attack_type = "dogfight",
	water_damage = 0,
	lava_damage = 10,
	light_damage = 0,
	fear_height = 12,
	fall_speed = -4,
	on_die = function(self, pos)
		if not pos then return end
		core.add_entity(pos, "es:jack_junior")
		core.add_entity(pos, "es:jack_junior")
		core.add_entity(pos, "es:jack_junior")
		core.add_entity(pos, "es:jack_junior")
		core.add_entity(pos, "es:jack_junior")
		core.add_entity(pos, "es:jack_junior")
		core.add_entity(pos, "es:jack_junior")
		core.add_entity(pos, "es:jack_junior")
	end
})

mobs:register_mob("es:jack_junior", {
	type = "monster",
	hp_min = 4,
	hp_max = 8,
	collisionbox = {-.375, -.375, -.375, .375, .375, .375},
	visual = "cube",
	textures = {{"default_stone.png^crack_anylength.png", "default_stone.png", "default_stone.png",
		"default_stone.png", "default_stone.png^troll_face.png^[colorize:black:60", "default_stone.png"}},
	visual_size = {x=.75, y=.75},
	blood_texture ="default_stone.png",
	makes_footstep_sound = true,
	pathfinding = 1,
	group_attack = true,
	jump = true,
	jump_height = 3,
	view_range = 16,
	walk_velocity = 2.8,
	run_velocity = 3.1,
	damage = 1,
	reach = 1,
	drops = {
		{name = "default:rocks", chance = 1, min = 1, max = 1},
		{name = "default:gold_lump", chance = 1, min = 1, max = 2},
	},
	armor = 100,
	attack_type = "dogfight",
	water_damage = 0,
	lava_damage = 10,
	light_damage = 0,
	fear_height = 2,
	fall_speed = -4
})


--NOTE: ALWAYS PUT THE REGISTER_SPAWN BELOW THE REGISTER_ENTITY!!!!!

mobs:register_spawn("es:playerbad1", {"default:obsidian", "es:infiniumblock", "es:stone_with_infinium", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 5, -1, 30000, 1, 1000)
mobs:register_spawn("es:playerbad2", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad3", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad4", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad5", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad6", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad7", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad8", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad9", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad10", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad11", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad12", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad13", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad14", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad15", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad16", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad17", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad18", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad19", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad20", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad21", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad22", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad23", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:playerbad24", {"default:sandstone", "default:stone", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, -20)
mobs:register_spawn("es:Mr_Black", {"default:dirt_with_grass", "default:desert_sand", "default:sand", "default:stone_brick", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 4, -1, 30000, 1, 3000)
mobs:register_spawn("es:Mr_Gray", {"default:dirt_with_grass", "default:desert_sand", "default:sand", "default:stone_brick", "default:cobble", "default:dry_dirt", "default:snow"}, 14, -1, 8000, 1, 30)
mobs:register_spawn("es:Jasmine", {"default:obsidian", "es:infiniumblock", "es:stone_with_infinium", "default:cobble", "default:clay_dirt_with_savanna_grass", "es:clay_dirt_with_aiden_grass"}, 7, -1, 30000, 1, -1000)
mobs:register_spawn("es:Infinium_Monster", {"default:obsidian", "default:lava_source", "default:lava_flowing", "es:stone_with_infinium"}, 12, -1, 30000, 3, -1000)

mobs:spawn({
	name = "es:jack",
	nodes = {"default:stone"},
	min_light = 0,
	max_light = 6,
	chance = 3000,
	active_object_count = 2,
	min_height = 0,
	day_toggle = false,
})

mobs:register_spawn("es:Bajan_m", {"decor:floor_ceiling_broken", "default:dirt_with_grass", "default:stone_brick", "default:cobble", "default:dry_dirt", "default:snow", "default:clay_dirt_with_savanna_grass"}, 5, -1, 6000, 1, 31000)
mobs:register_spawn("es:Calinou", {"decor:floor_ceiling_broken", "default:dirt_with_grass", "default:stone_brick", "default:cobble", "default:dry_dirt", "default:snow", "default:clay_dirt_with_savanna_grass"}, 5, -1, 6000, 1, 31000)
mobs:register_spawn("es:John_m", {"decor:floor_ceiling_broken",  "default:sand", "default:silver_sand", "default:desert_sand", "default:snow"}, 5, -1, 6000, 1, 31000)
mobs:register_spawn("es:cx384", {"decor:floor_ceiling_broken", "default:stone", "default:obsidian", "default:clay"}, 5, -1, 6000, 1, 31000)
mobs:register_spawn("es:FloatingWraith", {"decor:floor_ceiling_broken", "default:stone"}, 5, -1, 6000, 1, 31000)
mobs:register_spawn("es:Ghost", {"decor:floor_ceiling_broken", "default:dirt_with_grass"}, 5, -1, 6000, 1, 3250)
mobs:register_spawn("es:Zombie_Rex", {"decor:floor_ceiling_broken", "default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:dry_dirt", "default:snow", "default:clay_dirt_with_savanna_grass"}, 5, -1, 6000, 1, -300)
mobs:register_spawn("es:Lovehart", {"decor:floor_ceiling_broken", "default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:dry_dirt", "default:snow", "default:clay_dirt_with_savanna_grass"}, 5, -1, 6000, 1, -430)
mobs:register_spawn("es:Minetestian", {"decor:floor_ceiling_broken", "default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:dry_dirt", "default:snow", "default:clay_dirt_with_savanna_grass"}, 5, -1, 6000, 1, 100)
mobs:register_spawn("es:Andromeda", {"decor:floor_ceiling_broken", "default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:dry_dirt", "default:snow", "default:clay_dirt_with_savanna_grass"}, 5, -1, 6000, 1, 31000)
mobs:register_spawn("es:Phil", {"decor:floor_ceiling_broken", "default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:dry_dirt", "default:snow", "default:clay_dirt_with_savanna_grass"}, 5, -1, 6000, 1, 31000)
mobs:register_spawn("es:IvanbotXD", {"decor:floor_ceiling_broken", "default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:dry_dirt", "default:snow", "default:clay_dirt_with_savanna_grass"}, 5, -1, 6000, 1, 31000)
mobs:register_spawn("es:Orc", {"decor:floor_ceiling_broken", "default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:dry_dirt", "default:snow", "default:clay_dirt_with_savanna_grass"}, 5, -1, 6000, 1, 31000)
mobs:register_spawn("es:Luke", {"decor:floor_ceiling_broken", "default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:dry_dirt", "default:snow", "default:clay_dirt_with_savanna_grass"}, 5, -1, 6000, 1, -150)
mobs:register_spawn("es:Seth_Rollins", {"decor:floor_ceiling_broken", "default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:dry_dirt", "default:snow", "default:clay_dirt_with_savanna_grass"}, 5, -1, 6000, 1, -400)
mobs:register_spawn("es:Sgt_Prf", {"decor:floor_ceiling_broken", "default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:dry_dirt", "default:snow", "default:clay_dirt_with_savanna_grass"}, 5, -1, 6000, 1, -120)
mobs:register_spawn("es:Willy_Rex", {"decor:floor_ceiling_broken", "default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "default:dry_dirt", "default:snow", "default:clay_dirt_with_savanna_grass"}, 5, -1, 6000, 1, 31000)
mobs:register_spawn("es:Zombie_Drogado_A", {"decor:floor_ceiling_broken", "default:dirt_with_grass", "default:stone_brick", "default:cobble", "default:dry_dirt", "default:snow", "default:clay_dirt_with_savanna_grass"}, 5, -1, 6000, 1, 31000)
mobs:register_spawn("es:Zombie_Drogado_B", {"decor:floor_ceiling_broken", "default:dirt_with_grass", "default:stone_brick", "default:cobble", "default:dry_dirt", "default:snow", "default:clay_dirt_with_savanna_grass"}, 5, -1, 6000, 1, 31000)
mobs:register_spawn("es:Zombie_Drogado_C", {"decor:floor_ceiling_broken", "default:dirt_with_grass", "default:stone_brick", "default:cobble", "default:dry_dirt", "default:snow", "default:clay_dirt_with_savanna_grass"}, 5, -1, 6000, 1, 31000)
mobs:register_spawn("es:Zombie_Drogado_D", {"default:stone", "decor:floor_ceiling_broken"}, 5, -1, 6000, 1, 31000)
mobs:register_spawn("es:Zombie_Drogado_E", {"decor:floor_ceiling_broken", "default:desert_sand"}, 5, -1, 6000, 1, 31000)
mobs:register_spawn("es:Zombie_Drogado_F", {"decor:floor_ceiling_broken", "default:dirt_with_grass", "default:stone", "default:sand", "default:silver_sand", "default:cobble", "default:dry_dirt", "default:snow", "default:clay_dirt_with_savanna_grass"}, 9, -1, 6000, 1, 31000)
mobs:register_spawn("es:badbot_fighter", {"decor:road", "default:clay_dirt_with_savanna_grass"}, 9, -1, 8000, 1, 31000)
mobs:register_spawn("es:badbot_gunner", {"decor:road", "default:clay_dirt_with_savanna_grass"}, 9, -1, 12000, 1, 31000)
mobs:register_spawn("es:claw_alien", {"default:sand", "default:silver_sand", "default:clay"}, 3, -1,25000, 1, 31000)
mobs:register_spawn("es:alien", {"decor:road", "default:desert_sand", "default:silver_sand", "default:sand", "default:clay"}, 5, -1, 12500, 1, 31000)
mobs:register_spawn("es:destroyed_bot", {"default:steel_block", "default:sand", "default:silver_sand", "default:desert_sand", "default:clay"}, 7, -1, 16000, 1, 31000)
mobs:register_spawn("es:spider", {"default:stone" ,"default:cobble"}, 6, -1, 3000, 1, 3000)
mobs:register_spawn("es:herobrines_bloody_ghost", {"default:stone", "default:desert_sand", "nether:brick", "default:bedrock"}, 4, -1, 9000, 1, -6030)
mobs:register_spawn("es:bonemons", {"default:stone_with_iron", "bones:bones", "default:bedrock", "default:stone", "es:clay_dirt_with_aiden_grass"},6, -1, 8000, 1, 3000)
mobs:register_spawn("es:icemons", {"default:cave_ice"}, 5, -1, 18000, 1, 3100)
mobs:register_spawn("es:snowmons", {"default:snow", "default:snow_block", "default:dirt_with_snow"}, 5, -1, 6000, 1, 3000)
mobs:register_spawn("es:watermons", {"default:water_source", "default:water_flowing"}, 5, -1, 18000, 1, -120)
mobs:register_spawn("es:blue", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "es:radia_grass", "es:clay_dirt_with_aiden_grass"}, 5, -1, 6000, 1, -100)
mobs:register_spawn("es:stonemons", {"default:stone", "default:bedrock"}, 5, -1, 8000, 1, -500)
mobs:register_spawn("es:dirtmons", {"default:dirt_with_grass", "default:stone", "default:stone_brick", "default:cobble", "es:radia_grass", "default:dry_dirt"}, 5, -1, 5000, 1, 3000)

--spawn eggs
mobs:register_egg("es:playerbad2", "BP Angry Sam", "PB_2.png", 1)
mobs:register_egg("es:playerbad3", "BP Alien", "PB_3.png", 1)
mobs:register_egg("es:playerbad4", "BP Army Guy", "PB_4.png", 1)
mobs:register_egg("es:playerbad5", "BP Ninja", "PB_5.png", 1)
mobs:register_egg("es:playerbad6", "BP Oerkki", "PB_6.png", 1)
mobs:register_egg("es:playerbad7", "BP Tux", "PB_7.png", 1)
mobs:register_egg("es:playerbad8", "BP Karate Kid", "PB_8.png", 1)
mobs:register_egg("es:playerbad9", "BP Ruthless Attacker", "PB_9.png", 1)
mobs:register_egg("es:playerbad10", "BP Nerd", "PB_10.png", 1)
mobs:register_egg("es:playerbad11", "BP Bob", "PB_11.png", 1)
mobs:register_egg("es:playerbad12", "BP Zombie Sam", "PB_12.png", 1)
mobs:register_egg("es:playerbad13", "BP Unknown Mob", "PB_13.png", 1)
mobs:register_egg("es:playerbad14", "BP Plain Sam", "PB_14.png", 1)
mobs:register_egg("es:playerbad15", "BP Celeron C-55", "PB_15.png", 1)
mobs:register_egg("es:playerbad16", "BP Tux Sam", "PB_16.png", 1)
mobs:register_egg("es:playerbad17", "BP Iron Man", "PB_17.png", 1)
mobs:register_egg("es:playerbad18", "BP Phillip", "PB_18.png", 1)
mobs:register_egg("es:playerbad19", "BP Zack", "PB_19.png", 1)
mobs:register_egg("es:playerbad20", "BP Slenderman", "PB_20.png", 1)
mobs:register_egg("es:playerbad21", "BP Snow Beast", "PB_21.png", 1)
mobs:register_egg("es:playerbad22", "BP Jojoa", "PB_22.png", 1)
mobs:register_egg("es:playerbad23", "BP Cactus man", "PB_23.png", 1)
mobs:register_egg("es:Mr_Black", "BP Mr. Black", "PB_36.png", 1)
mobs:register_egg("es:Mr_Gray", "BP Mr. Gray", "PG_22.png^[colorize:gray:90", 1)
mobs:register_egg("es:Jasmine", "BP Jasmine", "PB_26.png", 1)
mobs:register_egg("es:Infinium_Monster", "BP Infinium Mons", "PB_24.png", 1)
mobs:register_egg("es:spider", "BP Spider", "mobs_spider_crystal.png", 1)
mobs:register_egg("es:bonemons", "BP Bone Monster", "mobs_bonemons.png", 1)
mobs:register_egg("es:jack", "BP Jack", "default_stone.png^default_gold_lump.png^[colorize:black:40", 1)