
mobs:register_mob("es:mese_monster", {
	type = "monster",
	damage = 3,
	attack_type = "dogfight",
	hp_min = 10,
	hp_max = 25,
	armor = 80,
	collisionbox = {-.5, -1.5, -.5, .5, .5, .5},
	visual = "mesh",
	mesh = "flying_block_monster.x",
	textures = {{"zmobs_mese_monster.png"}},
	visual_size = {x=.9,y=.9},
	blood_texture = "default_mese_crystal_fragment.png",
	makes_footstep_sound = false,
	sounds = {random = "mobs_mesemonster", damage = "default_glass_footstep"},
	view_range = 10,
	walk_velocity = 0.5,
	run_velocity = 2,
	jump = true,
	jump_height = 8,
	fall_damage = 0,
	fall_speed = -6,
	stepheight = 2.1,
	drops = {
		{name = "default:mese_crystal", chance = 1, min = 10, max = 10},
		{name = "default:mese_crystal_fragment", chance = 1, min = 7, max = 8},
		{name = "default:obsidian_shard", chance = 1, min = 7, max = 8},
		{name = "mobs:lava_orb", chance = 1, min = 1, max = 1}
	},
	water_damage = 1,
	lava_damage = 1,
	light_damage = 0,
	glow = 3,
	animation = {
		speed_normal = 15,
		speed_run = 15,
		stand_start = 0,
		stand_end = 14,
		walk_start = 15,
		walk_end = 38,
		run_start = 40,
		run_end = 63,
		punch_start = 40,
		punch_end = 63,
	},
})

mobs:register_egg("es:mese_monster", "Old Mese Monster", "default_mese_block.png", 1)
