
local R = {name = "farming:straw", force_place = true}
local S0 = {name = "stairs:stair_straw", force_place = true}
local S1 = {name = "stairs:stair_straw", param2 = 1, force_place = true}
local S2 = {name = "stairs:stair_straw", param2 = 2, force_place = true}
local S3 = {name = "stairs:stair_straw", param2 = 3, force_place = true}
local O0 = {name = "stairs:stair_outer_straw", force_place = true}
local O1 = {name = "stairs:stair_outer_straw", param2 = 1, force_place = true}
local O2 = {name = "stairs:stair_outer_straw", param2 = 2, force_place = true}
local O3 = {name = "stairs:stair_outer_straw", param2 = 3, force_place = true}
if core.get_modpath("mapgen") then
	R = {name = "mapgen:reet", force_place = true}
	S0 = {name = "stairs:stair_reet", force_place = true}
	S1 = {name = "stairs:stair_reet", param2 = 1, force_place = true}
	S2 = {name = "stairs:stair_reet", param2 = 2, force_place = true}
	S3 = {name = "stairs:stair_reet", param2 = 3, force_place = true}
	O0 = {name = "stairs:stair_outer_reet", force_place = true}
	O1 = {name = "stairs:stair_outer_reet", param2 = 1, force_place = true}
	O2 = {name = "stairs:stair_outer_reet", param2 = 2, force_place = true}
	O3 = {name = "stairs:stair_outer_reet", param2 = 3, force_place = true}
end
local D0 = {name = "doors:door_wood_a", force_place = true}
local D1 = {name = "doors:door_wood_a", param2 = 1, force_place = true}
local D2 = {name = "doors:door_wood_a", param2 = 2, force_place = true}
local D3 = {name = "doors:door_wood_a", param2 = 3, force_place = true}
local Hi = {name = "doors:hidden", force_place = true}
local MP = {name = "default:mese_post_light", force_place = true}
local FW = {name = "fabric:block_white", force_place = true}
local F = {name = "default:sandstone", force_place = true}
local W0 = {name = "default:wood", force_place = true}
local B0 = {name = "default:beech_trunk", force_place = true}
local G0 = {name = "xpanes:pane_flat", force_place = true}
local G3 = {name = "xpanes:pane_flat", param2 = 3, force_place = true}
if core.get_modpath("xdecor") then
	G0 = {name = "xpanes:wood_frame_flat", force_place = true}
	G3 = {name = "xpanes:wood_frame_flat", param2 = 3, force_place = true}
end
local F1 = _
local F2 = _
local F3 = _
local BH = _
local BH1 = _
local BH2 = _
local BH3 = _
if core.get_modpath("decor") then
	F1 = {name = "decor:fence_small", param2 = 1, force_place = true}
	F2 = {name = "decor:fence_small", param2 = 2, force_place = true}
	F3 = {name = "decor:fence_small", param2 = 3, force_place = true}
	BH = {name = "decor:bench", force_place = true}
	BH1 = {name = "decor:bench", param2 = 1, force_place = true}
	BH2 = {name = "decor:bench", param2 = 2, force_place = true}
	BH3 = {name = "decor:bench", param2 = 3, force_place = true}
end
local D = {name = "default:dirt", force_place = true}
local G = {name = "default:dirt_with_grass", force_place = true}
local SO = {name = "farming:soil_wet", force_place = true}
local CR = {name = "farming:cucumber_S7", force_place = true}
local FR = {name = "default:fresh_water_source", force_place = true}

house_1 = {size = {x = 9, y = 7, z = 9}, data = {
__,__,__,__,__,__,__,__,__,
SO,SO,SO,SO, F,SO,SO,SO,SO,
CR,CR,CR,CR,__,CR,CR,CR,CR,
__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,

__,__,__,__,__,__,__,__,__,
SO,SO,SO,SO, F,SO,SO,SO,SO,
CR,CR,CR,CR,II,CR,CR,CR,CR,
__,__,MP,II,II,II,MP,__,__,
__,__,S0,S0,S0,S0,S0,__,__,
__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,

__,__,__, F, F, F,__,__,__,
SO,SO, F, F,FW, F, F,SO,SO,
CR,CR,B0,W0,D0,W0,B0,CR,CR,
__,MP,B0,W0,Hi,W0,B0,MP,__,
__,S1,W0,W0,W0,W0,W0,S3,__,
__,__,O1,S0,S0,S0,O0,__,__,
__,__,__,__,__,__,__,__,__,

__,__, F, F, F, F, F,__,__,
SO,SO, F,FW,FW, F, F,SO,SO,
CR,CR,W0,II,II,c1,W0,CR,CR,
__,__,W0,II,II,II,W0,__,__,
__,S1,W0,II,II,II,W0,S3,__,
__,__,S1,W0,W0,W0,S3,__,__,
__,__,__,O1,S0,O0,__,__,__,

__,__, F, F,FR, F, F,__,__,
SO,SO, F,FW,FW,FW, F,SO,SO,
CR,CR,W0,II,II,II,W0,CR,CR,
__,__,G3,II,II,II,G3,__,__,
__,S1,W0,II,{name = "default:meselamp_torch", force_place = true},II,W0,S3,__,
__,__,S1,W0,W0,W0,S3,__,__,
__,__,__,S1, R,S3,__,__,__,

__,__, F, F, F, F, F,__,__,
SO,SO, F, F,FW, F, F,SO,SO,
CR,CR,W0,c0,II,F0,W0,CR,CR,
__,__,W0,II,II,II,W0,__,__,
__,S1,W0,II,II,II,W0,S3,__,
__,__,S1,W0,W0,W0,S3,__,__,
__,__,__,O2,S2,O3,__,__,__,

__,__,__, F, F, F,__,__,__,
SO,SO, F, F, F, F, F,SO,SO,
CR,CR,B0,W0,W0,W0,B0,CR,CR,
__,MP,B0,W0,G0,W0,B0,MP,__,
__,S1,W0,W0,W0,W0,W0,S3,__,
__,__,O2,S2,S2,S2,O3,__,__,
__,__,__,__,__,__,__,__,__,

__,__,__,__,__,__,__,__,__,
SO,SO,SO,SO,SO,SO,SO,SO,SO,
CR,CR,CR,CR,CR,CR,CR,CR,CR,
__,__,MP,__,__,__,MP,__,__,
__,__,S2,S2,S2,S2,S2,__,__,
__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,

__,__,__,__,__,__,__,__,__,
SO,SO,SO,SO,SO,SO,SO,SO,SO,
CR,CR,CR,CR,CR,CR,CR,CR,CR,
__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__}}

CR = {name = "farming:wheat_S8", force_place = true}
field = {size = {x = 9, y = 3, z = 9}, data = {
 D, D, D, D, D, D, D, D, D,
SO,SO,SO,SO,SO,SO,SO,SO,SO,
CR,CR,CR,CR,CR,CR,CR,CR,CR,

 D, D, D, D, D, D, D, D, D,
SO,SO,SO,SO,SO,SO,SO,SO,SO,
CR,CR,CR,CR,CR,CR,CR,CR,CR,

 D, D, D, D, D, D, D, D, D,
SO,SO,SO,SO,SO,SO,SO,SO,SO,
CR,CR,CR,CR,CR,CR,CR,CR,CR,

 D, D, D, D, D, D, D, D, D,
SO,SO,SO,SO,SO,SO,SO,SO,SO,
CR,CR,CR,CR,CR,CR,CR,CR,CR,

 D, D, D, D,FR, D, D, D, D,
SO,SO,SO,SO,SO,SO,SO,SO,SO,
CR,CR,CR,CR,CR,CR,CR,CR,CR,

 D, D, D, D, D, D, D, D, D,
SO,SO,SO,SO,SO,SO,SO,SO,SO,
CR,CR,CR,CR,CR,CR,CR,CR,CR,

 D, D, D, D, D, D, D, D, D,
SO,SO,SO,SO,SO,SO,SO,SO,SO,
CR,CR,CR,CR,CR,CR,CR,CR,CR,

 D, D, D, D, D, D, D, D, D,
SO,SO,SO,SO,SO,SO,SO,SO,SO,
CR,CR,CR,CR,CR,CR,CR,CR,CR,

 D, D, D, D, D, D, D, D, D,
SO,SO,SO,SO,SO,SO,SO,SO,SO,
CR,CR,CR,CR,CR,CR,CR,CR,CR}}

local WA = {name = "default:stone_brick", force_place = true}
local R0 = {name = "stairs:stair_stone_brick", param2 = 20, force_place = true}
local R1 = {name = "stairs:stair_stone_brick", param2 = 21, force_place = true}
local R2 = {name = "stairs:stair_stone_brick", param2 = 22, force_place = true}
local R3 = {name = "stairs:stair_stone_brick", param2 = 23, force_place = true}
local N0 = {name = "stairs:slab_stone_brick", param2 = 20, force_place = true}
local N1 = {name = "stairs:slab_stone_brick", param2 = 21, force_place = true}
local N2 = {name = "stairs:slab_stone_brick", param2 = 22, force_place = true}
local N3 = {name = "stairs:slab_stone_brick", param2 = 23, force_place = true}
local L0 = {name = "stairs:stair_inner_stone_brick", param2 = 20, force_place = true}
local L1 = {name = "stairs:stair_inner_stone_brick", param2 = 21, force_place = true}
local L2 = {name = "stairs:stair_inner_stone_brick", param2 = 22, force_place = true}
local L3 = {name = "stairs:stair_inner_stone_brick", param2 = 23, force_place = true}

cashe = {size = {x = 7, y = 6, z = 7}, data = {
WA,WA,WA,WA,WA,WA,WA,
WA,WA,WA,D0,WA,WA,WA,
WA,WA,WA,Hi,WA,WA,WA,
WA,WA,WA,WA,WA,WA,WA,
WA,WA,WA,WA,WA,WA,WA,
WA,WA,WA,WA,WA,WA,WA,

WA,WA,WA,WA,WA,WA,WA,
WA,C2,C2,II,C2,C2,WA,
WA,C2,C2,II,C2,C2,WA,
WA,C2,C2,C2,C2,C2,WA,
WA,L2,N2,R2,N2,L3,WA,
WA,WA,WA,WA,WA,WA,WA,

WA,WA,WA,WA,WA,WA,WA,
WA,II,II,II,II,II,WA,
WA,II,II,II,II,II,WA,
WA,II,II,II,II,II,WA,
WA,N1,II,II,II,N3,WA,
WA,WA,WA,WA,WA,WA,WA,

WA,WA,WA,WA,WA,WA,WA,
WA,C0,C3,II,C1,C0,WA,
WA,C0,C3,II,C1,C0,WA,
WA,C0,C3,II,C1,C0,WA,
WA,R1,C3,II,C1,R3,WA,
WA,WA,WA,WA,WA,WA,WA,

WA,WA,WA,WA,WA,WA,WA,
WA,II,II,II,II,II,WA,
WA,II,II,II,II,II,WA,
WA,II,II,II,II,II,WA,
WA,N1,II,II,II,N3,WA,
WA,WA,WA,WA,WA,WA,WA,

WA,WA,WA,WA,WA,WA,WA,
WA,C0,C0,C0,C0,C0,WA,
WA,C0,C0,C0,C0,C0,WA,
WA,C0,C0,C0,C0,C0,WA,
WA,L1,N0,R0,N0,L0,WA,
WA,WA,WA,WA,WA,WA,WA,

WA,WA,WA,WA,WA,WA,WA,
WA,WA,WA,WA,WA,WA,WA,
WA,WA,WA,WA,WA,WA,WA,
WA,WA,WA,WA,WA,WA,WA,
WA,WA,WA,WA,WA,WA,WA,
WA,WA,WA,WA,WA,WA,WA}}

local TD = {name = "doors:trapdoor", param2 = 1, force_place = true}
local WB = {name = "default:wrought_iron_block", force_place = true}
local ML = {name = "default:meselamp", force_place = true}
local L5 = {name = "default:ladder_wood", param2 = 5, force_place = true}

bunker = {size = {x = 11, y = 13, z = 11}, data = {
WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,

WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
WB,II,II,II,II,II,II,II,II,II,WB,
WB,II,II,II,II,II,II,II,II,II,WB,
WB,II,II,II,II,II,II,II,II,II,WB,
WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,

WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
WB,II,II,II,II,II,II,II,II,II,WB,
WB,II,II,II,II,II,II,II,II,II,WB,
WB,II,II,II,II,II,II,II,II,II,WB,
WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,

WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
WB,II,II,II,II,II,II,II,II,II,WB,
WB,II,II,II,II,II,II,II,II,II,WB,
WB,II,II,II,II,II,II,II,II,II,WB,
WB,WB,WB,ML,WB,WB,WB,ML,WB,WB,WB,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,

WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
WB,II,II,II,II,II,II,II,II,II,WB,
WB,II,II,II,II,WB,II,II,II,II,WB,
WB,II,II,II,II,WB,II,II,II,II,WB,
WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
__,__,__,__,WB,WB,WB,__,__,__,__,
__,__,__,__,WB,WB,WB,__,__,__,__,
__,__,__,__,WB,WB,WB,__,__,__,__,
__,__,__,__,WB,WB,WB,__,__,__,__,
__,__,__,__,WB,WB,WB,__,__,__,__,
__,__,__,__,WB,WB,WB,__,__,__,__,
__,__,__,__,WB,WB,WB,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,

WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
WB,II,II,II,II,II,II,II,II,II,WB,
WB,II,II,II,II,L5,II,II,II,II,WB,
WB,II,II,II,II,L5,II,II,II,II,WB,
WB,WB,WB,WB,WB,L5,WB,WB,WB,WB,WB,
__,__,__,__,WB,L5,WB,__,__,__,__,
__,__,__,__,WB,L5,WB,__,__,__,__,
__,__,__,__,WB,L5,WB,__,__,__,__,
__,__,__,__,WB,L5,WB,__,__,__,__,
__,__,__,__,WB,L5,WB,__,__,__,__,
__,__,__,__,WB,L5,WB,__,__,__,__,
__,__,__,__,WB,L5,WB,__,__,__,__,
__,__,__,__,__,TD,__,__,__,__,__,

WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
WB,II,II,II,II,II,II,II,II,II,WB,
WB,II,II,II,II,II,II,II,II,II,WB,
WB,II,II,II,II,II,II,II,II,II,WB,
WB,WB,WB,WB,WB,ML,WB,WB,WB,WB,WB,
__,__,__,__,WB,WB,WB,__,__,__,__,
__,__,__,__,WB,WB,WB,__,__,__,__,
__,__,__,__,WB,WB,WB,__,__,__,__,
__,__,__,__,WB,WB,WB,__,__,__,__,
__,__,__,__,WB,WB,WB,__,__,__,__,
__,__,__,__,WB,WB,WB,__,__,__,__,
__,__,__,__,WB,WB,WB,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,

WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
WB,II,II,II,II,II,II,II,II,II,WB,
WB,II,II,II,II,II,II,II,II,II,WB,
WB,II,II,II,II,II,II,II,II,II,WB,
WB,WB,WB,ML,WB,WB,WB,ML,WB,WB,WB,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,

WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
WB,II,II,II,II,II,II,II,II,II,WB,
WB,II,II,II,II,II,II,II,II,II,WB,
WB,II,II,II,II,II,II,II,II,II,WB,
WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,

WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
WB,c0,c0,II,F0,F0,F0,II,c0,c0,WB,
WB,c0,c0,II,II,II,II,II,c0,c0,WB,
WB,c0,c0,II,II,II,II,II,c0,c0,WB,
WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,

WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,WB,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__,
__,__,__,__,__,__,__,__,__,__,__}}

local W = {name = "default:water_source", force_place = true}
local f = FR
local l = {name = "default:fresh_water_flowing", param2 = 15, force_place = true}
local a = {name = "default:aspen_wood", force_place = true}
local b = {name = "stairs:slab_aspen_wood", force_place = true}
local h = {name = "stairs:slab_aspen_wood", param2 = 20, force_place = true}
local j = {name = "stairs:slab_sandstone", force_place = true}

fountain_well = {size = {x = 11, y = 8, z = 11}, data = {
D,D,D,D,D,D,D,D,D,D,D,
j,j,j,j,j,j,j,j,j,j,j,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,

D,F,F,F,F,F,F,F,F,F,D,
j,F,F,F,F,F,F,F,F,F,j,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,

D,F,F,F,F,F,F,F,F,F,D,
j,F,W,W,W,W,W,W,W,F,j,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,{name = "default:meselamp_torch_wall", param2 = 4, force_place = true},_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,

D,F,F,F,F,F,F,F,F,F,D,
j,F,W,f,f,f,f,f,W,F,j,
_,_,_,_,l,_,l,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,h,_,_,_,_,_,
_,_,_,_,_,b,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,

D,F,F,F,F,F,F,F,F,F,D,
j,F,W,f,f,f,f,f,W,F,j,
_,_,_,l,l,l,l,l,_,_,_,
_,_,_,_,l,_,l,_,_,_,_,
_,_,_,_,l,a,l,_,_,_,_,
_,_,_,_,l,l,l,_,_,_,_,
_,_,_,_,_,l,_,_,_,_,_,
_,_,_,_,_,l,_,_,_,_,_,

D,F,F,F,F,F,F,F,F,F,D,
j,F,W,f,f,a,f,f,W,F,j,
_,_,_,_,l,a,l,_,_,_,_,
_,_,_,_,_,a,_,_,_,_,_,
_,_,_,h,a,a,a,h,_,_,_,
_,_,{name = "default:meselamp_torch_wall", param2 = 2, force_place = true},b,l,a,l,b,{name = "default:meselamp_torch_wall", param2 = 3, force_place = true},_,_,
_,_,_,_,l,a,l,_,_,_,_,
_,_,_,_,l,f,l,_,_,_,_,

D,F,F,F,F,F,F,F,F,F,D,
j,F,W,f,f,f,f,f,W,F,j,
_,_,_,l,l,l,l,l,_,_,_,
_,_,_,_,l,_,l,_,_,_,_,
_,_,_,_,l,a,l,_,_,_,_,
_,_,_,_,l,l,l,_,_,_,_,
_,_,_,_,_,l,_,_,_,_,_,
_,_,_,_,_,l,_,_,_,_,_,

D,F,F,F,F,F,F,F,F,F,D,
j,F,W,f,f,f,f,f,W,F,j,
_,_,_,_,l,_,l,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,h,_,_,_,_,_,
_,_,_,_,_,b,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,

D,F,F,F,F,F,F,F,F,F,D,
j,F,W,W,W,W,W,W,W,F,j,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,{name = "default:meselamp_torch_wall", param2 = 5, force_place = true},_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,

D,F,F,F,F,F,F,F,F,F,D,
j,F,F,F,F,F,F,F,F,F,j,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,

D,D,D,D,D,D,D,D,D,D,D,
j,j,j,j,j,j,j,j,j,j,j,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_}}

local co = {name = "stairs:slab_cobble", force_place = true}
local CO = {name = "default:cobble", force_place = true}

tree_place = {size = {x = 7, y = 2, z = 7}, data = {
I,I,co,co,co,I,I,
I,I,I,I,I,I,I,

I,co,CO,CO,CO,co,I,
I,I,I,BH,I,I,I,

co,CO,G,G,G,CO,co,
I,I,I,I,I,I,I,

co,CO,G,G,G,CO,co,
I,BH1,I,{name = "default:apple_sapling", force_place = true},I,BH3,I,

co,CO,G,G,G,CO,co,
I,I,I,I,I,I,I,

I,co,CO,CO,CO,co,I,
I,I,I,BH2,I,I,I,

I,I,co,co,co,I,I,
I,I,I,I,I,I,I}}

local b = {name = "farming:straw_bale", force_place = true}
local c = {name = "farming:straw_bale", prob = 150, force_place = true}

bale_pile = {size = {x = 5, y = 4, z = 5}, data = {
G,G,G,G,G,
F1,c,b,c,F3,
_,_,c,_,_,
_,_,_,_,_,

G,G,G,G,G,
F1,b,b,b,F3,
_,c,b,c,_,
_,_,c,_,_,

G,G,G,G,G,
F1,b,b,b,F3,
_,c,b,c,_,
_,_,c,_,_,

G,G,G,G,G,
F1,b,b,b,F3,
_,c,b,c,_,
_,_,_,_,_,

G,G,G,G,G,
_,F2,F2,F2,_,
_,_,_,_,_,
_,_,_,_,_}}

if core.get_modpath("decor") then
benches = {size = {x = 5, y = 2, z = 5}, data = {
G,G,G,G,G,
_,_,_,_,_,

G,G,G,G,G,
_,BH,BH,BH,_,

G,G,G,G,G,
_,{name = "decor:small_table", force_place = true},{name = "decor:small_table", force_place = true},{name = "decor:small_table", force_place = true},_,

G,G,G,G,G,
_,BH2,BH2,BH2,_,

G,G,G,G,G,
_,_,_,_,_}}
end

chest_tower = {size = {x = 2, y = 4, z = 2}, data = {
c1,c0,
c1,c0,
c1,c0,
c1,c0,

c2,c3,
c2,c3,
c2,c3,
c2,c3}}

local A = {name = "default:ice", force_place = true}
local B = {name = "default:ice_brick", force_place = true}
local C = {name = "default:snow_block", force_place = true}
local D = {name = "default:snow_brick", force_place = true}
local E = {name = "default:crystal_block", force_place = true}
F = {name = "default:crystal_spike", force_place = true}
local G = I
local N = I
if core.get_modpath("mapgen") then
	G = {name = "mapgen:ice_spike", force_place = true}
	N = {name = "mapgen:ice_waterfall", force_place = true}
end
local H = {name = "stairs:slab_snow_block", force_place = true}
W = {name = "stairs:stair_snow_block", force_place = true}
local X = {name = "stairs:stair_snow_block", param2 = 1, force_place = true}
local Y = {name = "stairs:stair_snow_block", param2 = 2, force_place = true}
local Z = {name = "stairs:stair_snow_block", param2 = 3, force_place = true}
local J = {name = "stairs:slab_ice", force_place = true}
local T = {name = "stairs:stair_ice", force_place = true}
local d = {name = "doors:door_ice_a", force_place = true}

ice_castle = {size = {x = 29, y = 27, z = 29}, data = {
_,_,_,_,_,_,_,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,B,D,B,B,B,D,B,D,B,B,B,D,B,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,D,B,B,B,D,B,B,B,D,B,B,B,D,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,D,B,B,B,D,B,B,B,B,B,D,B,B,B,D,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,B,B,D,B,B,C,C,C,B,B,D,B,B,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,B,D,B,B,C,_,_,_,C,B,B,D,B,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,B,B,B,C,_,_,_,_,_,C,B,B,B,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,C,C,C,_,_,_,_,_,_,_,C,C,C,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,_,_,_,_,C,C,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,C,C,_,_,_,_,_,
_,_,_,_,_,_,_,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,d,I,I,I,I,I,I,I,I,I,I,I,I,I,d,_,_,_,_,_,_,_,
_,_,_,_,_,_,H,B,I,I,I,B,I,I,I,I,I,B,I,I,I,B,H,_,_,_,_,_,_,
_,_,_,_,_,_,_,D,I,I,I,B,B,B,B,B,B,B,I,I,I,D,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,I,I,I,B,B,C,A,C,B,B,I,I,I,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,B,B,B,B,C,_,_,_,C,B,B,B,B,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,C,B,C,C,_,_,_,_,_,C,C,B,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,H,C,H,_,_,_,_,_,_,_,H,C,H,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,_,_,C,C,C,C,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,C,C,C,C,_,_,_,
_,_,_,_,_,_,_,I,I,I,I,B,I,I,I,I,I,B,I,I,I,I,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,d,I,I,I,B,I,I,I,I,I,B,I,I,I,d,_,_,_,_,_,_,_,
_,_,_,_,_,_,H,B,I,I,I,B,I,I,I,I,I,B,I,I,I,B,H,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,I,I,I,B,B,B,B,B,B,B,I,I,I,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,D,I,I,I,B,B,C,A,C,B,B,I,I,I,D,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,B,I,B,B,C,_,_,_,C,B,B,I,B,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,B,B,B,C,_,_,_,_,_,C,B,B,B,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,C,C,C,_,_,_,_,_,_,_,C,C,C,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,_,C,C,C,C,C,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,C,C,C,C,C,_,_,
_,_,_,_,_,_,_,B,G,I,F,B,I,I,I,I,I,B,F,I,G,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,I,I,I,B,I,I,I,I,I,B,I,I,I,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,I,I,I,B,I,I,I,I,I,B,I,I,I,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,I,I,I,B,I,I,I,I,I,B,I,I,I,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,I,I,I,B,B,B,B,B,B,B,I,I,I,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,B,B,B,B,C,A,C,A,C,B,B,B,B,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,C,B,C,C,_,_,_,_,_,C,C,B,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,H,C,H,_,_,_,_,_,_,_,H,C,H,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,_,C,C,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,C,C,_,_,
_,_,_,_,A,B,B,B,B,B,B,B,G,I,I,I,G,B,B,B,B,B,B,B,A,_,_,_,_,
_,_,_,_,A,B,B,B,B,B,B,B,I,I,I,I,I,B,B,B,B,B,B,B,A,_,_,_,_,
_,_,_,_,A,A,B,B,B,B,B,B,I,I,I,I,I,B,B,B,B,B,B,A,A,_,_,_,_,
_,_,_,_,_,A,B,B,B,B,B,B,I,I,I,I,I,B,B,B,B,B,B,A,_,_,_,_,_,
_,_,_,_,_,A,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,A,_,_,_,_,_,
_,_,_,_,_,_,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,_,_,_,_,_,_,
_,_,_,_,_,_,A,C,C,C,C,A,C,A,A,A,C,A,C,C,C,C,A,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,C,C,C,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,C,C,C,_,
_,_,_,_,B,B,B,B,B,B,B,B,B,B,I,B,B,B,B,B,B,B,B,B,B,_,_,_,_,
_,_,_,_,B,B,B,B,B,B,B,B,B,B,I,B,B,B,B,B,B,B,B,B,B,_,_,_,_,
_,_,_,_,A,B,B,B,B,B,B,B,B,B,I,B,B,B,B,B,B,B,B,B,A,_,_,_,_,
_,_,_,_,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,_,_,_,_,
_,_,_,_,A,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,A,_,_,_,_,
_,_,_,_,_,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,_,_,_,_,_,
_,_,_,_,_,A,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,A,_,_,_,_,_,
_,_,_,_,_,_,A,C,C,C,C,C,C,A,C,A,C,C,C,C,C,C,A,_,_,_,_,_,_,
_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,C,_,_,_,A,_,_,_,A,_,_,_,C,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,_,A,_,_,_,_,_,_,_,_,_,A,_,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,C,C,C,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,C,C,C,_,
_,_,_,_,B,B,F,Z,I,I,I,I,I,G,I,G,I,I,I,I,I,I,F,B,B,_,_,_,_,
_,_,_,_,B,B,Z,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,Y,B,B,_,_,_,_,
_,H,H,_,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,Z,I,B,B,_,H,H,_,
_,_,_,_,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,Z,I,I,B,B,_,_,_,_,
_,_,_,_,A,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,A,_,_,_,_,
_,_,_,_,A,B,B,B,B,B,B,I,I,I,I,I,I,I,B,B,I,I,B,B,A,_,_,_,_,
_,_,_,_,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,I,A,A,A,A,_,_,_,_,
_,_,_,_,_,A,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,A,_,_,_,_,_,
_,_,_,_,_,A,A,B,N,B,D,B,N,D,B,D,N,B,D,B,N,B,A,A,_,_,_,_,_,
_,_,_,_,_,_,A,B,N,D,B,B,N,B,D,B,N,B,B,D,N,B,A,_,_,_,_,_,_,
_,_,_,_,_,_,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,_,_,_,_,_,_,
_,_,_,_,_,_,B,D,B,B,B,H,H,J,H,J,H,H,B,B,B,D,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,B,D,B,B,_,_,_,_,_,_,_,B,B,D,B,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,B,B,D,B,_,_,_,_,_,_,_,B,D,B,B,B,_,_,_,_,_,_,
_,_,_,_,_,_,D,B,N,B,D,_,_,_,_,_,_,_,D,B,N,B,D,_,_,_,_,_,_,
_,_,_,_,_,_,B,B,N,B,B,_,_,_,_,_,_,_,B,B,N,B,B,_,_,_,_,_,_,
_,_,_,_,_,_,A,B,D,B,A,_,_,_,_,_,_,_,A,B,D,B,A,_,_,_,_,_,_,
_,_,_,_,_,_,H,A,B,A,_,_,_,_,_,_,_,_,_,A,B,A,H,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,
B,I,I,B,B,B,I,I,F,I,I,I,F,I,I,I,F,I,I,I,F,I,Y,B,B,B,I,I,B,
B,d,d,B,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,B,d,d,B,
D,B,B,B,B,B,W,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,B,B,B,D,
B,D,B,B,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,B,B,D,B,
B,B,D,B,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,W,I,I,B,B,B,D,B,B,
C,B,B,B,B,B,I,Y,C,I,I,I,C,I,I,I,C,I,I,I,I,X,B,B,B,B,B,B,C,
_,C,C,C,C,B,A,I,X,A,A,A,A,A,A,A,A,A,A,A,I,I,A,B,C,C,C,C,_,
_,_,_,_,_,C,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,C,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,B,B,B,B,B,B,B,B,B,Y,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,D,I,I,I,B,C,C,C,A,C,C,C,B,I,X,I,D,_,_,_,_,_,_,
_,_,_,_,_,_,B,Y,I,I,B,_,_,_,_,_,_,_,B,I,I,X,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,X,B,D,_,_,_,_,_,_,_,D,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,B,_,_,_,_,_,_,_,B,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,A,B,I,I,I,B,A,_,_,_,_,_,A,B,I,I,I,B,A,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,B,_,_,_,_,_,_,_,B,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,A,I,I,I,A,_,_,_,_,_,_,_,A,I,I,I,A,_,_,_,_,_,_,
_,_,_,_,_,_,A,A,I,A,A,_,_,_,_,_,_,_,A,A,I,A,A,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,I,A,_,_,_,_,_,_,_,_,_,A,I,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,H,A,_,_,_,_,_,_,_,_,_,_,_,A,H,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,
B,I,I,G,B,B,I,F,A,F,I,F,A,F,I,F,A,F,I,F,A,F,I,B,B,G,I,I,B,
D,I,I,I,B,B,I,I,A,I,I,I,A,I,I,I,A,I,I,I,A,I,I,B,B,I,I,I,D,
B,I,I,I,B,B,I,I,A,I,I,I,A,I,I,I,A,I,I,I,A,I,I,B,B,I,I,I,B,
B,I,I,I,B,B,W,I,A,I,I,I,A,I,I,I,A,I,I,I,A,I,I,B,B,I,I,I,B,
B,I,I,I,B,B,I,X,A,I,I,I,A,I,I,I,A,I,I,I,A,I,I,B,B,I,I,I,B,
B,B,B,B,B,B,I,I,A,C,I,C,A,C,I,C,A,C,I,C,A,C,B,B,B,B,B,B,B,
C,C,B,C,C,B,I,I,A,A,A,A,A,A,A,A,A,A,A,A,A,W,A,B,C,C,B,C,C,
_,H,C,H,_,C,B,I,I,W,B,B,B,B,I,B,B,B,B,I,I,I,B,C,_,H,C,H,_,
_,_,_,_,_,_,N,I,I,I,B,B,B,B,I,B,B,B,B,I,I,I,N,_,_,_,_,_,_,
_,_,_,_,_,_,N,I,I,I,B,B,B,B,I,B,B,B,B,Y,I,I,N,_,_,_,_,_,_,
_,_,_,_,_,C,B,I,I,I,B,B,B,B,B,B,B,B,B,I,I,I,B,C,_,_,_,_,_,
_,_,_,_,_,_,B,Y,I,I,B,C,C,A,B,A,C,C,B,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,D,I,I,I,B,_,_,_,A,_,_,_,B,I,I,I,D,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,B,B,B,_,_,_,_,_,_,_,B,B,B,W,B,_,_,_,_,_,_,
_,_,_,_,_,_,N,I,I,I,B,_,_,_,_,_,_,_,B,I,I,I,N,_,_,_,_,_,_,
_,_,_,_,_,_,N,I,I,I,B,_,_,_,_,_,_,_,B,I,I,I,N,_,_,_,_,_,_,
_,_,_,_,_,_,D,I,I,I,B,_,_,_,_,_,_,_,B,I,I,I,D,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,B,_,_,_,_,_,_,_,B,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,A,I,I,I,A,_,_,_,_,_,_,_,A,I,I,I,A,_,_,_,_,_,_,
_,_,_,_,_,_,A,I,I,I,A,_,_,_,_,_,_,_,A,I,I,I,A,_,_,_,_,_,_,
_,_,_,_,_,_,A,A,I,A,A,_,_,_,_,_,_,_,A,A,I,A,A,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,I,A,_,_,_,_,_,_,_,_,_,A,I,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,I,A,_,_,_,_,_,_,_,_,_,A,I,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,

A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,
D,I,I,I,B,B,I,I,F,I,I,I,F,I,I,I,F,I,I,I,F,I,I,B,B,I,I,I,D,
B,I,I,I,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,I,I,I,B,
B,I,I,I,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,I,I,I,B,
B,I,I,I,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,I,I,I,B,
D,I,I,I,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,I,I,I,D,
B,B,I,B,B,B,B,I,C,I,I,I,C,I,I,I,C,I,I,I,C,I,B,B,B,B,I,B,B,
C,B,B,B,C,B,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,B,C,B,B,B,C,
_,C,C,C,_,C,B,I,I,F,B,I,B,B,I,B,B,I,B,F,Z,I,B,C,_,C,C,C,_,
_,_,_,_,_,_,B,I,I,W,B,I,B,B,I,B,B,I,B,Z,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,D,I,Z,I,B,I,B,B,I,B,B,I,B,I,I,I,D,_,_,_,_,_,_,
_,_,_,_,_,_,B,Z,I,I,B,I,B,B,B,B,B,I,B,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,B,A,B,B,B,B,B,A,B,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,B,A,B,B,B,B,B,A,B,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,D,I,B,B,B,_,B,D,B,D,B,_,B,B,B,B,D,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,F,B,_,C,B,B,B,C,_,B,F,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,A,B,I,I,I,B,_,_,C,A,C,_,_,B,I,I,I,B,A,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,B,_,_,_,_,_,_,_,B,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,A,I,I,I,A,_,_,_,_,_,_,_,A,I,I,I,A,_,_,_,_,_,_,
_,_,_,_,_,_,A,A,I,A,A,_,_,_,_,_,_,_,A,A,I,A,A,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,I,A,_,_,_,_,_,_,_,_,_,A,I,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,A,H,_,_,_,_,_,_,_,_,_,H,A,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,
B,I,I,F,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,F,I,I,B,
B,I,I,I,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,I,I,I,B,
B,I,I,I,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,I,I,I,B,
D,I,I,I,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,I,I,I,D,
B,I,I,I,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,I,I,I,B,
B,B,B,B,B,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,B,B,B,B,B,
C,C,B,C,C,B,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,B,C,C,B,C,C,
_,H,C,H,_,C,B,I,B,B,B,B,A,I,I,I,A,B,B,B,B,I,B,C,_,H,C,H,_,
_,_,_,_,_,_,D,I,B,B,B,B,A,I,I,I,A,B,B,B,B,I,D,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,B,B,B,B,A,I,I,I,A,B,B,B,B,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,B,B,B,B,B,A,I,I,I,A,B,B,B,B,B,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,B,B,B,B,B,A,I,I,I,A,B,B,B,B,B,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,B,B,B,B,B,A,A,I,A,A,B,B,B,B,B,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,D,B,B,B,B,B,A,A,A,B,B,B,B,B,D,B,_,_,_,_,_,_,
_,_,_,_,_,_,D,B,B,B,B,B,B,B,A,B,B,B,B,B,B,B,D,_,_,_,_,_,_,
_,_,_,_,_,_,B,B,B,B,B,A,B,B,B,B,B,A,B,B,B,B,B,_,_,_,_,_,_,
_,_,_,_,_,_,A,B,B,B,A,_,C,A,C,A,C,_,A,B,B,B,A,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,B,A,_,_,_,_,_,_,_,_,_,A,B,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,
B,I,B,B,B,B,I,I,F,I,I,I,F,I,I,I,F,I,I,I,F,I,I,B,B,B,B,I,B,
B,I,B,B,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,B,B,I,B,
D,B,B,B,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,B,B,B,D,
B,B,B,B,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,B,B,B,B,
B,B,B,B,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,B,B,B,B,
C,B,B,B,B,B,I,I,C,I,I,I,C,I,I,I,C,I,I,I,C,I,I,B,B,B,B,B,C,
_,C,C,C,A,B,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,B,A,C,C,C,_,
_,_,_,_,_,C,B,I,B,I,B,G,F,I,I,I,F,G,B,I,B,I,B,C,_,_,_,_,_,
_,_,_,_,_,_,B,I,B,I,B,I,I,I,I,I,I,I,B,I,B,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,B,I,B,I,I,I,I,I,I,I,B,I,B,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,B,B,I,B,I,I,I,I,I,I,I,B,I,B,B,B,_,_,_,_,_,_,
_,_,_,_,_,_,H,C,C,A,B,I,I,I,I,I,I,I,B,A,C,C,H,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,A,B,I,I,I,I,I,I,I,B,A,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,B,I,I,I,I,I,I,I,B,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,B,A,I,I,I,I,I,A,B,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,_,_,A,A,A,I,I,I,A,A,A,_,_,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,A,A,B,B,B,A,A,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,A,C,C,C,A,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,
B,I,I,I,G,B,I,F,A,F,I,F,A,F,I,F,A,F,I,F,A,F,I,B,G,I,I,I,B,
D,I,I,I,I,B,I,I,A,I,I,I,A,I,I,I,A,I,I,I,A,I,I,B,I,I,I,I,D,
B,I,I,I,I,B,I,I,A,I,I,I,A,I,I,I,A,I,I,I,A,I,I,B,I,I,I,I,B,
B,B,B,I,I,B,I,I,A,I,I,I,A,I,I,I,A,I,I,I,A,I,I,B,I,I,B,B,B,
C,B,B,B,B,B,I,I,A,I,I,I,A,I,I,I,A,I,I,I,A,I,I,B,B,B,B,B,C,
_,C,C,C,B,B,I,C,A,C,I,C,A,C,I,C,A,C,I,C,A,C,I,B,B,C,C,C,_,
_,_,_,_,C,B,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,B,C,_,_,_,_,
_,_,_,_,_,C,B,I,B,B,A,F,I,I,H,I,I,F,A,B,B,I,B,C,_,_,_,_,_,
_,_,_,_,_,_,N,I,B,B,A,I,I,I,I,I,I,I,A,B,B,I,N,_,_,_,_,_,_,
_,_,_,_,_,_,N,I,B,B,A,I,I,I,I,I,I,I,A,B,B,I,N,_,_,_,_,_,_,
_,_,_,_,_,A,B,B,B,B,A,I,I,I,I,I,I,I,A,B,B,B,B,A,_,_,_,_,_,
_,_,_,_,_,_,H,C,C,B,A,I,I,I,I,I,I,I,A,B,C,C,H,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,B,A,I,I,I,I,I,I,I,A,B,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,B,B,I,I,I,I,I,I,I,B,B,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,C,B,I,I,I,I,I,I,I,B,C,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,B,A,I,I,I,I,I,A,B,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,C,A,A,I,I,I,A,A,C,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,A,A,A,C,A,A,A,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,A,I,A,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,
D,I,I,I,I,B,G,I,F,I,I,I,F,I,I,I,F,I,I,I,F,I,G,B,I,I,I,I,D,
B,I,I,I,I,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,I,I,I,I,B,
B,I,I,I,I,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,I,I,I,I,B,
C,B,B,I,I,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,I,I,B,B,C,
_,C,C,B,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,B,C,C,_,
_,_,_,A,B,B,I,I,C,I,I,I,C,I,I,I,C,I,I,I,C,I,I,B,B,A,_,_,_,
_,_,_,_,A,B,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,B,A,_,_,_,_,
_,_,_,_,_,A,B,I,B,B,I,I,I,H,A,H,I,I,I,B,B,I,B,A,_,_,_,_,_,
_,_,_,_,_,_,D,I,B,B,I,I,I,I,I,I,I,I,I,B,B,I,D,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,B,B,I,I,I,I,I,I,I,I,I,B,B,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,B,B,B,I,I,I,I,I,I,I,I,I,B,B,B,B,_,_,_,_,_,_,
_,_,_,_,_,_,J,C,A,B,I,I,I,I,I,I,I,I,I,B,A,C,J,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,B,A,I,I,I,I,I,I,I,A,B,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,D,A,I,I,I,I,I,I,I,A,D,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,B,B,I,I,I,I,I,I,I,B,B,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,C,B,I,I,I,I,I,I,I,B,C,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,A,B,I,I,I,I,I,B,A,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,C,A,I,I,I,A,C,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,A,A,I,A,A,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,
B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,
B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,
B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,
C,B,B,I,I,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,I,I,B,B,C,
_,A,A,B,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,B,A,A,_,
_,_,_,C,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,C,_,_,_,
_,_,_,_,A,B,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,B,A,_,_,_,_,
_,_,_,_,_,C,B,I,I,I,I,I,H,A,A,A,H,I,I,I,I,I,B,C,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,I,I,I,I,T,I,I,I,I,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,D,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,D,_,_,_,_,_,_,
_,_,_,_,_,_,B,B,B,B,I,I,I,I,I,I,I,I,I,B,B,B,B,_,_,_,_,_,_,
_,_,_,_,_,_,H,A,B,B,I,I,I,I,I,I,I,I,I,B,B,A,H,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,A,B,I,I,I,I,I,I,I,I,I,B,A,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,B,A,I,I,I,I,I,I,I,A,B,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,B,A,I,I,I,I,I,I,I,A,B,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,A,B,I,I,I,I,I,I,I,B,A,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,C,B,I,I,I,I,I,B,C,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,C,C,I,I,I,C,C,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,I,I,E,I,I,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,
D,I,I,I,I,B,G,I,F,I,I,I,F,I,I,I,F,I,I,I,F,I,G,B,I,I,I,I,D,
B,I,I,I,I,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,I,I,I,I,B,
B,I,I,I,I,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,I,I,I,I,B,
C,B,B,I,I,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,I,I,B,B,C,
_,C,C,B,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,B,C,C,_,
_,_,_,A,B,B,I,I,C,I,I,I,C,I,I,I,C,I,I,I,C,I,I,B,B,A,_,_,_,
_,_,_,_,A,B,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,B,A,_,_,_,_,
_,_,_,_,_,A,B,I,B,B,I,I,I,H,A,H,I,I,I,B,B,I,B,A,_,_,_,_,_,
_,_,_,_,_,_,D,I,B,B,I,I,I,I,I,I,I,I,I,B,B,I,D,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,B,B,I,I,I,I,I,I,I,I,I,B,B,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,B,B,B,I,I,I,I,I,I,I,I,I,B,B,B,B,_,_,_,_,_,_,
_,_,_,_,_,_,J,C,A,B,I,I,I,I,I,I,I,I,I,B,A,C,J,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,B,A,I,I,I,I,I,I,I,A,B,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,D,A,I,I,I,I,I,I,I,A,D,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,B,B,I,I,I,I,I,I,I,B,B,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,C,B,I,I,I,I,I,I,I,B,C,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,A,B,I,I,I,I,I,B,A,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,C,A,I,I,I,A,C,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,A,A,I,A,A,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,
B,I,I,I,G,B,I,F,A,F,I,F,A,F,I,F,A,F,I,F,A,F,I,B,G,I,I,I,B,
D,I,I,I,I,B,I,I,A,I,I,I,A,I,I,I,A,I,I,I,A,I,I,B,I,I,I,I,D,
B,I,I,I,I,B,I,I,A,I,I,I,A,I,I,I,A,I,I,I,A,I,I,B,I,I,I,I,B,
B,B,B,I,I,B,I,I,A,I,I,I,A,I,I,I,A,I,I,I,A,I,I,B,I,I,B,B,B,
C,B,B,B,B,B,I,I,A,I,I,I,A,I,I,I,A,I,I,I,A,I,I,B,B,B,B,B,C,
_,C,C,C,B,B,I,C,A,C,I,C,A,C,I,C,A,C,I,C,A,C,I,B,B,C,C,C,_,
_,_,_,_,C,B,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,B,C,_,_,_,_,
_,_,_,_,_,C,B,I,B,B,A,F,I,I,H,I,I,F,A,B,B,I,B,C,_,_,_,_,_,
_,_,_,_,_,_,N,I,B,B,A,I,I,I,I,I,I,I,A,B,B,I,N,_,_,_,_,_,_,
_,_,_,_,_,_,N,I,B,B,A,I,I,I,I,I,I,I,A,B,B,I,N,_,_,_,_,_,_,
_,_,_,_,_,A,B,B,B,B,A,I,I,I,I,I,I,I,A,B,B,B,B,A,_,_,_,_,_,
_,_,_,_,_,_,H,C,C,B,A,I,I,I,I,I,I,I,A,B,C,C,H,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,B,A,I,I,I,I,I,I,I,A,B,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,B,B,I,I,I,I,I,I,I,B,B,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,C,B,I,I,I,I,I,I,I,B,C,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,B,A,I,I,I,I,I,A,B,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,C,A,A,I,I,I,A,A,C,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,A,A,A,C,A,A,A,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,A,I,A,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,
B,I,B,B,B,B,I,I,F,I,I,I,F,I,I,I,F,I,I,I,F,I,I,B,B,B,B,I,B,
B,I,B,B,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,B,B,I,B,
D,B,B,B,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,B,B,B,D,
B,B,B,B,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,B,B,B,B,
B,B,B,B,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,B,B,B,B,
C,B,B,B,B,B,I,I,C,I,I,I,C,I,I,I,C,I,I,I,C,I,I,B,B,B,B,B,C,
_,C,C,C,A,B,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,B,A,C,C,C,_,
_,_,_,_,_,C,B,I,B,I,B,G,F,I,I,I,F,G,B,I,B,I,B,C,_,_,_,_,_,
_,_,_,_,_,_,B,I,B,I,B,I,I,I,I,I,I,I,B,I,B,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,B,I,B,I,I,I,I,I,I,I,B,I,B,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,B,B,I,B,I,I,I,I,I,I,I,B,I,B,B,B,_,_,_,_,_,_,
_,_,_,_,_,_,H,C,C,A,B,I,I,I,I,I,I,I,B,A,C,C,H,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,A,B,I,I,I,I,I,I,I,B,A,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,B,I,I,I,I,I,I,I,B,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,B,A,I,I,I,I,I,A,B,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,_,_,A,A,A,I,I,I,A,A,A,_,_,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,A,A,B,B,B,A,A,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,A,C,C,C,A,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,
B,I,I,F,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,F,I,I,B,
B,I,I,I,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,I,I,I,B,
B,I,I,I,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,I,I,I,B,
D,I,I,I,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,I,I,I,D,
B,I,I,I,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,I,I,I,B,
B,B,B,B,B,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,B,B,B,B,B,
C,C,B,C,C,B,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,B,C,C,B,C,C,
_,H,C,H,_,C,B,I,B,B,B,B,A,I,I,I,A,B,B,B,B,I,B,C,_,H,C,H,_,
_,_,_,_,_,_,D,I,B,B,B,B,A,I,I,I,A,B,B,B,B,I,D,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,B,B,B,B,A,I,I,I,A,B,B,B,B,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,B,B,B,B,B,A,I,I,I,A,B,B,B,B,B,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,B,B,B,B,B,A,I,I,I,A,B,B,B,B,B,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,B,B,B,B,B,A,A,I,A,A,B,B,B,B,B,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,D,B,B,B,B,B,A,A,A,B,B,B,B,B,D,B,_,_,_,_,_,_,
_,_,_,_,_,_,D,B,B,B,B,B,B,B,A,B,B,B,B,B,B,B,D,_,_,_,_,_,_,
_,_,_,_,_,_,B,B,B,B,B,A,B,B,B,B,B,A,B,B,B,B,B,_,_,_,_,_,_,
_,_,_,_,_,_,A,B,B,B,A,_,C,A,C,A,C,_,A,B,B,B,A,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,B,A,_,_,_,_,_,_,_,_,_,A,B,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,
D,I,I,I,B,B,I,I,F,I,I,I,F,I,I,I,F,I,I,I,F,I,I,B,B,I,I,I,D,
B,I,I,I,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,I,I,I,B,
B,I,I,I,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,I,I,I,B,
B,I,I,I,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,I,I,I,B,
D,I,I,I,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,I,I,I,D,
B,B,I,B,B,B,B,I,C,I,I,I,C,I,I,I,C,I,I,I,C,I,B,B,B,B,I,B,B,
C,B,B,B,C,B,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,B,C,B,B,B,C,
_,C,C,C,_,C,B,I,X,F,B,I,B,B,I,B,B,I,B,F,I,I,B,C,_,C,C,C,_,
_,_,_,_,_,_,B,I,I,X,B,I,B,B,I,B,B,I,B,Y,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,D,I,I,I,B,I,B,B,I,B,B,I,B,I,X,I,D,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,B,I,B,B,B,B,B,I,B,I,I,X,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,B,A,B,B,B,B,B,A,B,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,B,A,B,B,B,B,B,A,B,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,D,B,B,B,B,_,B,D,B,D,B,_,B,B,B,I,D,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,F,B,_,C,B,B,B,C,_,B,F,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,A,B,I,I,I,B,_,_,C,A,C,_,_,B,I,I,I,B,A,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,B,_,_,_,_,_,_,_,B,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,A,I,I,I,A,_,_,_,_,_,_,_,A,I,I,I,A,_,_,_,_,_,_,
_,_,_,_,_,_,A,A,I,A,A,_,_,_,_,_,_,_,A,A,I,A,A,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,I,A,_,_,_,_,_,_,_,_,_,A,I,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,A,H,_,_,_,_,_,_,_,_,_,H,A,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,
B,I,I,G,B,B,I,F,A,F,I,F,A,F,I,F,A,F,I,F,A,F,I,B,B,G,I,I,B,
D,I,I,I,B,B,I,I,A,I,I,I,A,I,I,I,A,I,I,I,A,I,I,B,B,I,I,I,D,
B,I,I,I,B,B,I,I,A,I,I,I,A,I,I,I,A,I,I,I,A,I,I,B,B,I,I,I,B,
B,I,I,I,B,B,I,I,A,I,I,I,A,I,I,I,A,I,I,I,A,I,Y,B,B,I,I,I,B,
B,I,I,I,B,B,I,I,A,I,I,I,A,I,I,I,A,I,I,I,A,Z,I,B,B,I,I,I,B,
B,B,B,B,B,B,B,C,A,C,I,C,A,C,I,C,A,C,I,C,A,I,I,B,B,B,B,B,B,
C,C,B,C,C,B,A,Y,A,A,A,A,A,A,A,A,A,A,A,A,A,I,I,B,C,C,B,C,C,
_,H,C,H,_,C,B,I,I,I,B,B,B,B,I,B,B,B,B,Y,I,I,B,C,_,H,C,H,_,
_,_,_,_,_,_,N,I,I,I,B,B,B,B,I,B,B,B,B,I,I,I,N,_,_,_,_,_,_,
_,_,_,_,_,_,N,I,I,W,B,B,B,B,I,B,B,B,B,I,I,I,N,_,_,_,_,_,_,
_,_,_,_,_,C,B,I,I,I,B,B,B,B,B,B,B,B,B,I,I,I,B,C,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,B,C,C,A,B,A,C,C,B,I,I,W,B,_,_,_,_,_,_,
_,_,_,_,_,_,D,I,I,I,B,_,_,_,A,_,_,_,B,I,I,I,D,_,_,_,_,_,_,
_,_,_,_,_,_,B,Y,B,B,B,_,_,_,_,_,_,_,B,B,B,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,N,I,I,I,B,_,_,_,_,_,_,_,B,I,I,I,N,_,_,_,_,_,_,
_,_,_,_,_,_,N,I,I,I,B,_,_,_,_,_,_,_,B,I,I,I,N,_,_,_,_,_,_,
_,_,_,_,_,_,D,I,I,I,B,_,_,_,_,_,_,_,B,I,I,I,D,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,B,_,_,_,_,_,_,_,B,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,A,I,I,I,A,_,_,_,_,_,_,_,A,I,I,I,A,_,_,_,_,_,_,
_,_,_,_,_,_,A,I,I,I,A,_,_,_,_,_,_,_,A,I,I,I,A,_,_,_,_,_,_,
_,_,_,_,_,_,A,A,I,A,A,_,_,_,_,_,_,_,A,A,I,A,A,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,I,A,_,_,_,_,_,_,_,_,_,A,I,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,I,A,_,_,_,_,_,_,_,_,_,A,I,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,

A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,
B,I,I,B,B,B,W,I,F,I,I,I,F,I,I,I,F,I,I,I,F,I,I,B,B,B,I,I,B,
B,d,d,B,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,B,d,d,B,
D,B,B,B,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,Y,B,B,B,B,B,D,
B,D,B,B,B,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,B,B,D,B,
B,B,D,B,B,B,I,I,Y,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,B,D,B,B,
C,B,B,B,B,B,B,Z,I,I,I,I,C,I,I,I,C,I,I,I,C,W,I,B,B,B,B,B,C,
_,C,C,C,C,B,A,I,I,A,A,A,A,A,A,A,A,A,A,A,Z,I,A,B,C,C,C,C,_,
_,_,_,_,_,C,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,C,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,W,B,B,B,B,B,B,B,B,B,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,D,I,Z,I,B,C,C,C,A,C,C,C,B,I,I,I,D,_,_,_,_,_,_,
_,_,_,_,_,_,B,Z,I,I,B,_,_,_,_,_,_,_,B,I,I,W,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,D,_,_,_,_,_,_,_,D,B,Z,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,B,_,_,_,_,_,_,_,B,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,A,B,I,I,I,B,A,_,_,_,_,_,A,B,I,I,I,B,A,_,_,_,_,_,
_,_,_,_,_,_,B,I,I,I,B,_,_,_,_,_,_,_,B,I,I,I,B,_,_,_,_,_,_,
_,_,_,_,_,_,A,I,I,I,A,_,_,_,_,_,_,_,A,I,I,I,A,_,_,_,_,_,_,
_,_,_,_,_,_,A,A,I,A,A,_,_,_,_,_,_,_,A,A,I,A,A,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,I,A,_,_,_,_,_,_,_,_,_,A,I,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,H,A,_,_,_,_,_,_,_,_,_,_,_,A,H,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,C,C,C,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,C,C,C,_,
_,_,_,_,B,B,F,I,I,I,I,I,I,G,I,G,I,I,I,I,I,X,F,B,B,_,_,_,_,
_,_,_,_,B,B,W,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,X,B,B,_,_,_,_,
_,H,H,_,B,B,I,X,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,_,H,H,_,
_,_,_,_,B,B,I,I,X,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,B,_,_,_,_,
_,_,_,_,A,B,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,B,A,_,_,_,_,
_,_,_,_,A,B,B,I,I,B,B,I,I,I,I,I,I,I,B,B,B,B,B,B,A,_,_,_,_,
_,_,_,_,A,A,A,A,I,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,_,_,_,_,
_,_,_,_,_,A,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,A,_,_,_,_,_,
_,_,_,_,_,A,A,B,N,B,D,B,N,D,B,D,N,B,D,B,N,B,A,A,_,_,_,_,_,
_,_,_,_,_,_,A,B,N,D,B,B,N,B,D,B,N,B,B,D,N,B,A,_,_,_,_,_,_,
_,_,_,_,_,_,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,_,_,_,_,_,_,
_,_,_,_,_,_,B,D,B,B,B,H,H,J,H,J,H,H,B,B,B,D,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,B,D,B,B,_,_,_,_,_,_,_,B,B,D,B,B,_,_,_,_,_,_,
_,_,_,_,_,_,B,B,B,D,B,_,_,_,_,_,_,_,B,D,B,B,B,_,_,_,_,_,_,
_,_,_,_,_,_,D,B,N,B,D,_,_,_,_,_,_,_,D,B,N,B,D,_,_,_,_,_,_,
_,_,_,_,_,_,B,B,N,B,B,_,_,_,_,_,_,_,B,B,N,B,B,_,_,_,_,_,_,
_,_,_,_,_,_,A,B,D,B,A,_,_,_,_,_,_,_,A,B,D,B,A,_,_,_,_,_,_,
_,_,_,_,_,_,H,A,B,A,_,_,_,_,_,_,_,_,_,A,B,A,H,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,_,_,A,A,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,C,C,C,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,C,C,C,_,
_,_,_,_,B,B,B,B,B,B,B,B,B,B,I,B,B,B,B,B,B,B,B,B,B,_,_,_,_,
_,_,_,_,B,B,B,B,B,B,B,B,B,B,I,B,B,B,B,B,B,B,B,B,B,_,_,_,_,
_,_,_,_,A,B,B,B,B,B,B,B,B,B,I,B,B,B,B,B,B,B,B,B,A,_,_,_,_,
_,_,_,_,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,_,_,_,_,
_,_,_,_,A,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,A,_,_,_,_,
_,_,_,_,_,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,_,_,_,_,_,
_,_,_,_,_,A,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,A,_,_,_,_,_,
_,_,_,_,_,_,A,C,C,C,C,C,C,A,C,A,C,C,C,C,C,C,A,_,_,_,_,_,_,
_,_,_,_,_,_,A,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,A,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,C,_,_,_,A,_,_,_,A,_,_,_,C,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,A,_,A,_,_,_,_,_,_,_,_,_,A,_,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,_,C,C,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,C,C,_,_,
_,_,_,_,A,B,B,B,B,B,B,B,G,I,I,I,G,B,B,B,B,B,B,B,A,_,_,_,_,
_,_,_,_,A,B,B,B,B,B,B,B,I,I,I,I,I,B,B,B,B,B,B,B,A,_,_,_,_,
_,_,_,_,A,A,B,B,B,B,B,B,I,I,I,I,I,B,B,B,B,B,B,A,A,_,_,_,_,
_,_,_,_,_,A,B,B,B,B,B,B,I,I,I,I,I,B,B,B,B,B,B,A,_,_,_,_,_,
_,_,_,_,_,A,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,A,_,_,_,_,_,
_,_,_,_,_,_,A,B,B,B,B,B,B,B,B,B,B,B,B,B,B,B,A,_,_,_,_,_,_,
_,_,_,_,_,_,A,C,C,C,C,A,C,A,A,A,C,A,C,C,C,C,A,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,_,C,C,C,C,C,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,C,C,C,C,C,_,_,
_,_,_,_,_,_,_,B,G,I,F,B,I,I,I,I,I,B,F,I,G,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,I,I,I,B,I,I,I,I,I,B,I,I,I,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,I,I,I,B,I,I,I,I,I,B,I,I,I,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,I,I,I,B,I,I,I,I,I,B,I,I,I,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,I,I,I,B,B,B,B,B,B,B,I,I,I,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,B,B,B,B,C,A,C,A,C,B,B,B,B,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,C,B,C,C,_,_,_,_,_,C,C,B,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,H,C,H,_,_,_,_,_,_,_,H,C,H,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,_,_,C,C,C,C,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,C,C,C,C,_,_,_,
_,_,_,_,_,_,_,I,I,I,I,B,I,I,I,I,I,B,I,I,I,I,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,d,I,I,I,B,I,I,I,I,I,B,I,I,I,d,_,_,_,_,_,_,_,
_,_,_,_,_,_,H,B,I,I,I,B,I,I,I,I,I,B,I,I,I,B,H,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,I,I,I,B,B,B,B,B,B,B,I,I,I,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,D,I,I,I,B,B,C,A,C,B,B,I,I,I,D,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,B,I,B,B,C,_,_,_,C,B,B,I,B,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,B,B,B,C,_,_,_,_,_,C,B,B,B,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,C,C,C,_,_,_,_,_,_,_,C,C,C,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,_,_,_,_,C,C,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,C,C,_,_,_,_,_,
_,_,_,_,_,_,_,I,I,I,I,I,I,I,I,I,I,I,I,I,I,I,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,d,I,I,I,I,I,I,I,I,I,I,I,I,I,d,_,_,_,_,_,_,_,
_,_,_,_,_,_,H,B,I,I,I,B,I,I,I,I,I,B,I,I,I,B,H,_,_,_,_,_,_,
_,_,_,_,_,_,_,D,I,I,I,B,B,B,B,B,B,B,I,I,I,D,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,I,I,I,B,B,C,A,C,B,B,I,I,I,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,B,B,B,B,C,_,_,_,C,B,B,B,B,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,C,B,C,C,_,_,_,_,_,C,C,B,C,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,H,C,H,_,_,_,_,_,_,_,H,C,H,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,

_,_,_,_,_,_,_,A,A,A,A,A,A,A,A,A,A,A,A,A,A,A,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,B,D,B,B,B,D,B,D,B,B,B,D,B,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,D,B,B,B,D,B,B,B,D,B,B,B,D,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,D,B,B,B,D,B,B,B,B,B,D,B,B,B,D,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,B,B,D,B,B,C,C,C,B,B,D,B,B,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,B,B,D,B,B,C,_,_,_,C,B,B,D,B,B,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,C,B,B,B,C,_,_,_,_,_,C,B,B,B,C,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,C,C,C,_,_,_,_,_,_,_,C,C,C,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,
_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_,_}}
