
--[[

  Copyright (C) 2015 - Auke Kok <sofar@foo-projects.org>

  "frame" is free software; you can redistribute it and/or modify
  it under the terms of the GNU Lesser General Public License as
  published by the Free Software Foundation; either version 2.1 of
  the license, or (at your option) any later version.

--]]

frame = {}

-- handle node removal from frame
local function frame_on_punch(pos, node, puncher, pointd)
	if puncher and not core.check_player_privs(puncher, "protection_bypass") then
		local name = puncher:get_player_name()
		if core.is_protected(pos, name) then
			core.record_protection_violation(pos, name)
			return false
		end
	end

	local def = core.registered_nodes[node.name]
	local item = ItemStack(def.frame_contents)

	-- preserve itemstack metadata and wear
	local meta = core.get_meta(pos)
	local wear = meta:get_int("wear")
	if wear then
		item:set_wear(wear)
	end
	local metadata = meta:get_string("metadata")
	if metadata ~= "" then
		item:set_metadata(metadata)
	end

	--core.handle_node_drops(pos, {item}, puncher)
	local inv = puncher:get_inventory()
	if inv:room_for_item("main", item) then
		inv:add_item("main", item)
		core.sound_play(def.sounds.dug, {pos = pos})
		core.swap_node(pos, {name = "frame:empty", param2 = node.param2})
	end
end

-- handle node insertion into frame
local function frame_on_rightclick(pos, node, clicker, itemstack, pointd)
	local pname = clicker:get_player_name()
	if clicker and not core.check_player_privs(clicker, "protection_bypass") then
		if core.is_protected(pos, pname) then
			core.record_protection_violation(pos, pname)
			return itemstack
		end
	end

	local nodename = itemstack:get_name()
	if not nodename then
		return itemstack
	end

	local wear = itemstack:get_wear()
	if wear then
		local meta = core.get_meta(pos)
		meta:set_int("wear", wear)
	end
	local metadata = itemstack:get_metadata()-- ?
	if metadata ~= "" then
		local meta = core.get_meta(pos)
		meta:set_string("metadata", metadata)
	end

	local name = "frame:" .. nodename:gsub(":", "_")
	local def = core.registered_nodes[name]
	if not def then
		def = core.registered_items[name]
		if not def then
			return itemstack
		end
	end
	core.sound_play(def.sounds.place, {pos = pos})
	core.swap_node(pos, {name = name, param2 = node.param2})
	if not core.is_creative_enabled(pname) then
		itemstack:take_item()
	end
	return itemstack
end

function frame.register(name)
	assert(name, "no content passed")
	local tiles

	local def = core.registered_nodes[name]
	if not def then
		-- item?
		def = core.registered_items[name]
		if not def then
			-- nonexistant item.
			core.log("warning", "Frame registered for \"" .. name .. "\" but it isn't registered")
			return
		end
		assert(def.inventory_image, "no inventory image for " .. name)

		tiles = {
			{name = "frame_frame.png"},
			{name = def.inventory_image},
			{name = "blank.png"},
			{name = "blank.png"},
			{name = "blank.png"},
		}
	else
		-- node
		if def.inventory_image ~= "" then
			-- custom inventory override image first.
			tiles = {
				{name = "frame_frame.png"},
				{name = def.inventory_image or "blank.png"},
				{name = "blank.png"},
				{name = "blank.png"},
				{name = "blank.png"},
			}
		elseif def.drawtype ~= "normal" then
			-- use tiles[1] only, but on frame
			tiles = {
				{name = "frame_frame.png"},
				{name = def.tiles[1] and def.tiles[1].name or def.tiles[1] or "blank.png"},
				{name = "blank.png"},
				{name = "blank.png"},
				{name = "blank.png"},
			}
		else -- type(def.tiles[1]) == "table" then
			-- multiple tiles
			tiles = {
				{name = "frame_frame.png"},
				{name = "blank.png"},
				{name = def.tiles[1] and def.tiles[1].name or def.tiles[1]
					or "blank.png"},
				{name = def.tiles[2] and def.tiles[2].name or def.tiles[2]
					or def.tiles[1] and def.tiles[1].name or def.tiles[1]
					or "blank.png"},
				{name = def.tiles[6] and def.tiles[6].name or def.tiles[6]
				        or def.tiles[3] and def.tiles[3].name or def.tiles[3]
					or def.tiles[2] and def.tiles[2].name or def.tiles[2]
					or def.tiles[1] and def.tiles[1].name or def.tiles[1]
					or "blank.png"},
			}
		end
	end
	assert(def, name .. " is not a known node or item")

	core.register_node("frame:" .. name:gsub(":", "_"), {
		description = "Item Frame with " .. def.description,
		drawtype = "mesh",
		mesh = "frame.obj",
		tiles = tiles,
		paramtype = "light",
		paramtype2 = "wallmounted",
		use_texture_alpha = "blend",
		sunlight_propagates = true,
		walkable = false,
		selection_box = {
			type = "wallmounted",
			wall_side = {-1/2, -1/2, -1/2, -3/8, 1/2, 1/2},
		},
		sounds = default.node_sound_defaults(),
		groups = {oddly_breakable_by_hand = 1, snappy = 3, not_in_creative_inventory = 1},
		frame_contents = name,
		drop = "",
		on_punch = frame_on_punch,
	})
end

-- empty frame
core.register_node("frame:empty", {
	description = "Item Frame",
	drawtype = "mesh",
	mesh = "frame.obj",
	inventory_image = "frame_frame.png",
	wield_image = "frame_frame.png",
	tiles = {
		{name = "frame_frame.png"},
		{name = "blank.png"},
		{name = "blank.png"},
		{name = "blank.png"},
		{name = "blank.png"},
	},
	paramtype = "light",
	paramtype2 = "wallmounted",
	use_texture_alpha = "blend",
	sunlight_propagates = true,
	walkable = false,
	selection_box = {
		type = "wallmounted",
		wall_side = {-1/2, -1/2, -1/2, -3/8, 1/2, 1/2},
	},
	sounds = default.node_sound_defaults(),
	groups = {snappy = 3, oddly_breakable_by_hand = 3, cracky = 1, attached_node = 1},
	on_rightclick = frame_on_rightclick,
})

-- craft
core.register_craft({
	output = "frame:empty",
	recipe = {
		{"default:stick", "default:stick", "default:stick"},
		{"default:stick", "default:birch_bark", "default:stick"},
		{"default:stick", "default:stick", "default:stick"}
	}
})

for _, node in pairs({
	"beds:bed_bottom",
	"beds:fancy_bed_bottom",
	"binoculars:binoculars",
	"boats:boat",
	"bones:bones",
	"bucket:bucket_empty",
	"bucket:bucket_water",
	"bucket:bucket_fresh_water",
	"bucket:bucket_lava",
	"bucket:clay_bucket_empty",
	"bucket:clay_bucket_water",
	"bucket:clay_bucket_fresh_water",
	"bucket:clay_bucket_lava",
	"bucket:wooden_bucket_empty",
	"bucket:wooden_bucket_water",
	"bucket:wooden_bucket_fresh_water",
	"butterflies:butterfly_white",
	"butterflies:butterfly_red",
	"butterflies:butterfly_violet",
	"carts:brakerail",
	"carts:cart",
	"carts:copper_rail",
	"carts:powerrail",
	"carts:rail",
	"default:stone",
	"default:rocks",
	"default:rock",
	"default:cobble",
	"default:stone_block",
	"default:stone_brick",
	"default:mossystone",
	"default:mossycobble",
	"default:mossystone_block",
	"default:mossystone_brick",
	"default:basalt",
	"default:desert_stone",
	"default:desert_cobble",
	"default:desert_rocks",
	"default:desert_rock",
	"default:desert_stone_block",
	"default:desert_stone_brick",
	"default:molten_rock",
	"default:pumice",
	"default:ocean_stone",
	"default:ocean_cobble",
	"default:ocean_stone_carved",
	"default:ocean_stone_circular",
	"default:ocean_stone_pillar",
	"default:ocean_stone_brick",
	"default:sandstone",
	"default:sandstone_block",
	"default:sandstone_brick",
	"default:desert_sandstone",
	"default:desert_sandstone_block",
	"default:desert_sandstone_brick",
	"default:silver_sandstone",
	"default:silver_sandstone_block",
	"default:silver_sandstone_brick",
	"default:obsidian",
	"default:obsidian_block",
	"default:obsidian_brick",
	"default:white_marble",
	"default:white_marble_block",
	"default:marble",
	"default:marble_brick",
	"default:diamite",
	"default:granite",
	"default:bedrock",
	"default:stone_with_coal",
	"default:desert_stone_with_coal",
	"default:coal_block",
	"default:stone_with_sulfur",
	"default:stone_with_iron",
	"default:desert_stone_with_iron",
	"default:wrought_iron_block",
	"default:cast_iron_block",
	"default:steel_block",
	"default:stainless_steel_block",
	"default:stone_with_copper",
	"default:copper_block",
	"default:stone_with_tin",
	"default:tin_block",
	"default:brass_block",
	"default:bronze_block",
	"default:stone_with_chromium",
	"default:chromium_block",
	"default:stone_with_zinc",
	"default:zinc_block",
	"default:stone_with_silver",
	"default:silver_block",
	"default:stone_with_gold",
	"default:desert_stone_with_gold",
	"default:gold_block",
	"default:stone_with_mese",
	"default:mese",
	"default:stone_with_mithril",
	"default:mithril_block",
	"default:stone_with_diamond",
	"default:diamond_block",
	"default:stone_with_blue_diamond",
	"default:blue_diamond_block",
	"default:orichalc_block",
	"default:ocealite",
	"default:crystal_block",
	"default:crystal_spike",
	"default:compost_pile",
	"default:compost",
	"default:dirt",
	"default:mud",
	"default:dirt_with_grass",
	"default:dirt_with_short_grass",
	"default:dirt_with_grass_footsteps",
	"default:dirt_with_savanna_grass",
	"default:dirt_with_snow",
	"default:dirt_with_swamp_grass",
	"default:dirt_with_rainforest_litter",
	"default:dirt_with_coniferous_litter",
	"default:dirt_with_blue_moss",
	"default:dry_dirt",
	"default:clay_dirt",
	"default:clay_dirt_with_savanna_grass",
	"default:dry_clay_dirt",
	"default:permafrost",
	"default:permafrost_with_stones",
	"default:permafrost_with_moss",
	"default:sand",
	"default:desert_sand",
	"default:silver_sand",
	"default:gravel",
	"default:silt",
	"default:clay",
	"default:terracotta",
	"default:snow",
	"default:snow_block",
	"default:snow_brick",
	"default:ice",
	"default:ice_block",
	"default:ice_brick",
	"default:acacia_trunk",
	"default:acacia_wood",
	"default:acacia_leaves",
	"default:acacia_sapling",
	"default:apple_trunk",
	"default:apple_wood",
	"default:apple",
	"default:apple_leaves",
	"default:apple_leaves_blooming",
	"default:apple_leaves_fruiting",
	"default:apple_sapling",
	"default:aspen_trunk",
	"default:aspen_wood",
	"default:aspen_leaves",
	"default:aspen_sapling",
	"default:beech_trunk",
	"default:wood",
	"default:beech_leaves",
	"default:sapling",
	"default:birch_trunk",
	"default:birch_wood",
	"default:birch_leaves",
	"default:birch_sapling",
	"default:coco_palm_trunk",
	"default:coco_palm_wood",
	"default:coco_0",
	"default:coco_palm_leaves",
	"default:coco_palm_sapling",
	"default:jungle_trunk",
	"default:jungle_wood",
	"default:jungle_leaves",
	"default:jungle_sapling",
	"default:emergent_jungle_sapling",
	"default:mangrove_trunk",
	"default:mangrove_wood",
	"default:mangrove_leaves",
	"default:mangrove_sapling",
	"default:orange_trunk",
	"default:orange_leaves",
	"default:orange_leaves_blooming",
	"default:orange_leaves_fruiting",
	"default:orange_sapling",
	"default:pine_needles",
	"default:pine_sapling",
	"default:pine_trunk",
	"default:pine_wood",
	"default:coir_block",
	"default:coir_block_wet",
	"default:seaweedy_wood",
	"default:cactus",
	"default:cactus_fruiting",
	"default:large_cactus_seedling",
	"default:reed",
	"default:reed_block",
	"default:reed_block_dry",
	"default:bulrush_1",
	"default:bulrush_2",
	"default:papyrus",
	"default:dry_shrub",
	"default:subtrop_grass",
	"default:jungle_grass_1",
	"default:jungle_grass_2",
	"default:jungle_grass_3",
	"default:swamp_grass_1",
	"default:swamp_grass_2",
	"default:swamp_grass_3",
	"default:swamp_grass_4",
	"default:swamp_grass_5",
	"default:boston_fern",
	"default:frost_grass",
	"default:grass_1",
	"default:grass_2",
	"default:grass_3",
	"default:grass_4",
	"default:grass_5",
	"default:savanna_grass_1",
	"default:savanna_grass_2",
	"default:savanna_grass_3",
	"default:savanna_grass_4",
	"default:savanna_grass_5",
	"default:fern_1",
	"default:fern_2",
	"default:fern_3",
	"default:marram_grass_1",
	"default:marram_grass_2",
	"default:marram_grass_3",
	"default:poison_ivy_1",
	"default:poison_ivy_2",
	"default:poison_ivy_3",
	"default:juncus_1",
	"default:juncus_2",
	"default:bush_stem",
	"default:bush_leaves",
	"default:bush_leaves_fruiting",
	"default:bush_sapling",
	"default:blueberry_bush_leaves_fruiting",
	"default:blueberry_bush_leaves",
	"default:blueberry_bush_sapling",
	"default:acacia_bush_stem",
	"default:acacia_bush_leaves",
	"default:acacia_bush_sapling",
	"default:pine_bush_stem",
	"default:pine_bush_needles",
	"default:pine_bush_sapling",
	"default:kelp_brown",
	"default:kelp_dark_green",
	"default:kelp_green",
	"default:kelp_yellow",
	"default:seaweed",
	"default:alga",
	"default:seagrass",
	"default:seagrass_green",
	"default:seagrass_red",
	"default:seaweed_grass",
	"default:sea_anemone",
	"default:coral_blue",
	"default:coral_cyan",
	"default:coral_green",
	"default:coral_magenta_tip",
	"default:coral_red",
	"default:coral_skeleton_tip",
	"default:coral_brown",
	"default:coral_magenta",
	"default:coral_orange",
	"default:coral_skeleton",
	"default:water_flowing",
	"default:water_source",
	"default:fresh_water_flowing",
	"default:fresh_water_source",
	"default:lava_flowing",
	"default:lava_source",
	"default:bookshelf",
	"default:sign_wall_steel",
	"default:sign_wall_wood",
	"default:ladder_steel",
	"default:ladder_stone",
	"default:ladder_wood",
	"default:fence_acacia_wood",
	"default:fence_apple_wood",
	"default:fence_aspen_wood",
	"default:fence_wood",
	"default:fence_birch_wood",
	"default:fence_coco_palm_wood",
	"default:fence_jungle_wood",
	"default:fence_mangrove_wood",
	"default:fence_pine_wood",
	"default:fence_rail_acacia_wood",
	"default:fence_rail_apple_wood",
	"default:fence_rail_aspen_wood",
	"default:fence_rail_wood",
	"default:fence_rail_birch_wood",
	"default:fence_rail_coco_palm_wood",
	"default:fence_rail_jungle_wood",
	"default:fence_rail_mangrove_wood",
	"default:fence_rail_pine_wood",
	"default:glass",
	"default:obsidian_glass",
	"default:cement_block",
	"default:concrete_block",
	"default:concrete_block2",
	"default:concrete_paver",
	"default:brick",
	"default:meselamp",
	"default:mese_post_light_acacia_wood",
	"default:mese_post_light_aspen_wood",
	"default:mese_post_light",
	"default:mese_post_light_jungle_wood",
	"default:mese_post_light_pine_wood",
	"default:ocealitelamp",
	"default:spectrum",
	"default:cloud",
	"default:chest",
	"default:chest_locked",
	"default:bamboo_chest",
	"default:furnace",
	"default:torch",
	"default:torch_spent",
	"default:meselamp_torch",
	"default:pick_blue_diamond",
	"default:pick_bronze",
	"default:pick_crystal",
	"default:pick_orichalc",
	"default:pick_diamond",
	"default:pick_mithril",
	"default:pick_mese",
	"default:pick_silver",
	"default:pick_steel",
	"default:pick_stone",
	"default:pick_wood",
	"default:shovel_blue_diamond",
	"default:shovel_bronze",
	"default:shovel_crystal",
	"default:shovel_orichalc",
	"default:shovel_diamond",
	"default:shovel_mithril",
	"default:shovel_mese",
	"default:shovel_silver",
	"default:shovel_steel",
	"default:shovel_stone",
	"default:shovel_wood",
	"default:axe_blue_diamond",
	"default:axe_bronze",
	"default:axe_crystal",
	"default:axe_orichalc",
	"default:axe_diamond",
	"default:axe_mithril",
	"default:axe_mese",
	"default:axe_silver",
	"default:axe_steel",
	"default:axe_stone",
	"default:axe_wood",
	"default:hand_axe_stone",
	"default:hand_axe_desert_stone",
	"default:hand_axe_flint",
	"default:sword_blue_diamond",
	"default:sword_bronze",
	"default:sword_crystal",
	"default:sword_orichalc",
	"default:sword_diamond",
	"default:sword_mithril",
	"default:sword_mese",
	"default:sword_silver",
	"default:sword_steel",
	"default:sword_stone",
	"default:sword_wood",
	"default:plasma_cannon",
	"default:birch_bark",
	"default:blue_diamond",
	"default:blueberries",
	"default:book",
	"default:book_written",
	"bonemeal:bone",
	"default:brass_ingot",
	"default:bronze_ingot",
	"default:bush_berry",
	"default:cactus_fruit",
	"default:cast_iron_ingot",
	"default:chromium_ingot",
	"default:chromium_lump",
	"default:clay_brick",
	"default:clay_brick_mix",
	"default:clay_lump",
	"default:coal_lump",
	"default:coconut",
	"default:coconut_flesh",
	"default:coconut_milk",
	"default:coir",
	"default:coconut_young",
	"default:coconut_young_open",
	"default:cooked_bulrush",
	"default:copper_ingot",
	"default:copper_lump",
	"default:crystal_ingot",
	"default:diamite_dust",
	"default:diamond",
	"default:flint",
	"default:glue",
	"default:gold_ingot",
	"default:gold_lump",
	"default:iron_lump",
	"default:mese_crystal",
	"default:mese_crystal_fragment",
	"default:mithril_ingot",
	"default:mithril_lump",
	"default:obsidian_shard",
	"default:ocealite_crystal",
	"default:ocealite_crystal_fragment",
	"default:oil_extract",
	"default:orange",
	"default:orichalc_ingot",
	"default:padlock",
	"default:paper",
	"default:pine_nuts",
	"default:sea_salad",
	"default:silt_lump",
	"default:silver_ingot",
	"default:silver_lump",
	"default:stainless_steel_ingot",
	"default:steel_ingot",
	"default:steel_bar",
	"default:stick",
	"default:sulfur",
	"default:terracotta_lump",
	"default:tin_ingot",
	"default:tin_lump",
	"default:wet_cement",
	"default:wrought_iron_ingot",
	"default:zinc_ingot",
	"default:zinc_lump",
	"doors:door_coco_palm_wood",
	"doors:door_glass",
	"doors:door_ice",
	"doors:door_obsidian_glass",
	"doors:door_steel",
	"doors:door_stone",
	"doors:door_wood",
	"doors:door_wood_2",
	"doors:trapdoor",
	"doors:trapdoor_steel",
	"dye:black",
	"dye:blue",
	"dye:brown",
	"dye:cyan",
	"dye:dark_green",
	"dye:dark_grey",
	"dye:green",
	"dye:grey",
	"dye:light_blue",
	"dye:magenta",
	"dye:orange",
	"dye:pink",
	"dye:red",
	"dye:violet",
	"dye:white",
	"dye:yellow",
	"fabric:spinning_wheel",
	"fabric:string",
	"fabric:sheet_black",
	"fabric:sheet_light_blue",
	"fabric:sheet_blue",
	"fabric:sheet_brown",
	"fabric:sheet_cyan",
	"fabric:sheet_dark_green",
	"fabric:sheet_dark_grey",
	"fabric:sheet_green",
	"fabric:sheet_grey",
	"fabric:sheet_magenta",
	"fabric:sheet_orange",
	"fabric:sheet_pink",
	"fabric:sheet_red",
	"fabric:sheet_violet",
	"fabric:sheet_white",
	"fabric:sheet_yellow",
	"fabric:block_black",
	"fabric:block_light_blue",
	"fabric:block_blue",
	"fabric:block_brown",
	"fabric:block_cyan",
	"fabric:block_dark_green",
	"fabric:block_dark_grey",
	"fabric:block_green",
	"fabric:block_grey",
	"fabric:block_magenta",
	"fabric:block_orange",
	"fabric:block_pink",
	"fabric:block_red",
	"fabric:block_violet",
	"fabric:block_white",
	"fabric:block_yellow",
	"farming:soil",
	"farming:soil_wet",
	"farming:clay_soil",
	"farming:clay_soil_wet",
	"farming:straw_pile",
	"farming:straw",
	"farming:straw_bale",
	"farming:cut_grass",
	"farming:hay_pile",
	"farming:hay",
	"farming:hay_bale",
	"farming:spent_biomasse",
	"farming:hoe_steel",
	"farming:hoe_stone",
	"farming:hoe_wood",
	"farming:seed_cotton",
	"farming:cotton",
	"farming:cottonseed_oil",
	"farming:cotton_S1",
	"farming:cotton_S2",
	"farming:cotton_S3",
	"farming:cotton_S4",
	"farming:cotton_S5",
	"farming:cotton_S6",
	"farming:cotton_S7",
	"farming:cotton_S8",
	"farming:cotton_wild",
	"farming:seed_wheat",
	"farming:wheat",
	"farming:wheat_flour",
	"farming:wheat_dough",
	"farming:wheat_bread",
	"farming:wheat_S1",
	"farming:wheat_S2",
	"farming:wheat_S3",
	"farming:wheat_S4",
	"farming:wheat_S5",
	"farming:wheat_S6",
	"farming:wheat_S7",
	"farming:wheat_S8",
	"farming:seed_alfalfa",
	"farming:alfalfa",
	"farming:alfalfa_leaves",
	"farming:alfalfa_flour",
	"farming:alfalfa_treated",
	"farming:vegan_milk",
	"farming:vegan_butter",
	"farming:vegan_cheese",
	"farming:vegan_egg",
	"farming:vegan_fish",
	"farming:vegan_meat",
	"farming:alfalfa_S1",
	"farming:alfalfa_S2",
	"farming:alfalfa_S3",
	"farming:alfalfa_S4",
	"farming:alfalfa_S5",
	"farming:alfalfa_S6",
	"farming:alfalfa_S7",
	"farming:alfalfa_S8",
	"farming:alfalfa_S9",
	"farming:seed_amaranth",
	"farming:amaranth",
	"farming:amaranth_magenta",
	"farming:amaranth_leaves",
	"farming:amaranth_flour",
	"farming:amaranth_dough",
	"farming:amaranth_bread",
	"farming:amaranth_cooked",
	"farming:amaranth_S1",
	"farming:amaranth_S2",
	"farming:amaranth_S3",
	"farming:amaranth_S4",
	"farming:amaranth_S5",
	"farming:amaranth2_S5",
	"farming:amaranth_S6",
	"farming:amaranth2_S6",
	"farming:artichoke",
	"farming:artichoke_S1",
	"farming:artichoke_S2",
	"farming:artichoke_S3",
	"farming:artichoke_S4",
	"farming:artichoke_S5",
	"farming:artichoke_S6",
	"farming:asparagus_seed",
	"farming:asparagus",
	"farming:asparagus_soup",
	"farming:asparagus_S1",
	"farming:asparagus_S2",
	"farming:asparagus_S3",
	"farming:asparagus_S4",
	"farming:asparagus_S5",
	"farming:asparagus_S6",
	"farming:asparagus_S7",
	"farming:seed_barley",
	"farming:barley",
	"farming:barley_flour",
	"farming:barley_dough",
	"farming:barley_bread",
	"farming:barley_S1",
	"farming:barley_S2",
	"farming:barley_S3",
	"farming:barley_S4",
	"farming:barley_S5",
	"farming:barley_S6",
	"farming:barley_S7",
	"farming:beans_green",
	"farming:beans_yellow",
	"farming:crop_poles",
	"farming:beanpole_S1",
	"farming:beanpole_S2",
	"farming:beanpole_S3",
	"farming:beanpole_S4",
	"farming:beanpole_S5",
	"farming:beanpole_S6",
	"farming:bean_bush",
	"farming:blackberries",
	"farming:smoothie_blackberry",
	"farming:blackberry_S1",
	"farming:blackberry_S2",
	"farming:blackberry_S3",
	"farming:blackberry_S4",
	"farming:blackberry_S5",
	"farming:blackberry_S6",
	"farming:blackcurrants",
	"farming:blackcurrant_S1",
	"farming:blackcurrant_S2",
	"farming:blackcurrant_S3",
	"farming:blackcurrant_S4",
	"farming:blackcurrant_S5",
	"farming:blackcurrant_S6",
	"farming:blackcurrant_S7",
	"farming:blueberries",
	"farming:blueberry_muffin",
	"farming:blueberry_muffin_dough",
	"farming:blueberry_S1",
	"farming:blueberry_S2",
	"farming:blueberry_S3",
	"farming:blueberry_S4",
	"farming:blueberry_S5",
	"farming:blueberry_S6",
	"farming:blueberry_S7",
	"farming:seed_buckwheat",
	"farming:buckwheat_flour",
	"farming:buckwheat_dough",
	"farming:buckwheat_bread",
	"farming:buckwheat_S1",
	"farming:buckwheat_S2",
	"farming:buckwheat_S3",
	"farming:buckwheat_S4",
	"farming:buckwheat_S5",
	"farming:carrot",
	"farming:carrot_leaves",
	"farming:carrot_silver",
	"farming:carrot_S1",
	"farming:carrot_S2",
	"farming:carrot_S3",
	"farming:carrot_S4",
	"farming:carrot_S5",
	"farming:carrot_S6",
	"farming:carrot_S7",
	"farming:carrot_S8",
	"farming:wildcarrot",
	"farming:wildcarrot_S1",
	"farming:wildcarrot_S2",
	"farming:wildcarrot_S3",
	"farming:wildcarrot_S4",
	"farming:wildcarrot_S5",
	"farming:wildcarrot_S6",
	"farming:wildcarrot_S7",
	"farming:wildcarrot_S8",
	"farming:cauliflower_seed",
	"farming:brocoli_sprout",
	"farming:cabbage",
	"farming:brocoli",
	"farming:cauliflower",
	"farming:cauliflower_leaves",
	"farming:cauliflower_S1",
	"farming:cauliflower_S2",
	"farming:cauliflower_S3",
	"farming:cauliflower_S4",
	"farming:cauliflower_S5",
	"farming:cauliflower_S6",
	"farming:cauliflower_S7",
	"farming:cauliflower_S8",
	"farming:cauliflower_S9",
	"farming:celery",
	"farming:celery_pb",
	"farming:celery_S1",
	"farming:celery_S2",
	"farming:celery_S3",
	"farming:celery_S4",
	"farming:celery_S5",
	"farming:chili_pepper",
	"farming:cayenne_pepper",
	"farming:chili_bowl",
	"farming:chili_S1",
	"farming:chili_S2",
	"farming:chili_S3",
	"farming:chili_S4",
	"farming:chili_S5",
	"farming:chili_S6",
	"farming:chili_S7",
	"farming:chili_S8",
	"farming:chili_S9",
	"farming:chives",
	"farming:chive_S1",
	"farming:chive_S2",
	"farming:chive_S3",
	"farming:chive_S4",
	"farming:chive_S5",
	"farming:chive_S6",
	"farming:wild_chive",
	"farming:cilantro_seed",
	"farming:cilantro",
	"farming:cilantro_S1",
	"farming:cilantro_S2",
	"farming:cilantro_S3",
	"farming:cilantro_S4",
	"farming:cilantro_S5",
	"farming:coffee_beans",
	"farming:coffee_ground",
	"farming:coffee_S1",
	"farming:coffee_S2",
	"farming:coffee_S3",
	"farming:coffee_S4",
	"farming:coffee_S5",
	"farming:cucumber",
	"farming:cucumber_leaves",
	"farming:cucumber_S1",
	"farming:cucumber_S2",
	"farming:cucumber_S3",
	"farming:cucumber_S4",
	"farming:cucumber_S5",
	"farming:cucumber_S6",
	"farming:cucumber_S7",
	"farming:seed_flax",
	"farming:flax_flour",
	"farming:flax_dough",
	"farming:flax_bread",
	"farming:flaxseed_oil",
	"farming:flax_fresh",
	"farming:flax",
	"farming:flax_S1",
	"farming:flax_S2",
	"farming:flax_S3",
	"farming:flax_S4",
	"farming:flax_S5",
	"farming:flax_S6",
	"farming:flax_S7",
	"farming:flax_S8",
	"farming:garlic_clove",
	"farming:garlic",
	"farming:garlic_bread",
	"farming:garlic_braid",
	"farming:garlic_S1",
	"farming:garlic_S2",
	"farming:garlic_S3",
	"farming:garlic_S4",
	"farming:garlic_S5",
	"farming:garlic_S6",
	"farming:ginger",
	"farming:ginger_S1",
	"farming:ginger_S2",
	"farming:ginger_S3",
	"farming:ginger_S4",
	"farming:ginger_S5",
	"farming:ginger_S6",
	"farming:gooseberries",
	"farming:gooseberry_S1",
	"farming:gooseberry_S2",
	"farming:gooseberry_S3",
	"farming:gooseberry_S4",
	"farming:gooseberry_S5",
	"farming:gooseberry_S6",
	"farming:gooseberry_S7",
	"farming:gooseberry_S8",
	"farming:grapes_green",
	"farming:grapes_red",
	"farming:grapes_purple",
	"farming:grapes_black",
	"farming:trellis",
	"farming:grapes_S1",
	"farming:grapes_S2",
	"farming:grapes_S3",
	"farming:grapes_S4",
	"farming:grapes_S5",
	"farming:grapes_S6",
	"farming:grapes_S7",
	"farming:grapes_S8",
	"farming:grapes_S9",
	"farming:grapes_S10",
	"farming:grapes_S11",
	"farming:grape_bush",
	"farming:green_onions",
	"farming:green_onion_S1",
	"farming:green_onion_S2",
	"farming:green_onion_S3",
	"farming:green_onion_S4",
	"farming:green_onion_S5",
	"farming:wild_green_onion",
	"farming:habanero",
	"farming:habanero_S1",
	"farming:habanero_S2",
	"farming:habanero_S3",
	"farming:habanero_S4",
	"farming:habanero_S5",
	"farming:habanero_S6",
	"farming:habanero_S7",
	"farming:habanero_S8",
	"farming:seed_hemp",
	"farming:hemp_leaf",
	"farming:hemp_oil",
	"farming:hemp_fibre",
	"farming:hemp_block",
	"farming:hemp_S1",
	"farming:hemp_S2",
	"farming:hemp_S3",
	"farming:hemp_S4",
	"farming:hemp_S5",
	"farming:hemp_S6",
	"farming:hemp_S7",
	"farming:hemp_S8",
	"farming:hops_seed_with_bine",
	"farming:hops_seed",
	"farming:hops",
	"farming:hops_S1",
	"farming:hops_S2",
	"farming:hops_S3",
	"farming:hops_S4",
	"farming:hops_S5",
	"farming:hops_S6",
	"farming:hops_S7",
	"farming:hops_S8",
	"farming:hops_S9",
	"farming:huckleberries",
	"farming:huckleberry_S1",
	"farming:huckleberry_S2",
	"farming:huckleberry_S3",
	"farming:huckleberry_S4",
	"farming:huckleberry_S5",
	"farming:huckleberry_S6",
	"farming:kohlrabi_seed",
	"farming:kohlrabi",
	"farming:kohlrabi_leaves_cooked",
	"farming:kohlrabi_cooked",
	"farming:kohlrabi_soup",
	"farming:kohlrabi_S1",
	"farming:kohlrabi_S2",
	"farming:kohlrabi_S3",
	"farming:kohlrabi_S4",
	"farming:kohlrabi_S5",
	"farming:kohlrabi_S6",
	"farming:kohlrabi_S7",
	"farming:leek_root",
	"farming:leek",
	"farming:leek_S1",
	"farming:leek_S2",
	"farming:leek_S3",
	"farming:leek_S4",
	"farming:leek_S5",
	"farming:leek_S6",
	"farming:lettuce_iceberg",
	"farming:iceberg_lettuce_S1",
	"farming:iceberg_lettuce_S2",
	"farming:iceberg_lettuce_S3",
	"farming:iceberg_lettuce_S4",
	"farming:iceberg_lettuce_S5",
	"farming:iceberg_lettuce_S6",
	"farming:iceberg_lettuce_S7",
	"farming:lettuce_romaine",
	"farming:romaine_lettuce_S1",
	"farming:romaine_lettuce_S2",
	"farming:romaine_lettuce_S3",
	"farming:romaine_lettuce_S4",
	"farming:romaine_lettuce_S5",
	"farming:maize_yellow",
	"farming:maize_red",
	"farming:maize_blue",
	"farming:maize_yellow_cooked",
	"farming:maize_red_cooked",
	"farming:maize_blue_cooked",
	"farming:masa_yellow",
	"farming:masa_red",
	"farming:masa_blue",
	"farming:maizestarch",
	"farming:ethanol_1",
	"farming:ethanol_2",
	"farming:ethanol_3",
	"farming:maize_S1",
	"farming:maize_S2",
	"farming:maize_S3",
	"farming:maize_S4",
	"farming:maize_S5",
	"farming:maize_S6",
	"farming:maize_S7",
	"farming:maize_S8",
	"farming:maize_S9",
	"farming:maize_S10",
	"farming:melon_seed",
	"farming:melon_slice",
	"farming:melon_seed_butter",
	"farming:melon_S1",
	"farming:melon_S2",
	"farming:melon_S3",
	"farming:melon_S4",
	"farming:melon_S7",
	"farming:seed_mint",
	"farming:mint_leaf",
	"farming:mint_S1",
	"farming:mint_S2",
	"farming:mint_S3",
	"farming:mint_S4",
	"farming:mint_S5",
	"farming:mustard_seed",
	"farming:mustard",
	"farming:mustard_S1",
	"farming:mustard_S2",
	"farming:mustard_S3",
	"farming:mustard_S4",
	"farming:mustard_S5",
	"farming:mustard_S6",
	"farming:mustard_S7",
	"farming:mustard_S8",
	"farming:seed_oat",
	"farming:oat",
	"farming:oat_flour",
	"farming:oat_dough",
	"farming:oat_bread",
	"farming:oat_S1",
	"farming:oat_S2",
	"farming:oat_S3",
	"farming:oat_S4",
	"farming:oat_S5",
	"farming:oat_S6",
	"farming:oat_S7",
	"farming:oat_S8",
	"farming:onion",
	"farming:onion_soup",
	"farming:onion_S1",
	"farming:onion_S2",
	"farming:onion_S3",
	"farming:onion_S4",
	"farming:onion_S5",
	"farming:parsley",
	"farming:parsley_S1",
	"farming:parsley_S2",
	"farming:parsley_S3",
	"farming:parsley_S4",
	"farming:parsley_S5",
	"farming:peanut",
	"farming:peanut_roasted",
	"farming:peanut_butter",
	"farming:peanut_S1",
	"farming:peanut_S2",
	"farming:peanut_S3",
	"farming:peanut_S4",
	"farming:peanut_S5",
	"farming:peanut_S6",
	"farming:peanut_S7",
	"farming:pea_snow",
	"farming:pea",
	"farming:pea_pod",
	"farming:pea_chick",
	"farming:pea_leaves",
	"farming:pea_soup",
	"farming:pea_S1",
	"farming:pea_S2",
	"farming:pea_S3",
	"farming:pea_S4",
	"farming:pea_S5",
	"farming:pea_S6",
	"farming:pea_S7",
	"farming:pea_S8",
	"farming:peppercorn",
	"farming:peppercorn_ground",
	"farming:peppercorn_S1",
	"farming:peppercorn_S2",
	"farming:peppercorn_S3",
	"farming:peppercorn_S4",
	"farming:peppercorn_S5",
	"farming:peppercorn_S6",
	"farming:peppercorn_S7",
	"farming:peppercorn_bush",
	"farming:pineapple_top",
	"farming:pineapple",
	"farming:pineapple_ring",
	"farming:pineapple_juice",
	"farming:pineapple_S1",
	"farming:pineapple_S2",
	"farming:pineapple_S3",
	"farming:pineapple_S4",
	"farming:pineapple_S5",
	"farming:pineapple_S6",
	"farming:pineapple_S7",
	"farming:pineapple_S8",
	"farming:pineapple_S9",
	"farming:pineapple_S10",
	"farming:potato",
	"farming:poisonous_potato",
	"farming:baked_potato",
	"farming:potato_salad",
	"farming:potato_S1",
	"farming:potato_S2",
	"farming:potato_S3",
	"farming:potato_S4",
	"farming:pumpkin_slice",
	"farming:pumpkin_seed",
	"farming:pumpkin_seed_roasted",
	"farming:pumpkin_bread",
	"farming:pumpkin_dough",
	"farming:pumpkin_spice",
	"farming:pumpkin_seed_butter",
	"farming:jackolantern",
	"farming:jackolantern_on",
	"farming:pumpkin_S1",
	"farming:pumpkin_S2",
	"farming:pumpkin_S3",
	"farming:pumpkin_S4",
	"farming:pumpkin_S5",
	"farming:pumpkin_S8",
	"farming:seed_quinoa",
	"farming:quinoa",
	"farming:quinoa_leaves",
	"farming:quinoa_cooked",
	"farming:quinoa_flour",
	"farming:quinoa_dough",
	"farming:quinoa_bread",
	"farming:quinoa_S1",
	"farming:quinoa_S2",
	"farming:quinoa_S3",
	"farming:quinoa_S4",
	"farming:quinoa_S5",
	"farming:quinoa_S6",
	"farming:wild_quinoa",
	"farming:raddish",
	"farming:raddish_leaves",
	"farming:raddish_S1",
	"farming:raddish_S2",
	"farming:raddish_S3",
	"farming:raddish_S4",
	"farming:raddish_S5",
	"farming:raddish_S6",
	"farming:raspberries",
	"farming:raspberry_leaves",
	"farming:smoothie_raspberry",
	"farming:raspberry_S1",
	"farming:raspberry_S2",
	"farming:raspberry_S3",
	"farming:raspberry_S4",
	"farming:raspberry_S5",
	"farming:raspberry_S6",
	"farming:red_beet_seed",
	"farming:red_beet",
	"farming:red_beet_leaves",
	"farming:red_beet_soup",
	"farming:red_beet_S1",
	"farming:red_beet_S2",
	"farming:red_beet_S3",
	"farming:red_beet_S4",
	"farming:red_beet_S5",
	"farming:red_beet_S6",
	"farming:rhubarb",
	"farming:rhubarb_S1",
	"farming:rhubarb_S2",
	"farming:rhubarb_S3",
	"farming:rhubarb_S4",
	"farming:seed_rice",
	"farming:rice",
	"farming:rice_cooked",
	"farming:rice_flour",
	"farming:rice_dough",
	"farming:rice_bread",
	"farming:rice_milk",
	"farming:rice_S1",
	"farming:rice_S2",
	"farming:rice_S3",
	"farming:rice_S4",
	"farming:rice_S5",
	"farming:rice_S6",
	"farming:rice_bush",
	"farming:rosebush_starter",
	"farming:rosebush_S1",
	"farming:rosebush_S2",
	"farming:rosebush_S3",
	"farming:rosebush_S4",
	"farming:rosebush_S5",
	"farming:rosebush_S6",
	"farming:rosebush_S7",
	"farming:rosebush_S8",
	"farming:rosemary",
	"farming:rosemary_S1",
	"farming:rosemary_S2",
	"farming:rosemary_S3",
	"farming:rosemary_S4",
	"farming:rosemary_S5",
	"farming:rosemary_S6",
	"farming:seed_rye",
	"farming:rye",
	"farming:rye_flour",
	"farming:rye_dough",
	"farming:rye_bread",
	"farming:rye_S1",
	"farming:rye_S2",
	"farming:rye_S3",
	"farming:rye_S4",
	"farming:rye_S5",
	"farming:rye_S6",
	"farming:rye_S7",
	"farming:rye_S8",
	"farming:strawberry",
	"farming:strawberry_S1",
	"farming:strawberry_S2",
	"farming:strawberry_S3",
	"farming:strawberry_S4",
	"farming:strawberry_S5",
	"farming:strawberry_S6",
	"farming:strawberry_S7",
	"farming:strawberry_S8",
	"farming:strawberry_S9",
	"farming:strawberry_S10",
	"farming:sugar_beet_seed",
	"farming:sugar_beet",
	"farming:sugar_beet_leaves",
	"farming:sugar_beet_S1",
	"farming:sugar_beet_S2",
	"farming:sugar_beet_S3",
	"farming:sugar_beet_S4",
	"farming:sugar_beet_S5",
	"farming:sugar_beet_S6",
	"farming:sunflower_seed",
	"farming:sunflower_seeds",
	"farming:sunflower_seeds_roasted",
	"farming:sunflower_root",
	"farming:sunflower_flour",
	"farming:sunflower_dough",
	"farming:sunflower_bread",
	"farming:sunflower_butter",
	"farming:sunflower_oil",
	"farming:sunflower_S1",
	"farming:sunflower_S2",
	"farming:sunflower_S3",
	"farming:sunflower_S4",
	"farming:sunflower_S5",
	"farming:sunflower_S6",
	"farming:sunflower_S7",
	"farming:sunflower_S8",
	"farming:sunflower_S9",
	"farming:sunflower_S10",
	"farming:sweet_pepper_seed",
	"farming:sweet_pepper_green",
	"farming:sweet_pepper_yellow",
	"farming:sweet_pepper_orange",
	"farming:sweet_pepper_red",
	"farming:sweet_pepper_purple",
	"farming:sweet_pepper_S1",
	"farming:sweet_pepper_S2",
	"farming:sweet_pepper_S3",
	"farming:sweet_pepper_S4",
	"farming:sweet_pepper_S5",
	"farming:sweet_pepper_S6",
	"farming:sweet_pepper_S7",
	"farming:sweet_pepper_S8",
	"farming:sweet_pepper_S9",
	"farming:sweet_pepper_S10",
	"farming:tea",
	"farming:tea_S1",
	"farming:tea_S2",
	"farming:tea_S3",
	"farming:tea_S4",
	"farming:tea_S5",
	"farming:tea_S6",
	"farming:tea_S7",
	"farming:teosinte",
	"farming:teosinte_S1",
	"farming:teosinte_S2",
	"farming:teosinte_S3",
	"farming:teosinte_S4",
	"farming:teosinte_S5",
	"farming:teosinte_S6",
	"farming:teosinte_S7",
	"farming:teosinte_S8",
	"farming:tomato",
	"farming:tomato_S1",
	"farming:tomato_S2",
	"farming:tomato_S3",
	"farming:tomato_S4",
	"farming:tomato_S5",
	"farming:tomato_S6",
	"farming:tomato_S7",
	"farming:tomato_S8",
	"farming:tomato_S9",
	"farming:turmeric",
	"farming:turmeric_S1",
	"farming:turmeric_S2",
	"farming:turmeric_S3",
	"farming:turmeric_S4",
	"farming:turmeric_S5",
	"farming:turmeric_S6",
	"farming:turmeric_S7",
	"farming:vanilla",
	"farming:vanillapole_S1",
	"farming:vanillapole_S2",
	"farming:vanillapole_S3",
	"farming:vanillapole_S4",
	"farming:vanillapole_S5",
	"farming:vanillapole_S6",
	"farming:vanillapole_S7",
	"farming:vanillabush",
	"farming:zucchini_green",
	"farming:zucchini_green_cooked",
	"farming:zucchini_yellow",
	"farming:zucchini_yellow_cooked",
	"farming:zucchini_S1",
	"farming:zucchini_S2",
	"farming:zucchini_S3",
	"farming:zucchini_S4",
	"farming:zucchini_S5",
	"farming:zucchini_S6",
	"farming:zucchini_S7",
	"farming:zucchini_S8",
	"farming:avocado_sapling",
	"farming:cherry_sapling",
	"farming:cinnamon_sapling",
	"farming:cocoa_sapling",
	"farming:fig_sapling",
	"farming:hazelnut_sapling",
	"farming:lemon_sapling",
	"farming:lime_sapling",
	"farming:mandarin_sapling",
	"farming:mango_sapling",
	"farming:mirabelle_sapling",
	"farming:nutmeg_sapling",
	"farming:olive_sapling",
	"farming:peach_sapling",
	"farming:pear_sapling",
	"farming:pecan_sapling",
	"farming:plum_sapling",
	"farming:pomegranate_sapling",
	"farming:walnut_sapling",
	"farming:avocado",
	"farming:avocado_pit",
	"farming:avocado_trunk",
	"farming:avocado_leaves",
	"farming:avocado_leaves_blooming",
	"farming:avocado_leaves_fruiting",
	"farming:beanstalk_trunk",
	"farming:beanstalk_sapling",
	"farming:beanstalk_leaves",
	"farming:cherry",
	"farming:cherry_trunk",
	"farming:cherry_wood",
	"farming:cherry_leaves",
	"farming:cherry_leaves_blooming",
	"farming:cherry_leaves_fruiting",
	"farming:cinnamon",
	"farming:cinnamon_trunk",
	"farming:cinnamon_trunk_peeling",
	"farming:cinnamon_leaves",
	"farming:cocoa_beans",
	"farming:cocoa_powder",
	"farming:dark_chocolate",
	"farming:milk_chocolate",
	"farming:white_chocolate",
	"farming:dark_chocolate_block",
	"farming:milk_chocolate_block",
	"farming:white_chocolate_block",
	"farming:cocoa_trunk",
	"farming:cocoa_trunk_blooming",
	"farming:cocoa_leaves",
	"farming:cocoa_1",
	"farming:cocoa_2",
	"farming:cocoa_3",
	"farming:cocoa_4",
	"farming:date",
	"farming:date_pit",
	"farming:date_palm_trunk",
	"farming:date_palm_wood",
	"farming:date_palm_leaves",
	"farming:dates_female_flowers",
	"farming:dates_1",
	"farming:dates_2",
	"farming:dates_3",
	"farming:dates_4",
	"farming:dates_male_flowers",
	"farming:date_palm_sapling",
	"farming:fig",
	"farming:fig_trunk",
	"farming:fig_leaves",
	"farming:fig_leaves_blooming",
	"farming:fig_leaves_fruiting",
	"farming:hazelnut",
	"farming:hazelnut_trunk",
	"farming:hazelnut_leaves",
	"farming:hazelnut_leaves_blooming",
	"farming:hazelnut_leaves_fruiting",
	"farming:lemon",
	"farming:lemon_trunk",
	"farming:lemon_leaves",
	"farming:lemon_leaves_blooming",
	"farming:lemon_leaves_fruiting",
	"farming:lime",
	"farming:lime_trunk",
	"farming:lime_leaves",
	"farming:lime_leaves_blooming",
	"farming:lime_leaves_fruiting",
	"farming:mandarin",
	"farming:mandarin_trunk",
	"farming:mandarin_trunk_blooming",
	"farming:mandarin_trunk_fruiting",
	"farming:mandarin_leaves",
	"farming:mandarin_leaves_blooming",
	"farming:mandarin_leaves_fruiting",
	"farming:mango",
	"farming:mango_trunk",
	"farming:mango_leaves",
	"farming:mango_leaves_blooming",
	"farming:mango_leaves_fruiting",
	"farming:mirabelle",
	"farming:mirabelle_trunk",
	"farming:mirabelle_leaves",
	"farming:mirabelle_leaves_blooming",
	"farming:mirabelle_leaves_fruiting",
	"farming:nutmeg",
	"farming:nutmeg_nut",
	"farming:nutmeg_trunk",
	"farming:nutmeg_leaves",
	"farming:nutmeg_leaves_blooming",
	"farming:nutmeg_leaves_fruiting",
	"farming:olive_green",
	"farming:olive_ripe",
	"farming:olive_oil",
	"farming:olive_trunk",
	"farming:olive_leaves",
	"farming:olive_leaves_blooming",
	"farming:olive_leaves_fruiting_green",
	"farming:olive_leaves_fruiting_ripe",
	"farming:peach",
	"farming:peach_pit",
	"farming:almond",
	"farming:almond_flour",
	"farming:almond_milk",
	"farming:almond_butter",
	"farming:almond_oil",
	"farming:peach_trunk",
	"farming:peach_leaves",
	"farming:peach_leaves_blooming",
	"farming:peach_leaves_fruiting",
	"farming:pear",
	"farming:pear_trunk",
	"farming:pear_leaves",
	"farming:pear_leaves_blooming",
	"farming:pear_leaves_fruiting",
	"farming:pecan",
	"farming:pecan_shelled",
	"farming:pecan_trunk",
	"farming:pecan_leaves",
	"farming:pecan_leaves_blooming",
	"farming:pecan_leaves_fruiting",
	"farming:plum",
	"farming:plum_pit",
	"farming:plum_trunk",
	"farming:plum_leaves",
	"farming:plum_leaves_blooming",
	"farming:plum_leaves_fruiting",
	"farming:pomegranate",
	"farming:pomegranate_trunk",
	"farming:pomegranate_wood",
	"farming:pomegranate_leaves",
	"farming:pomegranate_leaves_blooming",
	"farming:pomegranate_leaves_fruiting",
	"farming:walnut",
	"farming:soaked_walnuts",
	"farming:walnut_trunk",
	"farming:walnut_leaves",
	"farming:walnut_leaves_blooming",
	"farming:walnut_leaves_fruiting",
	"farming:sugar",
	"farming:red_beet_sugar",
	"farming:boiling_water",
	"farming:boiling_fresh_water",
	"farming:salt",
	"farming:cactus_juice",
	"farming:medicine",
	"fire:basic_flame",
	"fire:permanent_flame",
	"fire:firemite_flame",
	"fire:watermite_flame",
	"fire:flint_and_steel",
	"fire:charcoal_lump",
	"fire:grille",
	"fire:ash",
	"fire:fireplace",
	"fire:campfire",
	"fire:campfire_active",
	"fire:fireplace_with_embers",
	"fire:fireplace_with_embers_with_grille",
	"fire:fireplace_with_grille",
	"fire:campfire_with_grille",
	"fire:campfire_active_with_grille",
	"fire:charcoal_block",
	"fire:ash_block",
	"fireflies:firefly",
	"fireflies:bug_net",
	"fireflies:firefly_bottle",
	"flowers:rose",
	"flowers:tulip",
	"flowers:dandelion",
	"flowers:chrysanthemum_green",
	"flowers:geranium",
	"flowers:viola",
	"flowers:daisy",
	"flowers:tulip_black",
	"flowers:tulip_LO",
	"flowers:delphinium",
	"flowers:thistle",
	"flowers:lazarus",
	"flowers:mannagrass",
	"flowers:spider_plant",
	"flowers:amaryllis",
	"flowers:orchide",
	"flowers:purple_droops",
	"flowers:lion_tooth",
	"flowers:pansy_purple",
	"flowers:pansy_blue",
	"flowers:petunia_blue",
	"flowers:petunia_pink",
	"flowers:petunia_white",
	"flowers:lavender",
	"flowers:flame_lily",
	"flowers:foxglove_pink",
	"flowers:foxglove_purple",
	"flowers:gerbera",
	"flowers:lobelia",
	"flowers:lantana",
	"flowers:purple_allium",
	"flowers:oxeye_daisy",
	"flowers:mushroom_red",
	"flowers:mushroom_white",
	"flowers:mushroom_brown",
	"flowers:waterlily",
	"flowers:giant_waterlily",
	"flowers:giant_waterlily_flower",
	"keys:key",
	"keys:skeleton_key",
	"map:mapping_kit",
	"screwdriver:screwdriver",
	"spawn:mirror",
	"spawn:anak",
	"tnt:gunpowder",
	"tnt:tnt_stick",
	"tnt:tnt",
	"vessels:shelf",
	"vessels:wood_bowl",
	"vessels:clay_bowl",
	"vessels:clay_bowl_unfired",
	"vessels:glass_bottle",
	"vessels:glass_jar",
	"vessels:drinking_glass",
	"vessels:ceramic_lump",
	"vessels:ceramic_cup",
	"vessels:ceramic_cup_unfired",
	"vessels:ceramic_plate",
	"vessels:ceramic_plate_unfired",
	"vessels:mixing_bowl",
	"vessels:ceramic_vase",
	"vessels:ceramic_vase_unfired",
	"vessels:ceramic_vase_flowers",
	"vessels:steel_bottle",
	"vessels:glass_fragments",
	"xpanes:bar_flat",
	"xpanes:obsidian_pane_flat",
	"xpanes:pane_flat",
	"xpanes:door_steel_bar",
	"xpanes:trapdoor_steel_bar",
}) do
	frame.register(node)
end

-- inception!
frame.register("frame:empty")

